import '../schema/unified_type_schema.dart';
import 'generator_base.dart';

/// Generates Kotlin platform channel handler code for Android.
///
/// Produces a Kotlin `FlutterPlugin` class that:
/// - Registers a `MethodChannel`
/// - Dispatches method calls via `when(call.method)`
/// - Extracts arguments and converts types
/// - Returns results or errors
class KotlinGlueGenerator extends GeneratorBase {
  @override
  Map<String, String> generate(UnifiedTypeSchema schema) {
    final className = _toPascalCase(schema.package);
    final fileName = '${className}Plugin.kt';
    return {fileName: generateKotlinCode(schema)};
  }

  /// Generates the full Kotlin plugin source code.
  String generateKotlinCode(UnifiedTypeSchema schema) {
    final buffer = StringBuffer();
    final className = _toPascalCase(schema.package);
    final channelName = _toSnakeCase(schema.package);

    _writeHeader(buffer, schema);
    _writeImports(buffer);
    buffer.writeln();
    _writePluginClass(buffer, schema, className, channelName);

    return buffer.toString();
  }

  void _writeHeader(StringBuffer buffer, UnifiedTypeSchema schema) {
    buffer.writeln('// GENERATED CODE — DO NOT EDIT');
    buffer.writeln('// Generated by native_bridge_generator');
    buffer.writeln(
        '// Kotlin platform channel handler for ${schema.package}');
    buffer.writeln();
  }

  void _writeImports(StringBuffer buffer) {
    buffer.writeln('import io.flutter.embedding.engine.plugins.FlutterPlugin');
    buffer.writeln(
        'import io.flutter.plugin.common.MethodCall');
    buffer.writeln(
        'import io.flutter.plugin.common.MethodChannel');
    buffer.writeln(
        'import io.flutter.plugin.common.MethodChannel.MethodCallHandler');
    buffer.writeln(
        'import io.flutter.plugin.common.MethodChannel.Result');
  }

  void _writePluginClass(StringBuffer buffer, UnifiedTypeSchema schema,
      String className, String channelName) {
    buffer.writeln(
        'class ${className}Plugin : FlutterPlugin, MethodCallHandler {');
    buffer.writeln('    private lateinit var channel: MethodChannel');
    buffer.writeln();

    // onAttachedToEngine
    buffer.writeln(
        '    override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding) {');
    buffer.writeln(
        '        channel = MethodChannel(binding.binaryMessenger, "$channelName")');
    buffer.writeln('        channel.setMethodCallHandler(this)');
    buffer.writeln('    }');
    buffer.writeln();

    // onDetachedFromEngine
    buffer.writeln(
        '    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {');
    buffer.writeln('        channel.setMethodCallHandler(null)');
    buffer.writeln('    }');
    buffer.writeln();

    // onMethodCall
    buffer.writeln(
        '    override fun onMethodCall(call: MethodCall, result: Result) {');
    buffer.writeln('        when (call.method) {');

    // Top-level functions
    for (final fn in schema.functions) {
      _writeMethodCase(buffer, fn, indent: '            ');
    }

    // Class methods (prefixed with className)
    for (final cls in schema.classes) {
      for (final method in cls.methods) {
        _writeMethodCase(buffer, method,
            indent: '            ',
            prefix: '${cls.name}.');
      }
    }

    buffer.writeln(
        '            else -> result.notImplemented()');
    buffer.writeln('        }');
    buffer.writeln('    }');

    buffer.writeln('}');
  }

  void _writeMethodCase(StringBuffer buffer, UtsMethod method,
      {String indent = '', String prefix = ''}) {
    final methodName = '$prefix${method.name}';
    buffer.writeln('$indent"$methodName" -> {');

    // Extract arguments
    for (final param in method.parameters) {
      final kotlinType = _toKotlinType(param.type);
      if (param.isOptional || param.type.nullable) {
        buffer.writeln(
            '$indent    val ${param.name} = call.argument<$kotlinType>("${param.name}")');
      } else {
        buffer.writeln(
            '$indent    val ${param.name} = call.argument<$kotlinType>("${param.name}")!!');
      }
    }

    // Type conversion for special types
    for (final param in method.parameters) {
      final conversion = _argumentConversion(param);
      if (conversion != null) {
        buffer.writeln('$indent    $conversion');
      }
    }

    // Call the method and return result
    final returnType = method.returnType;
    if (returnType.kind == UtsTypeKind.voidType) {
      buffer.writeln('$indent    // TODO: Call native method');
      buffer.writeln('$indent    result.success(null)');
    } else if (returnType.kind == UtsTypeKind.future) {
      buffer.writeln('$indent    try {');
      buffer.writeln('$indent        // TODO: Call native async method');
      buffer.writeln('$indent        result.success(null)');
      buffer.writeln('$indent    } catch (e: Exception) {');
      buffer.writeln(
          '$indent        result.error("ERROR", e.message, e.stackTraceToString())');
      buffer.writeln('$indent    }');
    } else {
      buffer.writeln('$indent    try {');
      buffer.writeln('$indent        // TODO: Call native method');
      final resultConversion = _resultConversion(returnType);
      buffer.writeln(
          '$indent        result.success($resultConversion)');
      buffer.writeln('$indent    } catch (e: Exception) {');
      buffer.writeln(
          '$indent        result.error("ERROR", e.message, e.stackTraceToString())');
      buffer.writeln('$indent    }');
    }

    buffer.writeln('$indent}');
  }

  /// Maps UTS type to Kotlin type string for argument extraction.
  String _toKotlinType(UtsType type) {
    switch (type.kind) {
      case UtsTypeKind.primitive:
        switch (type.name) {
          case 'String':
            return 'String';
          case 'int':
            return 'Int';
          case 'double':
            return 'Double';
          case 'bool':
            return 'Boolean';
          case 'DateTime':
            return 'String'; // ISO 8601
          case 'Uint8List':
            return 'ByteArray';
          default:
            return 'Any';
        }
      case UtsTypeKind.object:
        return 'Map<String, Any?>';
      case UtsTypeKind.list:
        return 'List<Any?>';
      case UtsTypeKind.map:
        return 'Map<String, Any?>';
      case UtsTypeKind.enumType:
        return 'String';
      case UtsTypeKind.callback:
        return 'String'; // callback ID
      case UtsTypeKind.voidType:
        return 'Unit';
      case UtsTypeKind.dynamic:
        return 'Any?';
      default:
        return 'Any?';
    }
  }

  /// Returns additional conversion code for a parameter, or null if none needed.
  String? _argumentConversion(UtsParameter param) {
    if (param.type.kind == UtsTypeKind.primitive &&
        param.type.name == 'DateTime') {
      return 'val ${param.name}Date = java.text.SimpleDateFormat("yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'").parse(${param.name})';
    }
    return null;
  }

  /// Returns the Kotlin expression for converting a return value.
  String _resultConversion(UtsType type) {
    if (type.kind == UtsTypeKind.primitive && type.name == 'DateTime') {
      return 'java.text.SimpleDateFormat("yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'").format(nativeResult)';
    }
    return 'null /* TODO: convert native result */';
  }

  // --- Naming helpers ---

  static String _toSnakeCase(String input) {
    return input
        .replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_')
        .replaceAll(RegExp(r'_+'), '_')
        .replaceAll(RegExp(r'^_|_$'), '')
        .toLowerCase();
  }

  static String _toPascalCase(String input) {
    return input
        .replaceAll(RegExp(r'[^a-zA-Z0-9]'), ' ')
        .split(RegExp(r'\s+'))
        .where((s) => s.isNotEmpty)
        .map((s) => s[0].toUpperCase() + s.substring(1).toLowerCase())
        .join();
  }
}
