import '../schema/unified_type_schema.dart';
import 'dart_reserved.dart';
import 'generator_base.dart';

/// Generates Dart binding classes from a [UnifiedTypeSchema].
///
/// Produces a `.dart` file containing:
/// - A main class with static methods for top-level functions
/// - Data classes with toMap/fromMap for custom types
/// - Enum classes for enum definitions
class DartGenerator extends GeneratorBase {
  /// Escapes a name that is a Dart reserved word by appending `$`.
  static String _esc(String name) => escapeDartName(name);

  /// Method names inherited from Object that must not appear in generated
  /// interfaces or @override implementations (they conflict with dart:core).
  static const _objectReservedNames = {
    'toString',
    'hashCode',
    'noSuchMethod',
    'runtimeType',
    '==',
  };

  /// Removes duplicate methods by name, preferring instance over static.
  static List<UtsMethod> _deduplicateMethods(List<UtsMethod> methods) {
    final byName = <String, UtsMethod>{};
    for (final m in methods) {
      final existing = byName[m.name];
      if (existing == null) {
        byName[m.name] = m;
      } else if (existing.isStatic && !m.isStatic) {
        // Prefer instance methods over static ones
        byName[m.name] = m;
      }
    }
    // Preserve original order based on first occurrence of each name
    final seen = <String>{};
    return methods
        .where((m) => seen.add(m.name))
        .map((m) => byName[m.name]!)
        .toList();
  }

  /// Removes duplicate fields by name, keeping the first occurrence.
  static List<UtsField> _deduplicateFields(List<UtsField> fields) {
    final seen = <String>{};
    return fields.where((f) => seen.add(f.name)).toList();
  }

  /// Writes a multi-line doc comment, splitting on `\n`.
  static void _writeDoc(StringBuffer buffer, String? doc, String indent) {
    if (doc == null) return;
    for (final line in doc.split('\n')) {
      final trimmed = line.trimRight();
      if (trimmed.isEmpty) {
        buffer.writeln('$indent///');
      } else {
        buffer.writeln('$indent/// $trimmed');
      }
    }
  }

  @override
  Map<String, String> generate(UnifiedTypeSchema schema,
      {Map<String, String> customTypes = const {}}) {
    final fileName = _packageToFileName(schema.package);
    final code = generateDartCode(schema, customTypes: customTypes);
    return {fileName: code};
  }

  /// Generates the Dart source code for the given schema.
  String generateDartCode(UnifiedTypeSchema schema,
      {Map<String, String> customTypes = const {}}) {
    final buffer = StringBuffer();

    // File header
    buffer.writeln('// GENERATED CODE — DO NOT EDIT');
    buffer.writeln('// Generated by auto_interop_generator');
    buffer.writeln('//');
    buffer.writeln('// Package: ${schema.package}@${schema.version}');
    buffer.writeln('// Source: ${schema.source.name}');
    buffer.writeln(
        '// Platform availability: ${_platformAvailability(schema.source)}');
    buffer.writeln();
    buffer.writeln(
        '// ignore_for_file: unused_field, unused_import, camel_case_types, prefer_null_aware_operators');
    buffer.writeln();
    if (_needsTypedDataImport(schema)) {
      buffer.writeln("import 'dart:typed_data';");
      buffer.writeln();
    }
    buffer.writeln("import 'package:auto_interop/auto_interop.dart';");

    // Collect external nativeObject types that need stubs
    final externalTypes = _collectExternalNativeObjectTypes(schema);

    // Emit imports for custom type overrides
    final importedPaths = <String>{};
    for (final typeName in externalTypes.toList()..sort()) {
      if (customTypes.containsKey(typeName)) {
        final path = customTypes[typeName]!;
        if (!importedPaths.contains(path)) {
          buffer.writeln("import '$path';");
          importedPaths.add(path);
        }
        externalTypes.remove(typeName);
      }
    }
    buffer.writeln();

    // Generate opaque stub classes for remaining external nativeObject types
    final sortedStubs = externalTypes.toList()..sort();
    for (final typeName in sortedStubs) {
      _generateNativeObjectStub(buffer, typeName);
      buffer.writeln();
    }

    // Generate enum classes
    for (final enumDef in schema.enums) {
      _generateEnum(buffer, enumDef);
      buffer.writeln();
    }

    // Generate data classes (types)
    for (final typeDef in schema.types) {
      _generateDataClass(buffer, schema, typeDef);
      buffer.writeln();
    }

    // Generate binding interface + class (for top-level functions)
    if (schema.functions.isNotEmpty) {
      _generateBindingInterface(buffer, schema);
      buffer.writeln();
      _generateBindingClass(buffer, schema);
      buffer.writeln();
    }

    // Generate class interfaces + classes
    for (final classDef in schema.classes) {
      // Generate interface for concrete classes with instance methods
      if (classDef.kind == UtsClassKind.concreteClass &&
          classDef.methods.any((m) => !m.isStatic)) {
        _generateClassInterface(buffer, schema, classDef);
        buffer.writeln();
      }
      _generateClass(buffer, schema, classDef);
      buffer.writeln();
    }

    return buffer.toString();
  }

  void _generateBindingInterface(
      StringBuffer buffer, UnifiedTypeSchema schema) {
    final className = _packageToClassName(schema.package);

    buffer.writeln('abstract interface class ${className}Interface {');
    for (var i = 0; i < schema.functions.length; i++) {
      if (i > 0) buffer.writeln();
      _generateInterfaceMethodSignature(buffer, schema, schema.functions[i],
          indent: '  ');
    }
    buffer.writeln('}');
  }

  void _generateBindingClass(StringBuffer buffer, UnifiedTypeSchema schema) {
    final className = _packageToClassName(schema.package);
    final channelName = _packageToChannelName(schema.package);

    final hasStreamFunction =
        schema.functions.any((m) => m.returnType.kind == UtsTypeKind.stream);

    buffer.writeln('class $className implements ${className}Interface {');
    buffer.writeln(
        "  static final _channel = AutoInteropChannel('$channelName');");
    if (hasStreamFunction) {
      buffer.writeln(
          "  static final _eventChannel = AutoInteropEventChannel('$channelName');");
    }
    buffer.writeln();
    buffer.writeln('  static final $className instance = $className._();');
    buffer.writeln('  $className._();');
    buffer.writeln();

    for (final method in schema.functions) {
      _generateMethod(buffer, schema, method,
          indent: '  ', forceInstance: true, addOverride: true);
      buffer.writeln();
    }

    buffer.writeln('}');
  }

  void _generateClassInterface(
      StringBuffer buffer, UnifiedTypeSchema schema, UtsClass classDef) {
    _writeDoc(buffer, classDef.documentation, '');

    buffer.writeln('abstract interface class ${classDef.name}Interface {');
    final instanceMethods = _deduplicateMethods(classDef.methods)
        .where((m) => !m.isStatic && !_objectReservedNames.contains(m.name))
        .toList();
    for (var i = 0; i < instanceMethods.length; i++) {
      if (i > 0) buffer.writeln();
      _generateInterfaceMethodSignature(buffer, schema, instanceMethods[i],
          indent: '  ');
    }
    buffer.writeln('}');
  }

  void _generateClass(
      StringBuffer buffer, UnifiedTypeSchema schema, UtsClass classDef) {
    final channelName = _packageToChannelName(schema.package);

    // Documentation
    _writeDoc(buffer, classDef.documentation, '');

    // Determine if this class has instance methods (making it a reference type)
    final hasInstanceMethods = classDef.methods.any((m) => !m.isStatic);
    // Both concrete and abstract classes with instance methods are reference types
    // (abstract classes like Call/JsonElement are handle proxies on the Dart side)
    final isReferenceType = hasInstanceMethods;
    final isConcreteReferenceType =
        isReferenceType && classDef.kind != UtsClassKind.abstractClass;
    final isAbstractInterface =
        classDef.kind == UtsClassKind.abstractClass && !hasInstanceMethods;

    // Class declaration
    if (classDef.kind == UtsClassKind.abstractClass) {
      if (hasInstanceMethods) {
        // Abstract classes with instance methods become concrete handle proxies
        buffer.writeln('class ${classDef.name} {');
      } else {
        buffer.writeln('abstract interface class ${classDef.name} {');
      }
    } else if (classDef.kind == UtsClassKind.sealedClass) {
      // Check if any sealed subclasses are actually defined in the schema
      final definedNames = {
        ...schema.classes.map((c) => c.name),
        ...schema.types.map((t) => t.name),
      };
      final hasDefinedSubclasses =
          classDef.sealedSubclasses.any((sub) => definedNames.contains(sub));

      if (!hasDefinedSubclasses && classDef.sealedSubclasses.isNotEmpty) {
        // No subclasses defined in schema — generate as a simple enum
        // (common for Swift enums with associated values that can't be
        // represented in Dart; the case names are preserved for use as
        // platform channel strings)
        buffer.writeln('enum ${classDef.name} {');
        for (var i = 0; i < classDef.sealedSubclasses.length; i++) {
          final comma = i < classDef.sealedSubclasses.length - 1 ? ',' : ';';
          buffer.writeln('  ${_esc(classDef.sealedSubclasses[i])}$comma');
        }
        buffer.writeln('}');
        return;
      }

      buffer.writeln('sealed class ${classDef.name} {');
      // Generative constructor so subtypes can extend this class
      buffer.writeln('  ${classDef.name}();');
      // Polymorphic fromMap factory for sealed classes
      if (classDef.sealedSubclasses.isNotEmpty) {
        buffer.writeln(
            '  factory ${classDef.name}.fromMap(Map<String, dynamic> map) {');
        buffer.writeln("    switch (map['_type'] as String) {");
        for (final sub in classDef.sealedSubclasses) {
          buffer.writeln("      case '$sub':");
          buffer.writeln('        return $sub.fromMap(map);');
        }
        buffer.writeln('      default:');
        buffer.writeln(
            "        throw ArgumentError('Unknown ${classDef.name} type: \${map[\"_type\"]}');");
        buffer.writeln('    }');
        buffer.writeln('  }');
      }
    } else {
      // Resolve protocol interfaces that are known abstract classes in the schema
      final knownAbstractNames = schema.classes
          .where((c) => c.kind == UtsClassKind.abstractClass)
          .map((c) => c.name)
          .toSet();
      final protocolImpls = classDef.interfaces
          .where((i) => knownAbstractNames.contains(i))
          .toList();

      if (hasInstanceMethods) {
        final allImplements = [
          '${classDef.name}Interface',
          ...protocolImpls,
        ];
        buffer.writeln(
            'class ${classDef.name} implements ${allImplements.join(', ')} {');
      } else if (protocolImpls.isNotEmpty) {
        buffer.writeln(
            'class ${classDef.name} implements ${protocolImpls.join(', ')} {');
      } else {
        buffer.writeln('class ${classDef.name} {');
      }
    }

    // Channel for method invocations (also needed for create() factory)
    final hasStreamMethod =
        classDef.methods.any((m) => m.returnType.kind == UtsTypeKind.stream);
    final needsChannel =
        classDef.methods.isNotEmpty || classDef.constructorParameters != null;
    if (needsChannel) {
      buffer.writeln(
          "  static final _channel = AutoInteropChannel('$channelName');");
      if (hasStreamMethod) {
        buffer.writeln(
            "  static final _eventChannel = AutoInteropEventChannel('$channelName');");
      }
      buffer.writeln();
    }

    // Handle field for reference types (classes with instance methods)
    // or empty opaque classes (no fields, no methods — act as handle wrappers)
    final isOpaqueHandleType = !isReferenceType &&
        classDef.fields.isEmpty &&
        classDef.methods.isEmpty &&
        classDef.kind != UtsClassKind.sealedClass;
    if (isReferenceType || isOpaqueHandleType) {
      buffer.writeln('  final String _handle;');
      buffer.writeln();
      buffer.writeln('  ${classDef.name}._(this._handle);');
      buffer.writeln();
      buffer.writeln(
          '  static ${classDef.name} fromHandle(String handle) => ${classDef.name}._(handle);');
    }

    // Factory constructor for handle-based types (only when a public init was found)
    final needsCreateFactory = (isConcreteReferenceType || isOpaqueHandleType) &&
        classDef.constructorParameters != null;
    if (needsCreateFactory) {
      buffer.writeln();
      if (classDef.constructorParameters!.isNotEmpty) {
        // Builder-aware factory with named parameters
        final params = classDef.constructorParameters!.map((p) {
          final dartType = p.type.toDartType();
          if (p.isOptional || p.type.nullable) {
            final suffix =
                (dartType == 'dynamic' || dartType.endsWith('?')) ? '' : '?';
            return '$dartType$suffix ${_esc(p.name)}';
          }
          return 'required $dartType ${_esc(p.name)}';
        }).join(', ');
        buffer.writeln(
            '  static Future<${classDef.name}> create({$params}) async {');
        buffer.writeln(
            "    final handle = await _channel.invoke<String>('${classDef.name}._create', {");
        for (final p in classDef.constructorParameters!) {
          if (p.isOptional || p.type.nullable) {
            buffer.writeln(
                "      if (${_esc(p.name)} != null) '${p.name}': ${_serializeExpr(schema, p.type, _esc(p.name), nullChecked: true)},");
          } else {
            buffer.writeln(
                "      '${p.name}': ${_serializeExpr(schema, p.type, _esc(p.name))},");
          }
        }
        buffer.writeln('    });');
      } else {
        buffer.writeln('  static Future<${classDef.name}> create() async {');
        buffer.writeln(
            "    final handle = await _channel.invoke<String>('${classDef.name}._create');");
      }
      buffer.writeln('    return ${classDef.name}._(handle);');
      buffer.writeln('  }');
    }

    // Fields (only for non-reference types; reference types access state via handle)
    if (!isReferenceType && !isAbstractInterface) {
      for (final field in classDef.fields) {
        _writeDoc(buffer, field.documentation, '  ');
        final nullable = field.nullable ? '?' : '';
        buffer.writeln(
            '  final ${field.type.toDartType()}$nullable ${_esc(field.name)};');
      }

      if (classDef.fields.isNotEmpty) {
        buffer.writeln();
        // Constructor
        _generateConstructor(buffer, classDef);
        buffer.writeln();
        // fromMap factory
        _generateFromMap(buffer, schema, classDef);
        buffer.writeln();
        // toMap method
        _generateToMap(buffer, schema, classDef);
      }
    }

    // Methods — add @override for instance methods of concrete classes with interfaces
    final addOverrideToInstanceMethods =
        classDef.kind == UtsClassKind.concreteClass && hasInstanceMethods;
    final dedupedMethods = _deduplicateMethods(classDef.methods);
    final instanceNames =
        dedupedMethods.where((m) => !m.isStatic).map((m) => m.name).toSet();
    for (final method in dedupedMethods) {
      // Skip methods that conflict with Object members
      if (_objectReservedNames.contains(method.name)) continue;
      // Skip static methods whose name conflicts with an instance method
      if (method.isStatic && instanceNames.contains(method.name)) continue;
      // Skip 'create' — already emitted as a factory constructor above
      if (isConcreteReferenceType && method.name == 'create') continue;
      buffer.writeln();
      _generateMethod(buffer, schema, method,
          indent: '  ',
          addOverride: addOverrideToInstanceMethods && !method.isStatic,
          classPrefix: '${classDef.name}.',
          isInstanceMethod: !method.isStatic && isReferenceType);
    }

    // Dispose method for reference types
    if (isReferenceType) {
      buffer.writeln();
      buffer.writeln('  Future<void> dispose() async {');
      buffer.writeln(
          "    await _channel.invoke<void>('_dispose', {'_handle': _handle});");
      buffer.writeln('  }');
    }

    buffer.writeln('}');
  }

  void _generateInterfaceMethodSignature(
      StringBuffer buffer, UnifiedTypeSchema schema, UtsMethod method,
      {String indent = ''}) {
    _writeDoc(buffer, method.documentation, indent);

    final params = _buildParameterList(method.parameters);
    final effectiveReturnType = _effectiveReturnType(method.returnType);

    if (method.returnType.kind == UtsTypeKind.stream) {
      final elementType =
          method.returnType.typeArguments?.first.toDartType() ?? 'dynamic';
      buffer.writeln(
          '${indent}Stream<$elementType> ${_esc(method.name)}($params);');
    } else {
      final dartType = _userFacingDartType(schema, effectiveReturnType);
      final asyncReturnType =
          dartType == 'void' ? 'Future<void>' : 'Future<$dartType>';
      buffer.writeln('$indent$asyncReturnType ${_esc(method.name)}($params);');
    }
  }

  void _generateMethod(
      StringBuffer buffer, UnifiedTypeSchema schema, UtsMethod method,
      {String indent = '',
      bool forceInstance = false,
      bool addOverride = false,
      String classPrefix = '',
      bool isInstanceMethod = false}) {
    final channelMethod = '$classPrefix${method.name}';
    final effectiveReturnType = _effectiveReturnType(method.returnType);

    // Documentation
    _writeDoc(buffer, method.documentation, indent);

    // Warn about synchronous callback parameters (non-void return type)
    for (final param in method.parameters) {
      if (param.type.kind == UtsTypeKind.callback &&
          param.type.returnType != null &&
          param.type.returnType!.kind != UtsTypeKind.voidType) {
        buffer.writeln(
            '$indent/// **Warning:** The `${param.name}` callback is invoked asynchronously via');
        buffer.writeln(
            '$indent/// platform channels. It cannot return a value synchronously to the native side.');
        break;
      }
    }

    if (addOverride) {
      buffer.writeln('$indent@override');
    }

    final staticMod = (method.isStatic && !forceInstance) ? 'static ' : '';
    final params = _buildParameterList(method.parameters);

    // Stream return type: use EventChannel instead of MethodChannel
    if (method.returnType.kind == UtsTypeKind.stream) {
      final elementUtsType = method.returnType.typeArguments?.first;
      final elementType = elementUtsType?.toDartType() ?? 'dynamic';
      final needsStreamDeser = elementUtsType != null &&
          _needsDeserialization(schema, elementUtsType);
      // When deserialization is needed, receive raw data and map to typed objects
      final channelElementType = needsStreamDeser
          ? _streamChannelType(schema, elementUtsType)
          : elementType;
      buffer.writeln(
          '$indent${staticMod}Stream<$elementType> ${_esc(method.name)}($params) {');

      if (method.parameters.isNotEmpty || isInstanceMethod) {
        buffer.writeln(
            '$indent  return _eventChannel.receiveStream<$channelElementType>(');
        buffer.writeln('$indent    method: \'$channelMethod\',');
        buffer.writeln('$indent    arguments: {');
        if (isInstanceMethod) {
          buffer.writeln('$indent      \'_handle\': _handle,');
        }
        final positionalParams =
            method.parameters.where((p) => !p.isNamed).toList();
        final namedParams = method.parameters.where((p) => p.isNamed).toList();
        for (final param in positionalParams) {
          buffer.writeln(
              '$indent      \'${param.name}\': ${_serializeParam(schema, param)},');
        }
        for (final param in namedParams) {
          if (param.isOptional) {
            buffer.writeln(
                '$indent      if (${_esc(param.name)} != null) \'${param.name}\': ${_serializeParam(schema, param, nullChecked: true)},');
          } else {
            buffer.writeln(
                '$indent      \'${param.name}\': ${_serializeParam(schema, param)},');
          }
        }
        buffer.writeln('$indent    },');
        buffer.writeln('$indent  )${_streamMapChain(schema, elementUtsType)};');
      } else {
        buffer.writeln(
            '$indent  return _eventChannel.receiveStream<$channelElementType>(method: \'$channelMethod\')${_streamMapChain(schema, elementUtsType)};');
      }
      buffer.writeln('$indent}');
      return;
    }

    // Regular method: use MethodChannel
    final dartReturnType = _userFacingDartType(schema, effectiveReturnType);
    final asyncReturnType =
        dartReturnType == 'void' ? 'Future<void>' : 'Future<$dartReturnType>';

    buffer.writeln(
        '$indent$staticMod$asyncReturnType ${_esc(method.name)}($params) async {');

    // Determine channel invoke type and deserialization
    final channelType = _channelInvokeType(schema, effectiveReturnType);
    final needsDeserialize = _needsDeserialization(schema, effectiveReturnType);

    // Pre-generate callback wrappers for callbacks needing deserialization
    final wrappedCallbacks = <String>{};
    for (final param in method.parameters) {
      if (_callbackNeedsWrapping(schema, param.type)) {
        _generateCallbackWrapper(
            buffer, schema, _esc(param.name), param.type, indent);
        wrappedCallbacks.add(param.name);
      }
    }

    // Build arguments map
    final positionalParams =
        method.parameters.where((p) => !p.isNamed).toList();
    final namedParams = method.parameters.where((p) => p.isNamed).toList();
    final hasArgs = method.parameters.isNotEmpty || isInstanceMethod;

    if (hasArgs) {
      if (dartReturnType == 'void') {
        buffer.writeln(
            '$indent  await _channel.invoke<void>(\'$channelMethod\', {');
      } else {
        buffer.writeln(
            '$indent  final result = await _channel.invoke<$channelType>(\'$channelMethod\', {');
      }
      if (isInstanceMethod) {
        buffer.writeln('$indent    \'_handle\': _handle,');
      }
      for (final param in positionalParams) {
        final serExpr = wrappedCallbacks.contains(param.name)
            ? '_${_esc(param.name)}Id'
            : _serializeParam(schema, param);
        buffer.writeln('$indent    \'${param.name}\': $serExpr,');
      }
      for (final param in namedParams) {
        if (param.isOptional) {
          final serExpr = wrappedCallbacks.contains(param.name)
              ? '_${_esc(param.name)}Id'
              : _serializeParam(schema, param, nullChecked: true);
          buffer.writeln(
              '$indent    if (${_esc(param.name)} != null) \'${param.name}\': $serExpr,');
        } else {
          final serExpr = wrappedCallbacks.contains(param.name)
              ? '_${_esc(param.name)}Id'
              : _serializeParam(schema, param);
          buffer.writeln('$indent    \'${param.name}\': $serExpr,');
        }
      }
      buffer.writeln('$indent  });');

      if (dartReturnType != 'void') {
        if (needsDeserialize) {
          buffer.writeln(
              '$indent  return ${_deserializeResult(schema, effectiveReturnType, 'result')};');
        } else {
          buffer.writeln('$indent  return result;');
        }
      }
    } else {
      if (dartReturnType == 'void') {
        buffer.writeln(
            '$indent  await _channel.invoke<void>(\'$channelMethod\');');
      } else {
        buffer.writeln(
            '$indent  final result = await _channel.invoke<$channelType>(\'$channelMethod\');');
        if (needsDeserialize) {
          buffer.writeln(
              '$indent  return ${_deserializeResult(schema, effectiveReturnType, 'result')};');
        } else {
          buffer.writeln('$indent  return result;');
        }
      }
    }

    buffer.writeln('$indent}');
  }

  /// Unwraps `Future<T>` to `T` for the effective return type.
  ///
  /// Swift async/Kotlin suspend methods have `returnType.kind == future`,
  /// but the channel invoke already wraps the result in a Future, so we
  /// unwrap once to avoid `Future<Future<T>>`.
  UtsType _effectiveReturnType(UtsType returnType) {
    if (returnType.kind == UtsTypeKind.future) {
      return returnType.typeArguments?.first ?? UtsType.voidType();
    }
    return returnType;
  }

  /// Returns the user-facing Dart type string for a return type.
  ///
  /// For object types that are classes in the schema (reference types with
  /// instance methods), returns the class name directly.
  /// For data-class objects, returns the class name (deserialized from Map).
  String _userFacingDartType(UnifiedTypeSchema schema, UtsType type) {
    return type.toDartType();
  }

  /// Returns the type to use in `_channel.invoke<T>(...)`.
  ///
  /// Objects come back as Map, enums as String, nativeObjects as String handle.
  /// For list/map with complex elements, uses `List<dynamic>`/`Map<String, dynamic>`.
  String _channelInvokeType(UnifiedTypeSchema schema, UtsType type) {
    final suffix = type.nullable ? '?' : '';
    switch (type.kind) {
      case UtsTypeKind.object:
        if (_isReferenceTypeClass(schema, type.name)) {
          return 'String$suffix'; // handle
        }
        return 'Map<String, dynamic>$suffix';
      case UtsTypeKind.nativeObject:
        return 'String$suffix'; // handle
      case UtsTypeKind.enumType:
        return 'String$suffix';
      case UtsTypeKind.primitive:
        if (type.name == 'DateTime') return 'String$suffix';
        if (type.name == 'Duration') return 'int$suffix';
        if (type.name == 'Uri') return 'String$suffix';
        return type.toDartType();
      case UtsTypeKind.list:
        final elementType = type.typeArguments?.first;
        if (elementType != null && _needsDeserialization(schema, elementType)) {
          return 'List<dynamic>$suffix';
        }
        return type.toDartType();
      case UtsTypeKind.map:
        final keyType = type.typeArguments?.first;
        final valueType =
            type.typeArguments != null && type.typeArguments!.length > 1
                ? type.typeArguments![1]
                : null;
        if ((keyType != null && _needsDeserialization(schema, keyType)) ||
            (valueType != null && _needsDeserialization(schema, valueType))) {
          return 'Map<dynamic, dynamic>$suffix';
        }
        return type.toDartType();
      default:
        return type.toDartType();
    }
  }

  /// Whether the channel result needs deserialization.
  bool _needsDeserialization(UnifiedTypeSchema schema, UtsType type) {
    switch (type.kind) {
      case UtsTypeKind.object:
        return true; // fromMap or fromHandle
      case UtsTypeKind.nativeObject:
        return true; // fromHandle
      case UtsTypeKind.enumType:
        return true; // values.byName
      case UtsTypeKind.primitive:
        return type.name == 'DateTime' ||
            type.name == 'Duration' ||
            type.name == 'Uri';
      case UtsTypeKind.list:
        final elementType = type.typeArguments?.first;
        return elementType != null &&
            _needsDeserialization(schema, elementType);
      case UtsTypeKind.map:
        final keyType = type.typeArguments?.first;
        final valueType =
            type.typeArguments != null && type.typeArguments!.length > 1
                ? type.typeArguments![1]
                : null;
        return (keyType != null && _needsDeserialization(schema, keyType)) ||
            (valueType != null && _needsDeserialization(schema, valueType));
      default:
        return false;
    }
  }

  /// Returns the expression to deserialize a channel result.
  ///
  /// [depth] tracks nesting level for unique variable names in nested
  /// collections (e.g., `e0`, `e1` instead of shadowed `e`).
  String _deserializeResult(
      UnifiedTypeSchema schema, UtsType type, String varName,
      {int depth = 0}) {
    // Handle nullable types: wrap with null check
    if (type.nullable && _needsDeserialization(schema, type)) {
      final nonNullType = UtsType(
        kind: type.kind,
        name: type.name,
        nullable: false,
        ref: type.ref,
        typeArguments: type.typeArguments,
        parameterTypes: type.parameterTypes,
        returnType: type.returnType,
      );
      final inner =
          _deserializeResult(schema, nonNullType, varName, depth: depth);
      return '$varName != null ? $inner : null';
    }

    switch (type.kind) {
      case UtsTypeKind.object:
        if (_isReferenceTypeClass(schema, type.name)) {
          return '${type.name}.fromHandle($varName)';
        }
        if (!_isEmptyClassWithoutFromMap(schema, type.name)) {
          return '${type.name}.fromMap($varName)';
        }
        return '$varName as ${type.name}';
      case UtsTypeKind.nativeObject:
        return '${type.name}.fromHandle($varName)';
      case UtsTypeKind.enumType:
        return '${type.name}.values.byName($varName)';
      case UtsTypeKind.primitive:
        if (type.name == 'DateTime') {
          return 'DateTime.parse($varName)';
        }
        if (type.name == 'Duration') {
          return 'Duration(microseconds: $varName)';
        }
        if (type.name == 'Uri') {
          return 'Uri.parse($varName)';
        }
        return varName;
      case UtsTypeKind.list:
        final elementType = type.typeArguments?.first;
        if (elementType != null && _needsDeserialization(schema, elementType)) {
          final eVar = 'e$depth';
          final elementDeser = _deserializeListElement(
              schema, elementType, eVar,
              depth: depth + 1);
          return '$varName.map(($eVar) => $elementDeser).toList()';
        }
        return varName;
      case UtsTypeKind.map:
        final keyType = type.typeArguments?.first;
        final valueType =
            type.typeArguments != null && type.typeArguments!.length > 1
                ? type.typeArguments![1]
                : null;
        final keyNeedsDeser =
            keyType != null && _needsDeserialization(schema, keyType);
        final valueNeedsDeser =
            valueType != null && _needsDeserialization(schema, valueType);
        if (keyNeedsDeser || valueNeedsDeser) {
          final kVar = 'k$depth';
          final vVar = 'v$depth';
          final keyDartType = keyType?.toDartType() ?? 'String';
          final keyDeser = keyNeedsDeser
              ? _deserializeListElement(schema, keyType, kVar, depth: depth + 1)
              : '$kVar as $keyDartType';
          final valueDeser = valueNeedsDeser
              ? _deserializeListElement(schema, valueType, vVar,
                  depth: depth + 1)
              : vVar;
          return '$varName.map(($kVar, $vVar) => MapEntry($keyDeser, $valueDeser))';
        }
        return varName;
      default:
        return varName;
    }
  }

  /// Deserializes an element within a list or map, adding casts from dynamic.
  ///
  /// [depth] tracks nesting level for unique variable names.
  String _deserializeListElement(
      UnifiedTypeSchema schema, UtsType type, String varName,
      {int depth = 0}) {
    switch (type.kind) {
      case UtsTypeKind.object:
        if (_isReferenceTypeClass(schema, type.name)) {
          return '${type.name}.fromHandle($varName as String)';
        }
        if (!_isEmptyClassWithoutFromMap(schema, type.name)) {
          return '${type.name}.fromMap($varName as Map<String, dynamic>)';
        }
        return '$varName as ${type.name}';
      case UtsTypeKind.nativeObject:
        return '${type.name}.fromHandle($varName as String)';
      case UtsTypeKind.enumType:
        return '${type.name}.values.byName($varName as String)';
      case UtsTypeKind.primitive:
        if (type.name == 'DateTime') {
          return 'DateTime.parse($varName as String)';
        }
        if (type.name == 'Duration') {
          return 'Duration(microseconds: $varName as int)';
        }
        if (type.name == 'Uri') {
          return 'Uri.parse($varName as String)';
        }
        return varName;
      case UtsTypeKind.list:
        final elementType = type.typeArguments?.first;
        if (elementType != null && _needsDeserialization(schema, elementType)) {
          final eVar = 'e$depth';
          final inner = _deserializeListElement(schema, elementType, eVar,
              depth: depth + 1);
          return '($varName as List).map(($eVar) => $inner).toList()';
        }
        return varName;
      case UtsTypeKind.map:
        final keyType = type.typeArguments?.first;
        final valueType =
            type.typeArguments != null && type.typeArguments!.length > 1
                ? type.typeArguments![1]
                : null;
        final keyNeedsDeser =
            keyType != null && _needsDeserialization(schema, keyType);
        final valueNeedsDeser =
            valueType != null && _needsDeserialization(schema, valueType);
        if (keyNeedsDeser || valueNeedsDeser) {
          final kVar = 'k$depth';
          final vVar = 'v$depth';
          final keyDartType = keyType?.toDartType() ?? 'String';
          final keyDeser = keyNeedsDeser
              ? _deserializeListElement(schema, keyType, kVar, depth: depth + 1)
              : '$kVar as $keyDartType';
          final valueDeser = valueNeedsDeser
              ? _deserializeListElement(schema, valueType, vVar,
                  depth: depth + 1)
              : vVar;
          return '($varName as Map).map(($kVar, $vVar) => MapEntry($keyDeser, $valueDeser))';
        }
        return varName;
      default:
        return varName;
    }
  }

  /// Whether a callback type has parameterTypes that need deserialization.
  bool _callbackNeedsWrapping(UnifiedTypeSchema schema, UtsType type) {
    if (type.kind != UtsTypeKind.callback) return false;
    final paramTypes = type.parameterTypes;
    if (paramTypes == null || paramTypes.isEmpty) return false;
    return paramTypes.any((pt) => _needsDeserialization(schema, pt));
  }

  /// Generates a callback wrapper registration statement that deserializes
  /// raw platform data before calling the user's callback.
  void _generateCallbackWrapper(StringBuffer buffer, UnifiedTypeSchema schema,
      String paramName, UtsType callbackType, String indent) {
    final paramTypes = callbackType.parameterTypes ?? [];
    if (paramTypes.length == 1) {
      // Single parameter callback: receives a single dynamic value
      buffer.writeln(
          '$indent  final _${paramName}Id = CallbackManager.instance.register((dynamic raw) {');
      buffer.writeln(
          '$indent    ${_callbackDeserializeAndCall(schema, paramName, paramTypes, singleArg: true)}');
      buffer.writeln('$indent  });');
    } else {
      // Multi-parameter callback: receives individual dynamic args
      // (CallbackManager uses Function.apply which passes positional args)
      final paramSigs =
          List.generate(paramTypes.length, (i) => 'dynamic arg$i');
      buffer.writeln(
          '$indent  final _${paramName}Id = CallbackManager.instance.register((${paramSigs.join(', ')}) {');
      buffer.writeln(
          '$indent    ${_callbackDeserializeAndCall(schema, paramName, paramTypes, singleArg: false)}');
      buffer.writeln('$indent  });');
    }
  }

  /// Generates the deserialization + call expression inside a callback wrapper.
  String _callbackDeserializeAndCall(
      UnifiedTypeSchema schema, String callbackName, List<UtsType> paramTypes,
      {required bool singleArg}) {
    final lines = <String>[];
    final argNames = <String>[];

    for (var i = 0; i < paramTypes.length; i++) {
      final pt = paramTypes[i];
      final rawExpr = singleArg ? 'raw' : 'arg$i';
      // Use a different prefix for deserialized vars to avoid shadowing
      // the wrapper function parameter names (arg0, arg1, ...)
      final deserName = 'p$i';

      if (_needsDeserialization(schema, pt)) {
        switch (pt.kind) {
          case UtsTypeKind.object:
            if (_isReferenceTypeClass(schema, pt.name)) {
              lines.add(
                  'final $deserName = ${pt.name}.fromHandle($rawExpr as String);');
            } else if (!_isEmptyClassWithoutFromMap(schema, pt.name)) {
              lines.add(
                  'final map$i = ($rawExpr as Map).map((k, v) => MapEntry(k.toString(), v));');
              lines.add('final $deserName = ${pt.name}.fromMap(map$i);');
            } else {
              lines.add('final $deserName = $rawExpr as ${pt.name};');
            }
            break;
          case UtsTypeKind.nativeObject:
            lines.add(
                'final $deserName = ${pt.name}.fromHandle($rawExpr as String);');
            break;
          case UtsTypeKind.enumType:
            lines.add(
                'final $deserName = ${pt.name}.values.byName($rawExpr as String);');
            break;
          case UtsTypeKind.primitive:
            if (pt.name == 'DateTime') {
              lines.add(
                  'final $deserName = DateTime.parse($rawExpr as String);');
            } else if (pt.name == 'Duration') {
              lines.add(
                  'final $deserName = Duration(microseconds: $rawExpr as int);');
            } else if (pt.name == 'Uri') {
              lines.add('final $deserName = Uri.parse($rawExpr as String);');
            }
            break;
          default:
            break;
        }
        argNames.add(deserName);
      } else {
        argNames.add(rawExpr);
      }
    }

    lines.add('return $callbackName(${argNames.join(', ')});');
    return lines.join('\n    ');
  }

  /// Returns the channel type for stream elements that need deserialization.
  String _streamChannelType(UnifiedTypeSchema schema, UtsType type) {
    switch (type.kind) {
      case UtsTypeKind.object:
        if (_isReferenceTypeClass(schema, type.name)) {
          return 'String'; // handle
        }
        if (!_isEmptyClassWithoutFromMap(schema, type.name)) {
          return 'Map<Object?, Object?>';
        }
        return type.toDartType();
      case UtsTypeKind.nativeObject:
        return 'String'; // handle
      case UtsTypeKind.enumType:
        return 'String';
      case UtsTypeKind.primitive:
        if (type.name == 'DateTime') return 'String';
        if (type.name == 'Duration') return 'int';
        if (type.name == 'Uri') return 'String';
        return type.toDartType();
      default:
        return type.toDartType();
    }
  }

  /// Returns the `.map(...)` chain for deserializing stream elements.
  /// Returns empty string if no deserialization is needed.
  String _streamMapChain(UnifiedTypeSchema schema, UtsType? elementType) {
    if (elementType == null || !_needsDeserialization(schema, elementType)) {
      return '';
    }
    switch (elementType.kind) {
      case UtsTypeKind.object:
        if (_isReferenceTypeClass(schema, elementType.name)) {
          return '.map((raw) => ${elementType.name}.fromHandle(raw))';
        }
        if (!_isEmptyClassWithoutFromMap(schema, elementType.name)) {
          return '.map((raw) {\n'
              '    final map = (raw as Map).map((k, v) => MapEntry(k.toString(), v));\n'
              '    return ${elementType.name}.fromMap(map);\n'
              '  })';
        }
        return '.cast<${elementType.name}>()';
      case UtsTypeKind.nativeObject:
        return '.map((raw) => ${elementType.name}.fromHandle(raw))';
      case UtsTypeKind.enumType:
        return '.map((raw) => ${elementType.name}.values.byName(raw))';
      case UtsTypeKind.primitive:
        if (elementType.name == 'DateTime') {
          return '.map((raw) => DateTime.parse(raw))';
        }
        if (elementType.name == 'Duration') {
          return '.map((raw) => Duration(microseconds: raw))';
        }
        if (elementType.name == 'Uri') {
          return '.map((raw) => Uri.parse(raw))';
        }
        return '';
      default:
        return '';
    }
  }

  /// Checks if a named type is a reference type class (has instance methods).
  bool _isReferenceTypeClass(UnifiedTypeSchema schema, String typeName) {
    final cls = schema.classes.where((c) => c.name == typeName).toList();
    return cls.isNotEmpty && cls.first.methods.any((m) => !m.isStatic);
  }

  /// Checks if a named object type won't have `fromMap`/`toMap` generated.
  ///
  /// Returns true for:
  /// - Classes in [schema.classes] with no fields and no instance methods
  ///   (generate as bare `class Foo {}`)
  /// - Enums in [schema.enums] (use `.name`/`.values.byName()`, not fromMap)
  bool _isEmptyClassWithoutFromMap(UnifiedTypeSchema schema, String typeName) {
    // Enums never have fromMap/toMap
    if (schema.enums.any((e) => e.name == typeName)) return true;
    // Empty non-reference classes don't get fromMap/toMap
    final cls = schema.classes.where((c) => c.name == typeName).toList();
    if (cls.isEmpty) return false;
    final c = cls.first;
    final isRef = c.methods.any((m) => !m.isStatic);
    return !isRef && c.fields.isEmpty;
  }

  /// Checks if the schema uses `Uint8List` anywhere, requiring a
  /// `dart:typed_data` import.
  bool _needsTypedDataImport(UnifiedTypeSchema schema) {
    bool hasUint8List(UtsType type) {
      if (type.kind == UtsTypeKind.primitive && type.name == 'Uint8List') {
        return true;
      }
      if (type.typeArguments != null) {
        for (final arg in type.typeArguments!) {
          if (hasUint8List(arg)) return true;
        }
      }
      return false;
    }

    for (final fn in schema.functions) {
      if (hasUint8List(fn.returnType)) return true;
      for (final p in fn.parameters) {
        if (hasUint8List(p.type)) return true;
      }
    }
    for (final cls in schema.classes) {
      for (final field in cls.fields) {
        if (hasUint8List(field.type)) return true;
      }
      for (final m in cls.methods) {
        if (hasUint8List(m.returnType)) return true;
        for (final p in m.parameters) {
          if (hasUint8List(p.type)) return true;
        }
      }
    }
    for (final typeDef in schema.types) {
      for (final field in typeDef.fields) {
        if (hasUint8List(field.type)) return true;
      }
      for (final m in typeDef.methods) {
        if (hasUint8List(m.returnType)) return true;
        for (final p in m.parameters) {
          if (hasUint8List(p.type)) return true;
        }
      }
    }
    return false;
  }

  void _generateDataClass(
      StringBuffer buffer, UnifiedTypeSchema schema, UtsClass typeDef) {
    _writeDoc(buffer, typeDef.documentation, '');
    // Check if this is a subclass of a sealed class
    final extendsClause =
        typeDef.superclass != null ? ' extends ${typeDef.superclass}' : '';
    buffer.writeln('class ${typeDef.name}$extendsClause {');

    // Deduplicate fields to avoid duplicate_definition errors
    final dedupedFields = _deduplicateFields(typeDef.fields);
    // Create a copy with deduplicated fields for constructor/fromMap/toMap
    final dedupedTypeDef = UtsClass(
      name: typeDef.name,
      kind: typeDef.kind,
      fields: dedupedFields,
      methods: typeDef.methods,
      superclass: typeDef.superclass,
      interfaces: typeDef.interfaces,
      sealedSubclasses: typeDef.sealedSubclasses,
      documentation: typeDef.documentation,
      constructorParameters: typeDef.constructorParameters,
    );

    // Fields
    for (final field in dedupedFields) {
      _writeDoc(buffer, field.documentation, '  ');
      final nullable = field.nullable ? '?' : '';
      buffer.writeln(
          '  final ${field.type.toDartType()}$nullable ${_esc(field.name)};');
    }

    buffer.writeln();
    if (dedupedFields.isNotEmpty) {
      _generateConstructor(buffer, dedupedTypeDef);
    } else {
      // Explicit default constructor for zero-field classes (needed by fromMap)
      buffer.writeln('  ${typeDef.name}();');
    }
    buffer.writeln();
    _generateFromMap(buffer, schema, dedupedTypeDef);
    buffer.writeln();
    _generateToMap(buffer, schema, dedupedTypeDef);

    buffer.writeln('}');
  }

  void _generateConstructor(StringBuffer buffer, UtsClass classDef) {
    buffer.write('  ${classDef.name}({');
    final params = <String>[];
    for (final field in classDef.fields) {
      if (field.nullable) {
        params.add('this.${_esc(field.name)}');
      } else {
        params.add('required this.${_esc(field.name)}');
      }
    }
    buffer.write(params.join(', '));
    buffer.writeln('});');
  }

  void _generateFromMap(
      StringBuffer buffer, UnifiedTypeSchema schema, UtsClass classDef) {
    buffer.writeln(
        '  factory ${classDef.name}.fromMap(Map<String, dynamic> map) {');
    buffer.writeln('    return ${classDef.name}(');
    for (final field in classDef.fields) {
      final cast = _castFromMap(schema, field);
      buffer.writeln('      ${_esc(field.name)}: $cast,');
    }
    buffer.writeln('    );');
    buffer.writeln('  }');
  }

  void _generateToMap(
      StringBuffer buffer, UnifiedTypeSchema schema, UtsClass classDef) {
    buffer.writeln('  Map<String, dynamic> toMap() => {');
    for (final field in classDef.fields) {
      if (field.nullable) {
        buffer.writeln(
            "    if (${_esc(field.name)} != null) '${field.name}': ${_serializeField(schema, field, nullChecked: true)},");
      } else {
        buffer
            .writeln("    '${field.name}': ${_serializeField(schema, field)},");
      }
    }
    buffer.writeln('  };');
  }

  void _generateEnum(StringBuffer buffer, UtsEnum enumDef) {
    _writeDoc(buffer, enumDef.documentation, '');
    if (enumDef.values.isEmpty) {
      // Dart requires at least one enum constant. Emit a placeholder so the
      // type name is still valid when referenced elsewhere in the schema.
      buffer.writeln('enum ${enumDef.name} {');
      buffer.writeln('  _placeholder;');
      buffer.writeln('}');
      return;
    }
    buffer.writeln('enum ${enumDef.name} {');
    for (var i = 0; i < enumDef.values.length; i++) {
      final value = enumDef.values[i];
      _writeDoc(buffer, value.documentation, '  ');
      final comma = i < enumDef.values.length - 1 ? ',' : ';';
      buffer.writeln('  ${_esc(value.name)}$comma');
    }
    buffer.writeln('}');
  }

  // --- Helpers ---

  String _buildParameterList(List<UtsParameter> params) {
    final positional = params.where((p) => !p.isNamed).toList();
    final named = params.where((p) => p.isNamed).toList();

    final parts = <String>[];

    for (final p in positional) {
      parts.add('${p.type.toDartType()} ${_esc(p.name)}');
    }

    if (named.isNotEmpty) {
      final namedParts = <String>[];
      for (final p in named) {
        final dartType = p.type.toDartType();
        if (p.isOptional) {
          // dynamic is already nullable; types already ending with '?' don't need another
          final suffix =
              (dartType == 'dynamic' || dartType.endsWith('?')) ? '' : '?';
          namedParts.add('$dartType$suffix ${_esc(p.name)}');
        } else {
          namedParts.add('required $dartType ${_esc(p.name)}');
        }
      }
      parts.add('{${namedParts.join(', ')}}');
    }

    return parts.join(', ');
  }

  String _serializeParam(UnifiedTypeSchema schema, UtsParameter param,
      {bool nullChecked = false}) {
    return _serializeExpr(schema, param.type, _esc(param.name),
        nullChecked: nullChecked);
  }

  /// Returns the expression to serialize a value for sending over the channel.
  ///
  /// [depth] tracks nesting level for unique variable names in nested
  /// collections (e.g., `e0`, `e1` instead of shadowed `e`).
  /// [nullChecked] indicates the value has already been null-checked by the
  /// caller, so nullable operators should not be emitted.
  String _serializeExpr(UnifiedTypeSchema schema, UtsType type, String expr,
      {int depth = 0, bool nullChecked = false}) {
    final isNullable = type.nullable && !nullChecked;
    final dot = isNullable ? '?.' : '.';
    if (type.kind == UtsTypeKind.primitive && type.name == 'DateTime') {
      return '$expr${dot}toIso8601String()';
    }
    if (type.kind == UtsTypeKind.primitive && type.name == 'Duration') {
      return '$expr${dot}inMicroseconds';
    }
    if (type.kind == UtsTypeKind.primitive && type.name == 'Uri') {
      return '$expr${dot}toString()';
    }
    if (type.kind == UtsTypeKind.nativeObject) {
      return '$expr${isNullable ? '?' : ''}._handle';
    }
    if (type.kind == UtsTypeKind.object) {
      if (_isReferenceTypeClass(schema, type.name)) {
        return '$expr${isNullable ? '?' : ''}._handle';
      }
      // Only call toMap() on known data classes (defined in schema.types)
      if (schema.types.any((t) => t.name == type.name)) {
        return '$expr${dot}toMap()';
      }
      return expr;
    }
    if (type.kind == UtsTypeKind.enumType) {
      return '$expr.name';
    }
    if (type.kind == UtsTypeKind.callback) {
      return 'CallbackManager.instance.register($expr)';
    }
    if (type.kind == UtsTypeKind.list) {
      final elementType = type.typeArguments?.first;
      if (elementType != null && _needsTypeSerialization(elementType)) {
        final eVar = 'e$depth';
        return '$expr.map(($eVar) => ${_serializeExpr(schema, elementType, eVar, depth: depth + 1)}).toList()';
      }
    }
    if (type.kind == UtsTypeKind.map) {
      final keyType = type.typeArguments?.first;
      final valueType =
          type.typeArguments != null && type.typeArguments!.length > 1
              ? type.typeArguments![1]
              : null;
      final keyNeedsSer = keyType != null && _needsTypeSerialization(keyType);
      final valueNeedsSer =
          valueType != null && _needsTypeSerialization(valueType);
      if (keyNeedsSer || valueNeedsSer) {
        final kVar = 'k$depth';
        final vVar = 'v$depth';
        final keySer = keyNeedsSer
            ? _serializeExpr(schema, keyType, kVar, depth: depth + 1)
            : kVar;
        final valueSer = valueNeedsSer
            ? _serializeExpr(schema, valueType, vVar, depth: depth + 1)
            : vVar;
        return '$expr.map(($kVar, $vVar) => MapEntry($keySer, $valueSer))';
      }
    }
    return expr;
  }

  /// Whether a type needs serialization when sending over the channel.
  bool _needsTypeSerialization(UtsType type) {
    if (type.kind == UtsTypeKind.primitive && type.name == 'DateTime') {
      return true;
    }
    if (type.kind == UtsTypeKind.primitive && type.name == 'Duration') {
      return true;
    }
    if (type.kind == UtsTypeKind.primitive && type.name == 'Uri') {
      return true;
    }
    if (type.kind == UtsTypeKind.object) return true;
    if (type.kind == UtsTypeKind.nativeObject) return true;
    if (type.kind == UtsTypeKind.enumType) return true;
    if (type.kind == UtsTypeKind.callback) return true;
    if (type.kind == UtsTypeKind.list) {
      final elementType = type.typeArguments?.first;
      return elementType != null && _needsTypeSerialization(elementType);
    }
    if (type.kind == UtsTypeKind.map) {
      final keyType = type.typeArguments?.first;
      final valueType =
          type.typeArguments != null && type.typeArguments!.length > 1
              ? type.typeArguments![1]
              : null;
      return (keyType != null && _needsTypeSerialization(keyType)) ||
          (valueType != null && _needsTypeSerialization(valueType));
    }
    return false;
  }

  String _serializeField(UnifiedTypeSchema schema, UtsField field,
      {bool nullChecked = false}) {
    final eName = _esc(field.name);
    if (!field.nullable || nullChecked) {
      return _serializeExpr(schema, field.type, eName, nullChecked: true);
    }
    // Nullable: need ?. operator
    final type = field.type;
    if (type.kind == UtsTypeKind.primitive && type.name == 'DateTime') {
      return '$eName?.toIso8601String()';
    }
    if (type.kind == UtsTypeKind.primitive && type.name == 'Duration') {
      return '$eName?.inMicroseconds';
    }
    if (type.kind == UtsTypeKind.primitive && type.name == 'Uri') {
      return '$eName?.toString()';
    }
    if (type.kind == UtsTypeKind.nativeObject) {
      return '$eName?._handle';
    }
    if (type.kind == UtsTypeKind.object) {
      if (_isReferenceTypeClass(schema, type.name)) {
        return '$eName?._handle';
      }
      // Only call toMap() on known data classes (defined in schema.types)
      if (schema.types.any((t) => t.name == type.name)) {
        return '$eName?.toMap()';
      }
      return eName;
    }
    if (type.kind == UtsTypeKind.enumType) {
      return '$eName?.name';
    }
    if (type.kind == UtsTypeKind.list) {
      final elementType = type.typeArguments?.first;
      if (elementType != null && _needsTypeSerialization(elementType)) {
        return '$eName?.map((e0) => ${_serializeExpr(schema, elementType, 'e0', depth: 1)}).toList()';
      }
    }
    if (type.kind == UtsTypeKind.map) {
      final keyType = type.typeArguments?.first;
      final valueType =
          type.typeArguments != null && type.typeArguments!.length > 1
              ? type.typeArguments![1]
              : null;
      final keyNeedsSer = keyType != null && _needsTypeSerialization(keyType);
      final valueNeedsSer =
          valueType != null && _needsTypeSerialization(valueType);
      if (keyNeedsSer || valueNeedsSer) {
        final keySer = keyNeedsSer
            ? _serializeExpr(schema, keyType, 'k0', depth: 1)
            : 'k0';
        final valueSer = valueNeedsSer
            ? _serializeExpr(schema, valueType, 'v0', depth: 1)
            : 'v0';
        return '$eName?.map((k0, v0) => MapEntry($keySer, $valueSer))';
      }
    }
    return eName;
  }

  String _castFromMap(UnifiedTypeSchema schema, UtsField field) {
    final key = "'${field.name}'";
    final type = field.type;
    final nullable = field.nullable;

    if (type.kind == UtsTypeKind.primitive) {
      if (type.name == 'DateTime') {
        if (nullable) {
          return 'map[$key] != null ? DateTime.parse(map[$key] as String) : null';
        }
        return 'DateTime.parse(map[$key] as String)';
      }
      if (type.name == 'Duration') {
        if (nullable) {
          return 'map[$key] != null ? Duration(microseconds: map[$key] as int) : null';
        }
        return 'Duration(microseconds: map[$key] as int)';
      }
      if (type.name == 'Uri') {
        if (nullable) {
          return 'map[$key] != null ? Uri.parse(map[$key] as String) : null';
        }
        return 'Uri.parse(map[$key] as String)';
      }
      if (nullable) {
        return 'map[$key] as ${type.toDartType()}?';
      }
      return 'map[$key] as ${type.toDartType()}';
    }

    if (type.kind == UtsTypeKind.nativeObject) {
      if (nullable) {
        return 'map[$key] != null ? ${type.name}.fromHandle(map[$key] as String) : null';
      }
      return '${type.name}.fromHandle(map[$key] as String)';
    }

    if (type.kind == UtsTypeKind.object) {
      if (_isReferenceTypeClass(schema, type.name)) {
        if (nullable) {
          return 'map[$key] != null ? ${type.name}.fromHandle(map[$key] as String) : null';
        }
        return '${type.name}.fromHandle(map[$key] as String)';
      }
      if (!_isEmptyClassWithoutFromMap(schema, type.name)) {
        if (nullable) {
          return 'map[$key] != null ? ${type.name}.fromMap(map[$key] as Map<String, dynamic>) : null';
        }
        return '${type.name}.fromMap(map[$key] as Map<String, dynamic>)';
      }
      // Opaque/empty type — pass through as dynamic cast
      if (nullable) {
        return 'map[$key] as ${type.name}?';
      }
      return 'map[$key] as ${type.name}';
    }

    if (type.kind == UtsTypeKind.enumType) {
      if (nullable) {
        return 'map[$key] != null ? ${type.name}.values.byName(map[$key] as String) : null';
      }
      return '${type.name}.values.byName(map[$key] as String)';
    }

    if (type.kind == UtsTypeKind.list) {
      final elementType = type.typeArguments?.first;
      if (elementType != null && _needsDeserialization(schema, elementType)) {
        final elementDeser =
            _deserializeListElement(schema, elementType, 'e0', depth: 1);
        if (nullable) {
          return 'map[$key] != null ? (map[$key] as List).map((e0) => $elementDeser).toList() : null';
        }
        return '(map[$key] as List).map((e0) => $elementDeser).toList()';
      }
      // Platform channels return List<dynamic>; use .cast<T>() for typed lists
      final elementDartType = elementType?.toDartType() ?? 'dynamic';
      if (nullable) {
        return "map[$key] != null ? (map[$key] as List).cast<$elementDartType>() : null";
      }
      return '(map[$key] as List).cast<$elementDartType>()';
    }

    if (type.kind == UtsTypeKind.map) {
      final keyType = type.typeArguments?.first;
      final valueType =
          type.typeArguments != null && type.typeArguments!.length > 1
              ? type.typeArguments![1]
              : null;
      final keyNeedsDeser =
          keyType != null && _needsDeserialization(schema, keyType);
      final valueNeedsDeser =
          valueType != null && _needsDeserialization(schema, valueType);
      if (keyNeedsDeser || valueNeedsDeser) {
        final keyDartType = keyType?.toDartType() ?? 'String';
        final keyDeser = keyNeedsDeser
            ? _deserializeListElement(schema, keyType, 'k0', depth: 1)
            : 'k0 as $keyDartType';
        final valueDeser = valueNeedsDeser
            ? _deserializeListElement(schema, valueType, 'v0', depth: 1)
            : 'v0';
        if (nullable) {
          return 'map[$key] != null ? (map[$key] as Map).map((k0, v0) => MapEntry($keyDeser, $valueDeser)) : null';
        }
        return '(map[$key] as Map).map((k0, v0) => MapEntry($keyDeser, $valueDeser))';
      }
      // Platform channels return Map<Object?, Object?>; use .cast<K,V>()
      final keyDartType = keyType?.toDartType() ?? 'String';
      final valueDartType = valueType?.toDartType() ?? 'dynamic';
      if (nullable) {
        return "map[$key] != null ? (map[$key] as Map).cast<$keyDartType, $valueDartType>() : null";
      }
      return '(map[$key] as Map).cast<$keyDartType, $valueDartType>()';
    }

    if (nullable) {
      return 'map[$key] as ${type.toDartType()}?';
    }
    return 'map[$key] as ${type.toDartType()}';
  }

  /// Names from dart:core that must never be stubbed as opaque handles.
  static const _dartCoreNames = {
    'Object',
    'Function',
    'Type',
    'Symbol',
    'Null',
    'Duration',
    'DateTime',
    'Uri',
    'RegExp',
    'Match',
    'Error',
    'Exception',
    'StackTrace',
    'Stopwatch',
    'Comparable',
    'Iterable',
    'Iterator',
    'Pattern',
    'String',
    'int',
    'double',
    'bool',
    'num',
    'List',
    'Map',
    'Set',
    'Future',
    'Stream',
  };

  /// Collects all nativeObject type names referenced in the schema
  /// that are NOT defined in `definedTypeNames`.
  Set<String> _collectExternalNativeObjectTypes(UnifiedTypeSchema schema) {
    final defined = schema.definedTypeNames;
    final external = <String>{};

    void walkType(UtsType type) {
      if (type.kind == UtsTypeKind.nativeObject &&
          type.name != 'dynamic' &&
          !defined.contains(type.name) &&
          !_dartCoreNames.contains(type.name)) {
        external.add(type.name);
      }
      type.typeArguments?.forEach(walkType);
      type.parameterTypes?.forEach(walkType);
      if (type.returnType != null) walkType(type.returnType!);
    }

    for (final cls in [...schema.classes, ...schema.types]) {
      for (final field in cls.fields) {
        walkType(field.type);
      }
      for (final method in cls.methods) {
        walkType(method.returnType);
        for (final param in method.parameters) {
          walkType(param.type);
        }
      }
      if (cls.constructorParameters != null) {
        for (final param in cls.constructorParameters!) {
          walkType(param.type);
        }
      }
    }
    for (final func in schema.functions) {
      walkType(func.returnType);
      for (final param in func.parameters) {
        walkType(param.type);
      }
    }

    return external;
  }

  /// Generates an opaque stub class for a nativeObject type.
  void _generateNativeObjectStub(StringBuffer buffer, String typeName) {
    buffer.writeln('/// Opaque handle to a native $typeName object.');
    buffer.writeln('class $typeName {');
    buffer.writeln('  final String _handle;');
    buffer.writeln('  $typeName._(this._handle);');
    buffer.writeln(
        '  static $typeName fromHandle(String handle) => $typeName._(handle);');
    buffer.writeln('}');
  }

  /// Returns the set of nativeObject type names that were auto-stubbed
  /// (not user-provided via customTypes).
  Set<String> collectUnresolvedTypes(UnifiedTypeSchema schema,
      {Map<String, String> customTypes = const {}}) {
    final external = _collectExternalNativeObjectTypes(schema);
    external.removeAll(customTypes.keys);
    return external;
  }

  String _packageToFileName(String packageName) {
    return '${_toSnakeCase(packageName)}.dart';
  }

  String _packageToClassName(String packageName) {
    return _toPascalCase(packageName);
  }

  String _packageToChannelName(String packageName) {
    return _toSnakeCase(packageName);
  }

  static String _toSnakeCase(String input) {
    return input
        .replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_')
        .replaceAll(RegExp(r'_+'), '_')
        .replaceAll(RegExp(r'^_|_$'), '')
        .toLowerCase();
  }

  static String _toPascalCase(String input) {
    return input
        .replaceAll(RegExp(r'[^a-zA-Z0-9]'), ' ')
        .split(RegExp(r'\s+'))
        .where((s) => s.isNotEmpty)
        .map((s) => s[0].toUpperCase() + s.substring(1).toLowerCase())
        .join();
  }

  static String _platformAvailability(PackageSource source) {
    switch (source) {
      case PackageSource.npm:
        return 'Web only (npm package)';
      case PackageSource.cocoapods:
        return 'iOS and macOS only (CocoaPods package)';
      case PackageSource.spm:
        return 'iOS and macOS only (Swift Package Manager)';
      case PackageSource.gradle:
        return 'Android only (Gradle/Maven package)';
    }
  }
}
