import '../schema/unified_type_schema.dart';
import 'generator_base.dart';

/// Generates Dart binding classes from a [UnifiedTypeSchema].
///
/// Produces a `.dart` file containing:
/// - A main class with static methods for top-level functions
/// - Data classes with toMap/fromMap for custom types
/// - Enum classes for enum definitions
class DartGenerator extends GeneratorBase {
  @override
  Map<String, String> generate(UnifiedTypeSchema schema) {
    final fileName = _packageToFileName(schema.package);
    final code = generateDartCode(schema);
    return {fileName: code};
  }

  /// Generates the Dart source code for the given schema.
  String generateDartCode(UnifiedTypeSchema schema) {
    final buffer = StringBuffer();

    // File header
    buffer.writeln('// GENERATED CODE — DO NOT EDIT');
    buffer.writeln('// Generated by auto_interop_generator');
    buffer.writeln();
    buffer.writeln("import 'package:auto_interop/auto_interop.dart';");
    buffer.writeln();

    // Generate enum classes
    for (final enumDef in schema.enums) {
      _generateEnum(buffer, enumDef);
      buffer.writeln();
    }

    // Generate data classes (types)
    for (final typeDef in schema.types) {
      _generateDataClass(buffer, typeDef);
      buffer.writeln();
    }

    // Generate binding interface + class (for top-level functions)
    if (schema.functions.isNotEmpty) {
      _generateBindingInterface(buffer, schema);
      buffer.writeln();
      _generateBindingClass(buffer, schema);
      buffer.writeln();
    }

    // Generate class interfaces + classes
    for (final classDef in schema.classes) {
      // Generate interface for concrete classes with instance methods
      if (classDef.kind == UtsClassKind.concreteClass &&
          classDef.methods.any((m) => !m.isStatic)) {
        _generateClassInterface(buffer, classDef);
        buffer.writeln();
      }
      _generateClass(buffer, schema, classDef);
      buffer.writeln();
    }

    return buffer.toString();
  }

  void _generateBindingInterface(
      StringBuffer buffer, UnifiedTypeSchema schema) {
    final className = _packageToClassName(schema.package);

    buffer.writeln('abstract interface class ${className}Interface {');
    for (var i = 0; i < schema.functions.length; i++) {
      if (i > 0) buffer.writeln();
      _generateInterfaceMethodSignature(
          buffer, schema.functions[i], indent: '  ');
    }
    buffer.writeln('}');
  }

  void _generateBindingClass(
      StringBuffer buffer, UnifiedTypeSchema schema) {
    final className = _packageToClassName(schema.package);
    final channelName = _packageToChannelName(schema.package);

    final hasStreamFunction = schema.functions.any(
        (m) => m.returnType.kind == UtsTypeKind.stream);

    buffer.writeln('class $className implements ${className}Interface {');
    buffer.writeln(
        "  static const _channel = AutoInteropChannel('$channelName');");
    if (hasStreamFunction) {
      buffer.writeln(
          "  static const _eventChannel = AutoInteropEventChannel('$channelName');");
    }
    buffer.writeln();
    buffer.writeln('  static final $className instance = $className._();');
    buffer.writeln('  $className._();');
    buffer.writeln();

    for (final method in schema.functions) {
      _generateMethod(buffer, method,
          indent: '  ', forceInstance: true, addOverride: true);
      buffer.writeln();
    }

    buffer.writeln('}');
  }

  void _generateClassInterface(
      StringBuffer buffer, UtsClass classDef) {
    if (classDef.documentation != null) {
      buffer.writeln('/// ${classDef.documentation}');
    }

    buffer.writeln('abstract interface class ${classDef.name}Interface {');
    final instanceMethods =
        classDef.methods.where((m) => !m.isStatic).toList();
    for (var i = 0; i < instanceMethods.length; i++) {
      if (i > 0) buffer.writeln();
      _generateInterfaceMethodSignature(
          buffer, instanceMethods[i], indent: '  ');
    }
    buffer.writeln('}');
  }

  void _generateClass(
      StringBuffer buffer, UnifiedTypeSchema schema, UtsClass classDef) {
    final channelName = _packageToChannelName(schema.package);

    // Documentation
    if (classDef.documentation != null) {
      buffer.writeln('/// ${classDef.documentation}');
    }

    // Class declaration
    final hasInstanceMethods = classDef.methods.any((m) => !m.isStatic);
    if (classDef.kind == UtsClassKind.abstractClass) {
      buffer.writeln('abstract interface class ${classDef.name} {');
    } else if (classDef.kind == UtsClassKind.sealedClass) {
      buffer.writeln('sealed class ${classDef.name} {');
    } else if (hasInstanceMethods) {
      buffer.writeln(
          'class ${classDef.name} implements ${classDef.name}Interface {');
    } else {
      buffer.writeln('class ${classDef.name} {');
    }

    // Channel for method invocations
    final hasStreamMethod = classDef.methods.any(
        (m) => m.returnType.kind == UtsTypeKind.stream);
    if (classDef.methods.isNotEmpty) {
      buffer.writeln(
          "  static const _channel = AutoInteropChannel('$channelName');");
      if (hasStreamMethod) {
        buffer.writeln(
            "  static const _eventChannel = AutoInteropEventChannel('$channelName');");
      }
      buffer.writeln();
    }

    // Fields
    for (final field in classDef.fields) {
      if (field.documentation != null) {
        buffer.writeln('  /// ${field.documentation}');
      }
      final nullable = field.nullable ? '?' : '';
      buffer.writeln(
          '  final ${field.type.toDartType()}$nullable ${field.name};');
    }

    if (classDef.fields.isNotEmpty) {
      buffer.writeln();
      // Constructor
      _generateConstructor(buffer, classDef);
      buffer.writeln();
      // fromMap factory
      _generateFromMap(buffer, classDef);
      buffer.writeln();
      // toMap method
      _generateToMap(buffer, classDef);
    }

    // Methods — add @override for instance methods of concrete classes with interfaces
    final addOverrideToInstanceMethods =
        classDef.kind == UtsClassKind.concreteClass && hasInstanceMethods;
    for (final method in classDef.methods) {
      buffer.writeln();
      _generateMethod(buffer, method,
          indent: '  ',
          addOverride:
              addOverrideToInstanceMethods && !method.isStatic);
    }

    buffer.writeln('}');
  }

  void _generateInterfaceMethodSignature(
      StringBuffer buffer, UtsMethod method,
      {String indent = ''}) {
    if (method.documentation != null) {
      buffer.writeln('$indent/// ${method.documentation}');
    }

    final params = _buildParameterList(method.parameters);

    if (method.returnType.kind == UtsTypeKind.stream) {
      final elementType =
          method.returnType.typeArguments?.first.toDartType() ?? 'dynamic';
      buffer.writeln(
          '${indent}Stream<$elementType> ${method.name}($params);');
    } else {
      final returnType = method.returnType.toDartType();
      final asyncReturnType =
          returnType == 'void' ? 'Future<void>' : 'Future<$returnType>';
      buffer.writeln(
          '$indent$asyncReturnType ${method.name}($params);');
    }
  }

  void _generateMethod(StringBuffer buffer, UtsMethod method,
      {String indent = '',
      bool forceInstance = false,
      bool addOverride = false}) {
    // Documentation
    if (method.documentation != null) {
      buffer.writeln('$indent/// ${method.documentation}');
    }

    if (addOverride) {
      buffer.writeln('$indent@override');
    }

    final staticMod =
        (method.isStatic && !forceInstance) ? 'static ' : '';
    final params = _buildParameterList(method.parameters);

    // Stream return type: use EventChannel instead of MethodChannel
    if (method.returnType.kind == UtsTypeKind.stream) {
      final elementType =
          method.returnType.typeArguments?.first.toDartType() ?? 'dynamic';
      buffer.writeln(
          '$indent${staticMod}Stream<$elementType> ${method.name}($params) {');

      if (method.parameters.isNotEmpty) {
        buffer.writeln(
            '$indent  return _eventChannel.receiveStream<$elementType>(');
        buffer.writeln('$indent    method: \'${method.name}\',');
        buffer.writeln('$indent    arguments: {');
        final positionalParams =
            method.parameters.where((p) => !p.isNamed).toList();
        final namedParams =
            method.parameters.where((p) => p.isNamed).toList();
        for (final param in positionalParams) {
          buffer.writeln(
              '$indent      \'${param.name}\': ${_serializeParam(param)},');
        }
        for (final param in namedParams) {
          if (param.isOptional) {
            buffer.writeln(
                '$indent      if (${param.name} != null) \'${param.name}\': ${_serializeParam(param)},');
          } else {
            buffer.writeln(
                '$indent      \'${param.name}\': ${_serializeParam(param)},');
          }
        }
        buffer.writeln('$indent    },');
        buffer.writeln('$indent  );');
      } else {
        buffer.writeln(
            '$indent  return _eventChannel.receiveStream<$elementType>(method: \'${method.name}\');');
      }
      buffer.writeln('$indent}');
      return;
    }

    // Regular method: use MethodChannel
    final returnType = method.returnType.toDartType();
    final asyncReturnType =
        returnType == 'void' ? 'Future<void>' : 'Future<$returnType>';

    buffer.writeln(
        '$indent$staticMod$asyncReturnType ${method.name}($params) async {');

    // Build arguments map
    final positionalParams =
        method.parameters.where((p) => !p.isNamed).toList();
    final namedParams = method.parameters.where((p) => p.isNamed).toList();

    if (method.parameters.isNotEmpty) {
      buffer.writeln(
          '$indent  final result = await _channel.invoke<$returnType>(\'${method.name}\', {');
      for (final param in positionalParams) {
        buffer.writeln(
            '$indent    \'${param.name}\': ${_serializeParam(param)},');
      }
      for (final param in namedParams) {
        if (param.isOptional) {
          buffer.writeln(
              '$indent    if (${param.name} != null) \'${param.name}\': ${_serializeParam(param)},');
        } else {
          buffer.writeln(
              '$indent    \'${param.name}\': ${_serializeParam(param)},');
        }
      }
      buffer.writeln('$indent  });');

      if (returnType != 'void') {
        buffer.writeln('$indent  return result;');
      }
    } else {
      if (returnType == 'void') {
        buffer.writeln(
            '$indent  await _channel.invoke<void>(\'${method.name}\');');
      } else {
        buffer.writeln(
            '$indent  final result = await _channel.invoke<$returnType>(\'${method.name}\');');
        buffer.writeln('$indent  return result;');
      }
    }

    buffer.writeln('$indent}');
  }

  void _generateDataClass(StringBuffer buffer, UtsClass typeDef) {
    if (typeDef.documentation != null) {
      buffer.writeln('/// ${typeDef.documentation}');
    }
    buffer.writeln('class ${typeDef.name} {');

    // Fields
    for (final field in typeDef.fields) {
      if (field.documentation != null) {
        buffer.writeln('  /// ${field.documentation}');
      }
      final nullable = field.nullable ? '?' : '';
      buffer.writeln(
          '  final ${field.type.toDartType()}$nullable ${field.name};');
    }

    if (typeDef.fields.isNotEmpty) {
      buffer.writeln();
      _generateConstructor(buffer, typeDef);
      buffer.writeln();
      _generateFromMap(buffer, typeDef);
      buffer.writeln();
      _generateToMap(buffer, typeDef);
    }

    buffer.writeln('}');
  }

  void _generateConstructor(StringBuffer buffer, UtsClass classDef) {
    buffer.write('  ${classDef.name}({');
    final params = <String>[];
    for (final field in classDef.fields) {
      if (field.nullable) {
        params.add('this.${field.name}');
      } else {
        params.add('required this.${field.name}');
      }
    }
    buffer.write(params.join(', '));
    buffer.writeln('});');
  }

  void _generateFromMap(StringBuffer buffer, UtsClass classDef) {
    buffer.writeln(
        '  factory ${classDef.name}.fromMap(Map<String, dynamic> map) {');
    buffer.writeln('    return ${classDef.name}(');
    for (final field in classDef.fields) {
      final cast = _castFromMap(field);
      buffer.writeln('      ${field.name}: $cast,');
    }
    buffer.writeln('    );');
    buffer.writeln('  }');
  }

  void _generateToMap(StringBuffer buffer, UtsClass classDef) {
    buffer.writeln('  Map<String, dynamic> toMap() => {');
    for (final field in classDef.fields) {
      if (field.nullable) {
        buffer.writeln(
            "    if (${field.name} != null) '${field.name}': ${_serializeField(field)},");
      } else {
        buffer.writeln(
            "    '${field.name}': ${_serializeField(field)},");
      }
    }
    buffer.writeln('  };');
  }

  void _generateEnum(StringBuffer buffer, UtsEnum enumDef) {
    if (enumDef.documentation != null) {
      buffer.writeln('/// ${enumDef.documentation}');
    }
    buffer.writeln('enum ${enumDef.name} {');
    for (var i = 0; i < enumDef.values.length; i++) {
      final value = enumDef.values[i];
      if (value.documentation != null) {
        buffer.writeln('  /// ${value.documentation}');
      }
      final comma = i < enumDef.values.length - 1 ? ',' : ';';
      buffer.writeln('  ${value.name}$comma');
    }
    buffer.writeln('}');
  }

  // --- Helpers ---

  String _buildParameterList(List<UtsParameter> params) {
    final positional = params.where((p) => !p.isNamed).toList();
    final named = params.where((p) => p.isNamed).toList();

    final parts = <String>[];

    for (final p in positional) {
      parts.add('${p.type.toDartType()} ${p.name}');
    }

    if (named.isNotEmpty) {
      final namedParts = <String>[];
      for (final p in named) {
        if (p.isOptional) {
          namedParts.add('${p.type.toDartType()}? ${p.name}');
        } else {
          namedParts.add('required ${p.type.toDartType()} ${p.name}');
        }
      }
      parts.add('{${namedParts.join(', ')}}');
    }

    return parts.join(', ');
  }

  String _serializeParam(UtsParameter param) {
    final type = param.type;
    if (type.kind == UtsTypeKind.primitive && type.name == 'DateTime') {
      return '${param.name}.toIso8601String()';
    }
    if (type.kind == UtsTypeKind.object) {
      return '${param.name}.toMap()';
    }
    if (type.kind == UtsTypeKind.enumType) {
      return '${param.name}.name';
    }
    if (type.kind == UtsTypeKind.callback) {
      return 'CallbackManager.instance.register(${param.name})';
    }
    return param.name;
  }

  String _serializeField(UtsField field) {
    final type = field.type;
    if (type.kind == UtsTypeKind.primitive && type.name == 'DateTime') {
      if (field.nullable) {
        return '${field.name}?.toIso8601String()';
      }
      return '${field.name}.toIso8601String()';
    }
    if (type.kind == UtsTypeKind.object) {
      if (field.nullable) {
        return '${field.name}?.toMap()';
      }
      return '${field.name}.toMap()';
    }
    if (type.kind == UtsTypeKind.enumType) {
      if (field.nullable) {
        return '${field.name}?.name';
      }
      return '${field.name}.name';
    }
    return field.name;
  }

  String _castFromMap(UtsField field) {
    final key = "'${field.name}'";
    final type = field.type;
    final nullable = field.nullable;

    if (type.kind == UtsTypeKind.primitive) {
      if (type.name == 'DateTime') {
        if (nullable) {
          return 'map[$key] != null ? DateTime.parse(map[$key] as String) : null';
        }
        return 'DateTime.parse(map[$key] as String)';
      }
      if (nullable) {
        return 'map[$key] as ${type.toDartType()}?';
      }
      return 'map[$key] as ${type.toDartType()}';
    }

    if (type.kind == UtsTypeKind.object) {
      if (nullable) {
        return 'map[$key] != null ? ${type.name}.fromMap(map[$key] as Map<String, dynamic>) : null';
      }
      return '${type.name}.fromMap(map[$key] as Map<String, dynamic>)';
    }

    if (type.kind == UtsTypeKind.enumType) {
      if (nullable) {
        return 'map[$key] != null ? ${type.name}.values.byName(map[$key] as String) : null';
      }
      return '${type.name}.values.byName(map[$key] as String)';
    }

    if (nullable) {
      return 'map[$key] as ${type.toDartType()}?';
    }
    return 'map[$key] as ${type.toDartType()}';
  }

  String _packageToFileName(String packageName) {
    return '${_toSnakeCase(packageName)}.dart';
  }

  String _packageToClassName(String packageName) {
    return _toPascalCase(packageName);
  }

  String _packageToChannelName(String packageName) {
    return _toSnakeCase(packageName);
  }

  static String _toSnakeCase(String input) {
    return input
        .replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_')
        .replaceAll(RegExp(r'_+'), '_')
        .replaceAll(RegExp(r'^_|_$'), '')
        .toLowerCase();
  }

  static String _toPascalCase(String input) {
    return input
        .replaceAll(RegExp(r'[^a-zA-Z0-9]'), ' ')
        .split(RegExp(r'\s+'))
        .where((s) => s.isNotEmpty)
        .map((s) => s[0].toUpperCase() + s.substring(1).toLowerCase())
        .join();
  }
}
