import '../schema/unified_type_schema.dart';
import 'generator_base.dart';

/// Generates `dart:js_interop` bindings for web platform.
///
/// For npm packages on web, instead of platform channels, this generates
/// direct JS interop bindings using `@JS()` annotations and extension types.
class JsGlueGenerator extends GeneratorBase {
  @override
  Map<String, String> generate(UnifiedTypeSchema schema,
      {Map<String, String> customTypes = const {}}) {
    final fileName = '${_toSnakeCase(schema.package)}_web.dart';
    return {fileName: generateJsInteropCode(schema)};
  }

  /// Generates the full JS interop source code for the given schema.
  String generateJsInteropCode(UnifiedTypeSchema schema) {
    final buffer = StringBuffer();
    final jsNamespace = _toJsIdentifier(schema.package);

    // Header
    buffer.writeln('// GENERATED CODE — DO NOT EDIT');
    buffer.writeln('// Generated by auto_interop_generator');
    buffer.writeln('// Web JS interop bindings for ${schema.package}');
    buffer.writeln();

    // Imports
    buffer.writeln("import 'dart:js_interop';");
    buffer.writeln("import 'dart:js_interop_unsafe';");
    if (_needsTypedData(schema)) {
      buffer.writeln("import 'dart:typed_data';");
    }
    buffer.writeln();

    // JS interop extension types for interfaces/types
    for (final typeDef in schema.types) {
      _generateJsExtensionType(buffer, typeDef);
      buffer.writeln();
    }

    // JS interop extension types for classes
    for (final classDef in schema.classes) {
      _generateJsClassInterop(buffer, classDef);
      buffer.writeln();
    }

    // External JS function declarations
    if (schema.functions.isNotEmpty) {
      for (final fn in schema.functions) {
        _generateJsExternalFunction(buffer, fn, jsNamespace);
      }
      buffer.writeln();
    }

    // Dart enums
    for (final enumDef in schema.enums) {
      _generateEnum(buffer, enumDef);
      buffer.writeln();
    }

    // Dart data classes for types
    for (final typeDef in schema.types) {
      _generateDartDataClass(buffer, typeDef);
      buffer.writeln();
    }

    // Dart wrapper class for top-level functions
    if (schema.functions.isNotEmpty) {
      _generateDartFunctionWrapper(buffer, schema);
      buffer.writeln();
    }

    // Dart wrapper classes for classes
    for (final classDef in schema.classes) {
      _generateDartClassWrapper(buffer, schema, classDef);
      buffer.writeln();
    }

    return buffer.toString();
  }

  // --- JS Interop Layer ---

  void _generateJsExtensionType(StringBuffer buffer, UtsClass typeDef) {
    final jsName = '_Js${typeDef.name}';
    buffer.writeln('@JS()');
    buffer.writeln(
        'extension type $jsName._(JSObject _) implements JSObject {');
    for (final field in typeDef.fields) {
      final jsType = _toJsType(field.type);
      if (field.nullable) {
        buffer.writeln('  external $jsType? get ${field.name};');
      } else {
        buffer.writeln('  external $jsType get ${field.name};');
      }
    }
    buffer.writeln('}');
  }

  void _generateJsClassInterop(StringBuffer buffer, UtsClass classDef) {
    final jsName = '_Js${classDef.name}';
    buffer.writeln("@JS('${classDef.name}')");
    buffer.writeln(
        'extension type $jsName._(JSObject _) implements JSObject {');

    // Constructor
    final constructorParams = <String>[];
    for (final field in classDef.fields) {
      final jsType = _toJsType(field.type);
      constructorParams.add('$jsType ${field.name}');
    }
    if (constructorParams.isNotEmpty) {
      buffer.writeln(
          '  external factory $jsName(${constructorParams.join(', ')});');
    } else {
      buffer.writeln('  external factory $jsName();');
    }

    // Methods
    for (final method in classDef.methods) {
      final jsReturnType = _toJsReturnType(method);
      final params = method.parameters
          .map((p) => '${_toJsType(p.type)} ${p.name}')
          .join(', ');
      final staticMod = method.isStatic ? 'static ' : '';
      buffer.writeln('  external $staticMod$jsReturnType ${method.name}($params);');
    }

    buffer.writeln('}');
  }

  void _generateJsExternalFunction(
      StringBuffer buffer, UtsMethod fn, String jsNamespace) {
    final jsReturnType = _toJsReturnType(fn);
    final params = fn.parameters
        .map((p) {
          final jsType = _toJsType(p.type);
          if (p.isOptional || p.type.nullable) {
            return '$jsType? ${p.name}';
          }
          return '$jsType ${p.name}';
        })
        .join(', ');
    final jsFnName = '_js${_capitalize(fn.name)}';

    buffer.writeln("@JS('$jsNamespace.${fn.name}')");
    buffer.writeln('external $jsReturnType $jsFnName($params);');
  }

  // --- Dart API Layer ---

  void _generateEnum(StringBuffer buffer, UtsEnum enumDef) {
    if (enumDef.documentation != null) {
      buffer.writeln('/// ${enumDef.documentation}');
    }
    buffer.writeln('enum ${enumDef.name} {');
    for (var i = 0; i < enumDef.values.length; i++) {
      final value = enumDef.values[i];
      if (value.documentation != null) {
        buffer.writeln('  /// ${value.documentation}');
      }
      final comma = i < enumDef.values.length - 1 ? ',' : ';';
      buffer.writeln('  ${value.name}$comma');
    }
    buffer.writeln('}');
  }

  void _generateDartDataClass(StringBuffer buffer, UtsClass typeDef) {
    if (typeDef.documentation != null) {
      buffer.writeln('/// ${typeDef.documentation}');
    }
    buffer.writeln('class ${typeDef.name} {');

    // Fields
    for (final field in typeDef.fields) {
      final nullable = field.nullable ? '?' : '';
      buffer.writeln(
          '  final ${field.type.toDartType()}$nullable ${field.name};');
    }

    if (typeDef.fields.isNotEmpty) {
      buffer.writeln();
      // Constructor
      _generateConstructor(buffer, typeDef);
      buffer.writeln();
      // fromJs factory
      _generateFromJs(buffer, typeDef);
      buffer.writeln();
      // toJs method
      _generateToJs(buffer, typeDef);
    }

    buffer.writeln('}');
  }

  void _generateConstructor(StringBuffer buffer, UtsClass classDef) {
    buffer.write('  ${classDef.name}({');
    final params = <String>[];
    for (final field in classDef.fields) {
      if (field.nullable) {
        params.add('this.${field.name}');
      } else {
        params.add('required this.${field.name}');
      }
    }
    buffer.write(params.join(', '));
    buffer.writeln('});');
  }

  void _generateFromJs(StringBuffer buffer, UtsClass classDef) {
    final jsName = '_Js${classDef.name}';
    buffer.writeln(
        '  factory ${classDef.name}.fromJs($jsName js) {');
    buffer.writeln('    return ${classDef.name}(');
    for (final field in classDef.fields) {
      buffer.writeln(
          '      ${field.name}: ${_fromJsExpression(field)},');
    }
    buffer.writeln('    );');
    buffer.writeln('  }');
  }

  void _generateToJs(StringBuffer buffer, UtsClass classDef) {
    buffer.writeln('  JSObject toJs() {');
    buffer.writeln('    final obj = JSObject();');
    for (final field in classDef.fields) {
      final jsExpr = _toJsExpression(
          field.name, field.type, nullable: field.nullable);
      if (field.nullable) {
        buffer.writeln(
            "    if (${field.name} != null) obj['${field.name}'] = $jsExpr;");
      } else {
        buffer.writeln(
            "    obj['${field.name}'] = $jsExpr;");
      }
    }
    buffer.writeln('    return obj;');
    buffer.writeln('  }');
  }

  void _generateDartFunctionWrapper(
      StringBuffer buffer, UnifiedTypeSchema schema) {
    final className = _toPascalCase(schema.package);

    buffer.writeln('class $className {');

    for (final fn in schema.functions) {
      _generateDartMethod(buffer, fn, indent: '  ');
      buffer.writeln();
    }

    buffer.writeln('}');
  }

  void _generateDartClassWrapper(
      StringBuffer buffer, UnifiedTypeSchema schema, UtsClass classDef) {
    final jsName = '_Js${classDef.name}';

    if (classDef.documentation != null) {
      buffer.writeln('/// ${classDef.documentation}');
    }
    buffer.writeln('class ${classDef.name} {');
    buffer.writeln('  final $jsName _js;');
    buffer.writeln();

    // Constructor
    final constructorParams = <String>[];
    final constructorArgs = <String>[];
    for (final field in classDef.fields) {
      constructorParams.add('${field.type.toDartType()} ${field.name}');
      constructorArgs.add(_toJsExpression(field.name, field.type));
    }
    if (constructorParams.isNotEmpty) {
      buffer.writeln(
          '  ${classDef.name}(${constructorParams.join(', ')}) : _js = $jsName(${constructorArgs.join(', ')});');
    } else {
      buffer.writeln(
          '  ${classDef.name}() : _js = $jsName();');
    }
    buffer.writeln();

    // Methods
    for (final method in classDef.methods) {
      if (method.isStatic) {
        _generateDartClassStaticMethod(buffer, method, classDef, indent: '  ');
      } else {
        _generateDartClassMethod(buffer, method, indent: '  ');
      }
      buffer.writeln();
    }

    buffer.writeln('}');
  }

  void _generateDartMethod(StringBuffer buffer, UtsMethod method,
      {String indent = ''}) {
    if (method.documentation != null) {
      buffer.writeln('$indent/// ${method.documentation}');
    }

    final dartReturnType = _dartReturnType(method);
    final isAsync = method.isAsync ||
        method.returnType.kind == UtsTypeKind.future;
    final asyncMod = isAsync ? ' async' : '';

    // Parameter list
    final params = _buildDartParams(method.parameters);

    buffer.writeln(
        '${indent}static $dartReturnType ${method.name}($params)$asyncMod {');

    final jsFnName = '_js${_capitalize(method.name)}';
    final jsArgs = method.parameters
        .map((p) => _toJsExpression(p.name, p.type,
            nullable: p.isOptional || p.type.nullable))
        .join(', ');

    final innerType = _unwrapFutureType(method.returnType);

    if (isAsync) {
      if (innerType.kind == UtsTypeKind.voidType) {
        buffer.writeln('$indent  await $jsFnName($jsArgs).toDart;');
      } else {
        buffer.writeln(
            '$indent  final jsResult = await $jsFnName($jsArgs).toDart;');
        buffer.writeln(
            '$indent  return ${_fromJsValueExpression('jsResult', innerType)};');
      }
    } else {
      if (method.returnType.kind == UtsTypeKind.voidType) {
        buffer.writeln('$indent  $jsFnName($jsArgs);');
      } else {
        buffer.writeln(
            '$indent  final jsResult = $jsFnName($jsArgs);');
        buffer.writeln(
            '$indent  return ${_fromJsValueExpression('jsResult', method.returnType)};');
      }
    }

    buffer.writeln('$indent}');
  }

  void _generateDartClassStaticMethod(StringBuffer buffer, UtsMethod method,
      UtsClass classDef, {String indent = ''}) {
    if (method.documentation != null) {
      buffer.writeln('$indent/// ${method.documentation}');
    }

    final jsName = '_Js${classDef.name}';
    final dartReturnType = _dartReturnType(method);
    final isAsync = method.isAsync ||
        method.returnType.kind == UtsTypeKind.future;
    final asyncMod = isAsync ? ' async' : '';

    final params = _buildDartParams(method.parameters);

    buffer.writeln(
        '${indent}static $dartReturnType ${method.name}($params)$asyncMod {');

    final jsArgs = method.parameters
        .map((p) => _toJsExpression(p.name, p.type,
            nullable: p.isOptional || p.type.nullable))
        .join(', ');

    final innerType = _unwrapFutureType(method.returnType);

    if (isAsync) {
      if (innerType.kind == UtsTypeKind.voidType) {
        buffer.writeln(
            '$indent  await $jsName.${method.name}($jsArgs).toDart;');
      } else {
        buffer.writeln(
            '$indent  final jsResult = await $jsName.${method.name}($jsArgs).toDart;');
        buffer.writeln(
            '$indent  return ${_fromJsValueExpression('jsResult', innerType)};');
      }
    } else {
      if (method.returnType.kind == UtsTypeKind.voidType) {
        buffer.writeln('$indent  $jsName.${method.name}($jsArgs);');
      } else {
        buffer.writeln(
            '$indent  final jsResult = $jsName.${method.name}($jsArgs);');
        buffer.writeln(
            '$indent  return ${_fromJsValueExpression('jsResult', method.returnType)};');
      }
    }

    buffer.writeln('$indent}');
  }

  void _generateDartClassMethod(StringBuffer buffer, UtsMethod method,
      {String indent = ''}) {
    if (method.documentation != null) {
      buffer.writeln('$indent/// ${method.documentation}');
    }

    final dartReturnType = _dartReturnType(method);
    final isAsync = method.isAsync ||
        method.returnType.kind == UtsTypeKind.future;
    final asyncMod = isAsync ? ' async' : '';

    final params = _buildDartParams(method.parameters);

    buffer.writeln(
        '$indent$dartReturnType ${method.name}($params)$asyncMod {');

    final jsArgs = method.parameters
        .map((p) => _toJsExpression(p.name, p.type,
            nullable: p.isOptional || p.type.nullable))
        .join(', ');

    final innerType = _unwrapFutureType(method.returnType);

    if (isAsync) {
      if (innerType.kind == UtsTypeKind.voidType) {
        buffer.writeln(
            '$indent  await _js.${method.name}($jsArgs).toDart;');
      } else {
        buffer.writeln(
            '$indent  final jsResult = await _js.${method.name}($jsArgs).toDart;');
        buffer.writeln(
            '$indent  return ${_fromJsValueExpression('jsResult', innerType)};');
      }
    } else {
      if (method.returnType.kind == UtsTypeKind.voidType) {
        buffer.writeln('$indent  _js.${method.name}($jsArgs);');
      } else {
        buffer.writeln(
            '$indent  final jsResult = _js.${method.name}($jsArgs);');
        buffer.writeln(
            '$indent  return ${_fromJsValueExpression('jsResult', method.returnType)};');
      }
    }

    buffer.writeln('$indent}');
  }

  // --- Type Mapping Helpers ---

  /// Maps a UTS type to its JS interop type string.
  String _toJsType(UtsType type) {
    switch (type.kind) {
      case UtsTypeKind.primitive:
        switch (type.name) {
          case 'String':
            return 'JSString';
          case 'int':
          case 'double':
            return 'JSNumber';
          case 'bool':
            return 'JSBoolean';
          case 'DateTime':
            return 'JSString';
          case 'Duration':
            return 'JSNumber'; // microseconds
          case 'Uri':
            return 'JSString';
          case 'Uint8List':
            return 'JSUint8Array';
          default:
            return 'JSAny';
        }
      case UtsTypeKind.object:
        return 'JSObject';
      case UtsTypeKind.list:
        return 'JSArray';
      case UtsTypeKind.map:
        return 'JSObject';
      case UtsTypeKind.future:
        final inner = type.typeArguments?.first;
        if (inner != null) {
          return 'JSPromise<${_toJsType(inner)}>';
        }
        return 'JSPromise';
      case UtsTypeKind.stream:
        return 'JSObject';
      case UtsTypeKind.callback:
        return 'JSFunction';
      case UtsTypeKind.enumType:
        return 'JSString';
      case UtsTypeKind.voidType:
        return 'void';
      case UtsTypeKind.dynamic:
        return 'JSAny?';
      case UtsTypeKind.nativeObject:
        return 'JSObject';
    }
  }

  /// Maps a method's return type to JS interop type for external declarations.
  String _toJsReturnType(UtsMethod method) {
    final type = method.returnType;
    if (method.isAsync && type.kind != UtsTypeKind.future) {
      // Async method without explicit Future type — wrap in JSPromise
      return 'JSPromise<${_toJsType(type)}>';
    }
    return _toJsType(type);
  }

  /// Returns the Dart return type string for a method.
  String _dartReturnType(UtsMethod method) {
    final type = method.returnType;
    if (method.isAsync && type.kind != UtsTypeKind.future) {
      final dartType = type.toDartType();
      return dartType == 'void' ? 'Future<void>' : 'Future<$dartType>';
    }
    return type.toDartType();
  }

  /// Unwraps `Future<T>` to get T.
  UtsType _unwrapFutureType(UtsType type) {
    if (type.kind == UtsTypeKind.future) {
      return type.typeArguments?.first ?? UtsType.voidType();
    }
    return type;
  }

  /// Expression to convert a Dart value to its JS equivalent.
  String _toJsExpression(String name, UtsType type, {bool nullable = false}) {
    final nullSuffix = nullable ? '?' : '';
    switch (type.kind) {
      case UtsTypeKind.primitive:
        switch (type.name) {
          case 'String':
            return '$name$nullSuffix.toJS';
          case 'int':
          case 'double':
            return '$name$nullSuffix.toJS';
          case 'bool':
            return '$name$nullSuffix.toJS';
          case 'DateTime':
            return '$name$nullSuffix.toIso8601String().toJS';
          case 'Duration':
            return '$name$nullSuffix.inMicroseconds.toJS';
          case 'Uri':
            return '$name$nullSuffix.toString().toJS';
          case 'Uint8List':
            return '$name$nullSuffix.toJS';
          default:
            return '$name$nullSuffix.toJS';
        }
      case UtsTypeKind.object:
        return '$name$nullSuffix.toJs()';
      case UtsTypeKind.enumType:
        return '$name$nullSuffix.name.toJS';
      case UtsTypeKind.list:
        return '$name$nullSuffix.toJS';
      case UtsTypeKind.voidType:
        return name;
      default:
        return '$name$nullSuffix.toJS';
    }
  }

  /// Expression to convert a JS value to Dart type from a field.
  String _fromJsExpression(UtsField field) {
    final name = 'js.${field.name}';
    final type = field.type;

    if (field.nullable) {
      return _fromJsNullableExpression(name, type);
    }
    return _fromJsValueExpression(name, type);
  }

  /// Expression to convert a JS value to Dart.
  String _fromJsValueExpression(String expr, UtsType type) {
    switch (type.kind) {
      case UtsTypeKind.primitive:
        switch (type.name) {
          case 'String':
            return '$expr.toDart';
          case 'int':
            return '$expr.toDartInt';
          case 'double':
            return '$expr.toDartDouble';
          case 'bool':
            return '$expr.toDart';
          case 'DateTime':
            return 'DateTime.parse($expr.toDart)';
          case 'Duration':
            return 'Duration(microseconds: $expr.toDartInt)';
          case 'Uri':
            return 'Uri.parse($expr.toDart)';
          case 'Uint8List':
            return '$expr.toDart';
          default:
            return '$expr.toDart';
        }
      case UtsTypeKind.object:
        return '${type.name}.fromJs($expr as _Js${type.name})';
      case UtsTypeKind.enumType:
        return '${type.name}.values.byName($expr.toDart)';
      case UtsTypeKind.voidType:
        return expr;
      default:
        return '$expr.toDart';
    }
  }

  /// Expression for nullable JS → Dart conversion.
  String _fromJsNullableExpression(String expr, UtsType type) {
    switch (type.kind) {
      case UtsTypeKind.primitive:
        switch (type.name) {
          case 'String':
            return '$expr?.toDart';
          case 'int':
            return '$expr?.toDartInt';
          case 'double':
            return '$expr?.toDartDouble';
          case 'bool':
            return '$expr?.toDart';
          case 'DateTime':
            return '$expr != null ? DateTime.parse($expr!.toDart) : null';
          case 'Duration':
            return '$expr != null ? Duration(microseconds: $expr!.toDartInt) : null';
          case 'Uri':
            return '$expr != null ? Uri.parse($expr!.toDart) : null';
          default:
            return '$expr?.toDart';
        }
      case UtsTypeKind.object:
        return '$expr != null ? ${type.name}.fromJs($expr! as _Js${type.name}) : null';
      case UtsTypeKind.enumType:
        return '$expr != null ? ${type.name}.values.byName($expr!.toDart) : null';
      default:
        return '$expr?.toDart';
    }
  }

  // --- Dart parameter helpers ---

  String _buildDartParams(List<UtsParameter> params) {
    final positional = params.where((p) => !p.isNamed).toList();
    final named = params.where((p) => p.isNamed).toList();
    final parts = <String>[];

    for (final p in positional) {
      parts.add('${p.type.toDartType()} ${p.name}');
    }

    if (named.isNotEmpty) {
      final namedParts = <String>[];
      for (final p in named) {
        final dartType = p.type.toDartType();
        if (p.isOptional) {
          // dynamic is already nullable; don't append '?'
          final suffix = dartType == 'dynamic' ? '' : '?';
          namedParts.add('$dartType$suffix ${p.name}');
        } else {
          namedParts.add('required $dartType ${p.name}');
        }
      }
      parts.add('{${namedParts.join(', ')}}');
    }

    return parts.join(', ');
  }

  // --- Utility helpers ---

  bool _needsTypedData(UnifiedTypeSchema schema) {
    bool check(UtsType type) =>
        (type.kind == UtsTypeKind.primitive && type.name == 'Uint8List') ||
        (type.typeArguments?.any(check) ?? false);

    for (final fn in schema.functions) {
      if (check(fn.returnType)) return true;
      if (fn.parameters.any((p) => check(p.type))) return true;
    }
    for (final cls in schema.classes) {
      for (final m in cls.methods) {
        if (check(m.returnType)) return true;
        if (m.parameters.any((p) => check(p.type))) return true;
      }
      if (cls.fields.any((f) => check(f.type))) return true;
    }
    for (final t in schema.types) {
      if (t.fields.any((f) => check(f.type))) return true;
    }
    return false;
  }

  static String _toSnakeCase(String input) {
    return input
        .replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_')
        .replaceAll(RegExp(r'_+'), '_')
        .replaceAll(RegExp(r'^_|_$'), '')
        .toLowerCase();
  }

  static String _toPascalCase(String input) {
    return input
        .replaceAll(RegExp(r'[^a-zA-Z0-9]'), ' ')
        .split(RegExp(r'\s+'))
        .where((s) => s.isNotEmpty)
        .map((s) => s[0].toUpperCase() + s.substring(1).toLowerCase())
        .join();
  }

  /// Converts a package name to a valid JS identifier (camelCase).
  static String _toJsIdentifier(String packageName) {
    final parts = packageName
        .replaceAll(RegExp(r'[^a-zA-Z0-9]'), ' ')
        .split(RegExp(r'\s+'))
        .where((s) => s.isNotEmpty)
        .toList();
    if (parts.isEmpty) return packageName;
    return parts.first.toLowerCase() +
        parts
            .skip(1)
            .map((s) => s[0].toUpperCase() + s.substring(1).toLowerCase())
            .join();
  }

  static String _capitalize(String s) {
    if (s.isEmpty) return s;
    return s[0].toUpperCase() + s.substring(1);
  }
}
