import '../schema/unified_type_schema.dart';
import 'generator_base.dart';

/// Generates Kotlin platform channel handler code for Android.
///
/// Produces a Kotlin `FlutterPlugin` class that:
/// - Registers a `MethodChannel`
/// - Dispatches method calls via `when(call.method)`
/// - Extracts arguments and converts types
/// - Calls actual native library methods
/// - Returns results or errors
class KotlinGlueGenerator extends GeneratorBase {
  @override
  Map<String, String> generate(UnifiedTypeSchema schema,
      {Map<String, String> customTypes = const {}}) {
    final className = _toPascalCase(schema.package);
    final fileName = '${className}Plugin.kt';
    return {fileName: generateKotlinCode(schema)};
  }

  /// Generates the full Kotlin plugin source code.
  String generateKotlinCode(UnifiedTypeSchema schema) {
    final buffer = StringBuffer();
    final className = _toPascalCase(schema.package);
    final channelName = _toSnakeCase(schema.package);

    final hasStreams = _hasStreamMethods(schema);

    _writeHeader(buffer, schema);
    _writeImports(buffer, schema, hasStreams: hasStreams);
    buffer.writeln();
    _writePluginClass(buffer, schema, className, channelName,
        hasStreams: hasStreams);

    return buffer.toString();
  }

  bool _hasStreamMethods(UnifiedTypeSchema schema) {
    for (final fn in schema.functions) {
      if (fn.returnType.kind == UtsTypeKind.stream) return true;
    }
    for (final cls in schema.classes) {
      for (final m in cls.methods) {
        if (m.returnType.kind == UtsTypeKind.stream) return true;
      }
    }
    return false;
  }

  bool _hasInstanceMethods(UnifiedTypeSchema schema) {
    for (final cls in schema.classes) {
      for (final m in cls.methods) {
        if (!m.isStatic) return true;
      }
    }
    return false;
  }

  /// Returns true if any method lacks nativeBody and needs auto-generated native calls.
  bool _hasAutoGeneratedMethodCalls(UnifiedTypeSchema schema) {
    for (final fn in schema.functions) {
      if (fn.returnType.kind == UtsTypeKind.stream) {
        if (fn.nativeBody?['kotlin_onListen'] == null) return true;
      } else {
        if (fn.nativeBody?['kotlin'] == null) return true;
      }
    }
    for (final cls in schema.classes) {
      for (final m in cls.methods) {
        if (m.returnType.kind == UtsTypeKind.stream) {
          if (m.nativeBody?['kotlin_onListen'] == null) return true;
        } else {
          if (m.nativeBody?['kotlin'] == null) return true;
        }
      }
    }
    return false;
  }

  /// Checks if any method in the schema has callback parameters.
  bool _hasCallbackParameters(UnifiedTypeSchema schema) {
    for (final fn in schema.functions) {
      for (final p in fn.parameters) {
        if (p.type.kind == UtsTypeKind.callback) return true;
      }
    }
    for (final cls in schema.classes) {
      for (final m in cls.methods) {
        for (final p in m.parameters) {
          if (p.type.kind == UtsTypeKind.callback) return true;
        }
      }
    }
    return false;
  }

  bool _hasAsyncMethods(UnifiedTypeSchema schema) {
    for (final fn in schema.functions) {
      if (fn.returnType.kind == UtsTypeKind.future || fn.isAsync) return true;
    }
    for (final cls in schema.classes) {
      for (final m in cls.methods) {
        if (m.returnType.kind == UtsTypeKind.future || m.isAsync) return true;
      }
    }
    return false;
  }

  /// Returns true if any stream method lacks kotlin_onListen nativeBody.
  bool _hasAutoGeneratedStreams(UnifiedTypeSchema schema) {
    for (final fn in schema.functions) {
      if (fn.returnType.kind == UtsTypeKind.stream &&
          fn.nativeBody?['kotlin_onListen'] == null) {
        return true;
      }
    }
    for (final cls in schema.classes) {
      for (final m in cls.methods) {
        if (m.returnType.kind == UtsTypeKind.stream &&
            m.nativeBody?['kotlin_onListen'] == null) {
          return true;
        }
      }
    }
    return false;
  }

  void _writeHeader(StringBuffer buffer, UnifiedTypeSchema schema) {
    buffer.writeln('// GENERATED CODE — DO NOT EDIT');
    buffer.writeln('// Generated by auto_interop_generator');
    buffer.writeln('// Kotlin platform channel handler for ${schema.package}');
    buffer.writeln();
  }

  void _writeImports(StringBuffer buffer, UnifiedTypeSchema schema,
      {bool hasStreams = false}) {
    buffer.writeln('import io.flutter.embedding.engine.plugins.FlutterPlugin');
    buffer.writeln('import io.flutter.plugin.common.MethodCall');
    buffer.writeln('import io.flutter.plugin.common.MethodChannel');
    buffer.writeln(
        'import io.flutter.plugin.common.MethodChannel.MethodCallHandler');
    buffer.writeln('import io.flutter.plugin.common.MethodChannel.Result');
    if (hasStreams) {
      buffer.writeln('import io.flutter.plugin.common.EventChannel');
    }
    if (_hasAsyncMethods(schema) || _hasAutoGeneratedStreams(schema)) {
      buffer.writeln('import kotlinx.coroutines.*');
    }
    if (_hasAutoGeneratedStreams(schema)) {
      buffer.writeln('import kotlinx.coroutines.flow.*');
    }
    // Import the source library package (only when auto-generated calls exist)
    if (_hasAutoGeneratedMethodCalls(schema)) {
      final packageImport = _toKotlinPackageImport(schema.package);
      if (packageImport.isNotEmpty) {
        buffer.writeln('import $packageImport.*');
      }
    }
    // Emit additional platform-specific imports from nativeImports
    final kotlinImports = schema.nativeImports?['kotlin'];
    if (kotlinImports != null) {
      for (final imp in kotlinImports) {
        buffer.writeln('import $imp');
      }
    }
  }

  void _writePluginClass(StringBuffer buffer, UnifiedTypeSchema schema,
      String className, String channelName,
      {bool hasStreams = false}) {
    final hasCallbacks = _hasCallbackParameters(schema);
    final interfaces = hasStreams
        ? 'FlutterPlugin, MethodCallHandler, EventChannel.StreamHandler'
        : 'FlutterPlugin, MethodCallHandler';
    buffer.writeln('class ${className}Plugin : $interfaces {');
    buffer.writeln('    private lateinit var channel: MethodChannel');
    if (hasCallbacks) {
      buffer.writeln('    private lateinit var callbackChannel: MethodChannel');
    }
    if (hasStreams) {
      buffer.writeln('    private lateinit var eventChannel: EventChannel');
      buffer
          .writeln('    private var eventSink: EventChannel.EventSink? = null');
    }
    if (_hasInstanceMethods(schema)) {
      buffer.writeln('    private val instances = mutableMapOf<String, Any>()');
      buffer.writeln('    private var nextHandle = 0');
    }
    if (_hasAsyncMethods(schema) || _hasAutoGeneratedStreams(schema)) {
      buffer.writeln(
          '    private val scope = CoroutineScope(Dispatchers.Main + SupervisorJob())');
    }

    if (_hasAutoGeneratedStreams(schema)) {
      buffer.writeln('    private var streamJob: Job? = null');
    }

    // Emit additional platform-specific instance fields from nativeFields
    final kotlinFields = schema.nativeFields?['kotlin'];
    if (kotlinFields != null) {
      for (final field in kotlinFields) {
        buffer.writeln('    $field');
      }
    }
    buffer.writeln();

    // onAttachedToEngine
    buffer.writeln(
        '    override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding) {');
    buffer.writeln(
        '        channel = MethodChannel(binding.binaryMessenger, "auto_interop/$channelName")');
    buffer.writeln('        channel.setMethodCallHandler(this)');
    if (hasCallbacks) {
      buffer.writeln(
          '        callbackChannel = MethodChannel(binding.binaryMessenger, "auto_interop/callbacks")');
    }
    if (hasStreams) {
      buffer.writeln(
          '        eventChannel = EventChannel(binding.binaryMessenger, "auto_interop/$channelName/events")');
      buffer.writeln('        eventChannel.setStreamHandler(this)');
    }
    buffer.writeln('    }');
    buffer.writeln();

    // onDetachedFromEngine
    buffer.writeln(
        '    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {');
    buffer.writeln('        channel.setMethodCallHandler(null)');
    if (hasStreams) {
      buffer.writeln('        eventChannel.setStreamHandler(null)');
    }
    if (_hasAsyncMethods(schema) || _hasAutoGeneratedStreams(schema)) {
      buffer.writeln('        scope.cancel()');
    }
    buffer.writeln('    }');

    // EventChannel StreamHandler methods
    if (hasStreams) {
      final streamMethods = _collectStreamMethods(schema);
      _writeOnListen(buffer, schema, streamMethods);
      _writeOnCancel(buffer, streamMethods);
    }
    buffer.writeln();

    // Instance registry helpers
    if (_hasInstanceMethods(schema)) {
      _writeInstanceRegistryHelpers(buffer);
      buffer.writeln();
    }

    // Data class encode/decode helpers (skip types only used in nativeBody methods)
    final neededTypes = _typesNeededByAutoGeneratedMethods(schema);
    for (final typeDef in schema.types) {
      if (neededTypes.contains(typeDef.name)) {
        _writeDataClassHelpers(buffer, schema, typeDef);
      }
    }

    // Enum conversion helpers (skip enums only used in nativeBody methods)
    final neededEnums = _enumsNeededByAutoGeneratedMethods(schema);
    for (final enumDef in schema.enums) {
      if (neededEnums.contains(enumDef.name)) {
        _writeEnumHelper(buffer, enumDef);
      }
    }

    // onMethodCall
    buffer.writeln(
        '    override fun onMethodCall(call: MethodCall, result: Result) {');
    buffer.writeln('        when (call.method) {');

    // Top-level functions
    for (final fn in schema.functions) {
      _writeMethodCase(buffer, schema, fn, indent: '            ');
    }

    // Class methods (prefixed with className)
    for (final cls in schema.classes) {
      // Constructor factory for concrete classes with instance methods
      final hasInstanceMethods = cls.methods.any((m) => !m.isStatic);
      if (hasInstanceMethods &&
          cls.kind != UtsClassKind.abstractClass &&
          cls.constructorParameters != null) {
        _writeCreateCase(buffer, schema, cls, indent: '            ');
      }

      final dedupedMethods = _deduplicateMethods(cls.methods);
      for (final method in dedupedMethods) {
        // Skip spurious "create" method (init is handled via _writeCreateCase)
        if (cls.constructorParameters != null && method.name == 'create') {
          continue;
        }
        _writeMethodCase(buffer, schema, method,
            indent: '            ',
            prefix: '${cls.name}.',
            className: cls.nativeName ?? cls.name,
            isStatic: method.isStatic);
      }
    }

    // Dispose handler
    if (_hasInstanceMethods(schema)) {
      buffer.writeln('            "_dispose" -> {');
      buffer.writeln(
          '                val handle = call.argument<String>("_handle")!!');
      buffer.writeln('                releaseHandle(handle)');
      buffer.writeln('                result.success(null)');
      buffer.writeln('            }');
    }

    buffer.writeln('            else -> result.notImplemented()');
    buffer.writeln('        }');
    buffer.writeln('    }');

    // Emit normalizeErrorCode helper
    _writeNormalizeErrorCode(buffer);

    buffer.writeln('}');
  }

  void _writeNormalizeErrorCode(StringBuffer buffer) {
    buffer.writeln();
    buffer
        .writeln('    private fun normalizeErrorCode(e: Exception): String {');
    buffer.writeln('        return when (e) {');
    buffer.writeln('            is java.io.IOException -> "IO_ERROR"');
    buffer
        .writeln('            is java.net.SocketException -> "NETWORK_ERROR"');
    buffer
        .writeln('            is java.net.SocketTimeoutException -> "TIMEOUT"');
    buffer.writeln(
        '            is java.util.concurrent.TimeoutException -> "TIMEOUT"');
    buffer.writeln('            is SecurityException -> "PERMISSION_DENIED"');
    buffer.writeln(
        '            is IllegalArgumentException -> "INVALID_ARGUMENT"');
    buffer.writeln('            is IllegalStateException -> "INVALID_STATE"');
    buffer.writeln(
        '            is UnsupportedOperationException -> "UNSUPPORTED"');
    buffer.writeln('            is NullPointerException -> "NULL_REFERENCE"');
    buffer
        .writeln('            is IndexOutOfBoundsException -> "OUT_OF_RANGE"');
    buffer.writeln('            is ClassCastException -> "TYPE_ERROR"');
    buffer.writeln('            is NoSuchElementException -> "NOT_FOUND"');
    buffer.writeln(
        '            is ConcurrentModificationException -> "CONCURRENT_MODIFICATION"');
    buffer.writeln(
        '            is kotlinx.coroutines.CancellationException -> "CANCELLED"');
    buffer.writeln('            else -> e::class.simpleName ?: "UNKNOWN"');
    buffer.writeln('        }');
    buffer.writeln('    }');
  }

  void _writeInstanceRegistryHelpers(StringBuffer buffer) {
    buffer.writeln('    private fun createHandle(obj: Any): String {');
    buffer.writeln('        val handle = "h_\${nextHandle}"');
    buffer.writeln('        nextHandle++');
    buffer.writeln('        instances[handle] = obj');
    buffer.writeln('        return handle');
    buffer.writeln('    }');
    buffer.writeln();
    buffer.writeln('    private fun releaseHandle(handle: String) {');
    buffer.writeln('        instances.remove(handle)');
    buffer.writeln('    }');
  }

  void _writeDataClassHelpers(
      StringBuffer buffer, UnifiedTypeSchema schema, UtsClass typeDef) {
    final dartName = typeDef.name;
    final nativeName = typeDef.nativeName ?? typeDef.name;

    // decode helper
    buffer.writeln(
        '    private fun decode$dartName(map: Map<String, Any?>): $nativeName {');
    if (typeDef.fields.isEmpty) {
      buffer.writeln('        return $nativeName()');
    } else {
      buffer.writeln('        return $nativeName(');
      for (var i = 0; i < typeDef.fields.length; i++) {
        final field = typeDef.fields[i];
        final comma = i < typeDef.fields.length - 1 ? ',' : '';
        final decodeExpr = _kotlinDecodeFieldExpr(schema, field);
        buffer.writeln('            ${field.name} = $decodeExpr$comma');
      }
      buffer.writeln('        )');
    }
    buffer.writeln('    }');
    buffer.writeln();

    // encode helper
    final hasNullableFields = typeDef.fields.any((f) => f.nullable);
    if (hasNullableFields) {
      buffer.writeln(
          '    private fun encode(obj: $nativeName): Map<String, Any?> {');
      buffer.writeln('        val map = mutableMapOf<String, Any?>()');
      for (final field in typeDef.fields) {
        final encodeExpr = _kotlinEncodeFieldExpr(schema, field);
        if (field.nullable) {
          buffer.writeln(
              '        obj.${field.name}?.let { map["${field.name}"] = $encodeExpr }');
        } else {
          buffer.writeln('        map["${field.name}"] = $encodeExpr');
        }
      }
      buffer.writeln('        return map');
    } else {
      buffer.writeln(
          '    private fun encode(obj: $nativeName): Map<String, Any?> {');
      buffer.writeln('        return mapOf(');
      for (var i = 0; i < typeDef.fields.length; i++) {
        final field = typeDef.fields[i];
        final comma = i < typeDef.fields.length - 1 ? ',' : '';
        final encodeExpr = _kotlinEncodeFieldExpr(schema, field);
        buffer.writeln('            "${field.name}" to $encodeExpr$comma');
      }
      buffer.writeln('        )');
    }
    buffer.writeln('    }');
    buffer.writeln();
  }

  /// Returns the Kotlin expression to decode a field from a channel map.
  String _kotlinDecodeFieldExpr(UnifiedTypeSchema schema, UtsField field) {
    final key = '"${field.name}"';
    final type = field.type;

    // Nested data class: call decode helper
    if (type.kind == UtsTypeKind.object &&
        schema.types.any((t) => t.name == type.name)) {
      if (field.nullable) {
        return '(map[$key] as? Map<String, Any?>)?.let { decode${type.name}(it) }';
      }
      return 'decode${type.name}(map[$key] as Map<String, Any?>)';
    }

    // Enum field: call decode helper
    if (type.kind == UtsTypeKind.enumType) {
      if (field.nullable) {
        return '(map[$key] as? String)?.let { decode${type.name}(it) }';
      }
      return 'decode${type.name}(map[$key] as String)';
    }

    // Default: simple cast
    final kotlinType = _toNativeKotlinType(type);
    if (field.nullable) {
      return 'map[$key] as? $kotlinType';
    }
    return 'map[$key] as $kotlinType';
  }

  /// Returns the Kotlin expression to encode a field for the channel.
  String _kotlinEncodeFieldExpr(UnifiedTypeSchema schema, UtsField field) {
    final type = field.type;
    final accessor = field.nullable ? 'it' : 'obj.${field.name}';

    // Nested data class: call encode helper
    if (type.kind == UtsTypeKind.object &&
        schema.types.any((t) => t.name == type.name)) {
      return 'encode($accessor)';
    }

    // Enum field: convert to string name
    if (type.kind == UtsTypeKind.enumType) {
      return '$accessor.name';
    }

    return accessor;
  }

  void _writeEnumHelper(StringBuffer buffer, UtsEnum enumDef) {
    final dartName = enumDef.name;
    final nativeName = enumDef.nativeName ?? enumDef.name;
    buffer.writeln(
        '    private fun decode$dartName(value: String): $nativeName {');
    buffer.writeln('        return when (value) {');
    for (final v in enumDef.values) {
      buffer.writeln('            "${v.name}" -> $nativeName.${v.name}');
    }
    buffer.writeln(
        '            else -> throw IllegalArgumentException("Unknown $nativeName value: \$value")');
    buffer.writeln('        }');
    buffer.writeln('    }');
    buffer.writeln();
  }

  void _writeCreateCase(
      StringBuffer buffer, UnifiedTypeSchema schema, UtsClass cls,
      {String indent = ''}) {
    final nativeClassName = cls.nativeName ?? cls.name;
    buffer.writeln('$indent"${cls.name}._create" -> {');
    if (cls.constructorParameters != null &&
        cls.constructorParameters!.isNotEmpty) {
      // Extract arguments with proper type mapping
      for (final param in cls.constructorParameters!) {
        final kotlinType = _toKotlinType(param.type, schema: schema);
        if (param.isOptional || param.type.nullable) {
          buffer.writeln(
              '$indent    val ${param.name} = call.argument<$kotlinType>("${param.name}")');
        } else {
          buffer.writeln(
              '$indent    val ${param.name} = call.argument<$kotlinType>("${param.name}")!!');
        }
      }

      // Type conversion for special types
      for (final param in cls.constructorParameters!) {
        final conversion = _argumentConversion(param);
        if (conversion != null) {
          buffer.writeln('$indent    $conversion');
        }
      }

      // Build native arg list using the shared helper
      final nativeArgs =
          _buildNativeArgList(schema, cls.constructorParameters!);

      if (cls.constructorThrows) {
        buffer.writeln('$indent    try {');
        buffer.writeln(
            '$indent        val instance = $nativeClassName($nativeArgs)');
        buffer.writeln('$indent        val handle = createHandle(instance)');
        buffer.writeln('$indent        result.success(handle)');
        buffer.writeln('$indent    } catch (e: Exception) {');
        buffer.writeln(
            '$indent        result.error(normalizeErrorCode(e), e.message, e.stackTraceToString())');
        buffer.writeln('$indent    }');
      } else {
        buffer
            .writeln('$indent    val instance = $nativeClassName($nativeArgs)');
        buffer.writeln('$indent    val handle = createHandle(instance)');
        buffer.writeln('$indent    result.success(handle)');
      }
    } else {
      // No-arg constructor
      if (cls.constructorThrows) {
        buffer.writeln('$indent    try {');
        buffer.writeln('$indent        val instance = $nativeClassName()');
        buffer.writeln('$indent        val handle = createHandle(instance)');
        buffer.writeln('$indent        result.success(handle)');
        buffer.writeln('$indent    } catch (e: Exception) {');
        buffer.writeln(
            '$indent        result.error(normalizeErrorCode(e), e.message, e.stackTraceToString())');
        buffer.writeln('$indent    }');
      } else {
        buffer.writeln('$indent    val instance = $nativeClassName()');
        buffer.writeln('$indent    val handle = createHandle(instance)');
        buffer.writeln('$indent    result.success(handle)');
      }
    }
    buffer.writeln('$indent}');
  }

  void _writeMethodCase(
      StringBuffer buffer, UnifiedTypeSchema schema, UtsMethod method,
      {String indent = '',
      String prefix = '',
      String? className,
      bool isStatic = true}) {
    final methodName = '$prefix${method.name}';
    buffer.writeln('$indent"$methodName" -> {');

    // If nativeBody is provided for Kotlin, use it verbatim
    final kotlinBody = method.nativeBody?['kotlin'];
    if (kotlinBody != null) {
      for (final line in kotlinBody.split('\n')) {
        buffer.writeln('$indent    $line');
      }
      buffer.writeln('$indent}');
      return;
    }

    // Extract arguments
    for (final param in method.parameters) {
      final kotlinType = _toKotlinType(param.type, schema: schema);
      if (param.isOptional || param.type.nullable) {
        buffer.writeln(
            '$indent    val ${param.name} = call.argument<$kotlinType>("${param.name}")');
      } else {
        buffer.writeln(
            '$indent    val ${param.name} = call.argument<$kotlinType>("${param.name}")!!');
      }
    }

    // Type conversion for special types
    for (final param in method.parameters) {
      final conversion = _argumentConversion(param);
      if (conversion != null) {
        buffer.writeln('$indent    $conversion');
      }
    }

    // Build the native call expression
    final nativeArgs = _buildNativeArgList(schema, method.parameters);
    final nativeCall =
        _buildNativeCall(method, className, nativeArgs, isStatic: isStatic);

    // Call the method and return result
    final returnType = method.returnType;
    if (returnType.kind == UtsTypeKind.stream) {
      buffer.writeln('$indent    // Stream: events forwarded via eventSink');
      buffer.writeln('$indent    result.success(null)');
    } else if (returnType.kind == UtsTypeKind.voidType) {
      buffer.writeln('$indent    try {');
      if (!isStatic && className != null) {
        buffer.writeln(
            '$indent        val handle = call.argument<String>("_handle")!!');
        buffer.writeln(
            '$indent        val instance = instances[handle] as $className');
        buffer.writeln('$indent        instance.${method.name}($nativeArgs)');
      } else if (className != null) {
        buffer.writeln('$indent        $nativeCall');
      }
      buffer.writeln('$indent        result.success(null)');
      buffer.writeln('$indent    } catch (e: Exception) {');
      buffer.writeln(
          '$indent        result.error(normalizeErrorCode(e), e.message, e.stackTraceToString())');
      buffer.writeln('$indent    }');
    } else if (returnType.kind == UtsTypeKind.future) {
      final innerType = returnType.typeArguments?.first;
      if (!isStatic && className != null) {
        buffer.writeln(
            '$indent    val handle = call.argument<String>("_handle")!!');
        buffer.writeln(
            '$indent    val instance = instances[handle] as $className');
      }
      buffer.writeln('$indent    scope.launch {');
      buffer.writeln('$indent        try {');
      if (!isStatic && className != null) {
        if (innerType != null && innerType.kind != UtsTypeKind.voidType) {
          buffer.writeln(
              '$indent            val nativeResult = instance.${method.name}($nativeArgs)');
        } else {
          buffer.writeln(
              '$indent            instance.${method.name}($nativeArgs)');
        }
      } else {
        if (innerType != null && innerType.kind != UtsTypeKind.voidType) {
          buffer.writeln('$indent            val nativeResult = $nativeCall');
        } else {
          buffer.writeln('$indent            $nativeCall');
        }
      }
      final resultExpr =
          innerType != null && innerType.kind != UtsTypeKind.voidType
              ? _resultConversion(schema, innerType)
              : 'null';
      buffer.writeln('$indent            withContext(Dispatchers.Main) {');
      buffer.writeln('$indent                result.success($resultExpr)');
      buffer.writeln('$indent            }');
      buffer.writeln('$indent        } catch (e: Exception) {');
      buffer.writeln('$indent            withContext(Dispatchers.Main) {');
      buffer.writeln(
          '$indent                result.error(normalizeErrorCode(e), e.message, e.stackTraceToString())');
      buffer.writeln('$indent            }');
      buffer.writeln('$indent        }');
      buffer.writeln('$indent    }');
    } else {
      // Synchronous with return value
      buffer.writeln('$indent    try {');
      if (!isStatic && className != null) {
        buffer.writeln(
            '$indent        val handle = call.argument<String>("_handle")!!');
        buffer.writeln(
            '$indent        val instance = instances[handle] as $className');
        buffer.writeln(
            '$indent        val nativeResult = instance.${method.name}($nativeArgs)');
      } else {
        buffer.writeln('$indent        val nativeResult = $nativeCall');
      }
      final resultConversion = _resultConversion(schema, returnType);
      buffer.writeln('$indent        result.success($resultConversion)');
      buffer.writeln('$indent    } catch (e: Exception) {');
      buffer.writeln(
          '$indent        result.error(normalizeErrorCode(e), e.message, e.stackTraceToString())');
      buffer.writeln('$indent    }');
    }

    buffer.writeln('$indent}');
  }

  /// Builds the argument list for a native Kotlin call.
  ///
  /// Wraps object-type params with decode helpers and DateTime params with
  /// ISO 8601 conversion.
  String _buildNativeArgList(
      UnifiedTypeSchema schema, List<UtsParameter> params) {
    final parts = <String>[];
    for (final param in params) {
      String argName;
      if (param.type.kind == UtsTypeKind.primitive &&
          param.type.name == 'DateTime') {
        argName = '${param.name}Date';
      } else if (param.type.kind == UtsTypeKind.primitive &&
          param.type.name == 'Duration') {
        argName = '${param.name}Duration';
      } else if (param.type.kind == UtsTypeKind.primitive &&
          param.type.name == 'Uri') {
        argName = '${param.name}URI';
      } else if (param.type.kind == UtsTypeKind.object &&
          _isReferenceTypeClass(schema, param.type.name)) {
        // Reference type param: look up instance from handle
        argName = 'instances[${param.name}] as ${param.type.name}';
      } else if (param.type.kind == UtsTypeKind.object &&
          schema.types.any((t) => t.name == param.type.name)) {
        // Data class param: call decode helper to convert Map → native type
        argName = 'decode${param.type.name}(${param.name})';
      } else if (param.type.kind == UtsTypeKind.enumType) {
        argName = 'decode${param.type.name}(${param.name})';
      } else if (param.type.kind == UtsTypeKind.list) {
        final elementType = param.type.typeArguments?.first;
        if (elementType != null &&
            elementType.kind == UtsTypeKind.primitive &&
            _toNativeKotlinType(elementType) != 'Any') {
          argName = '${param.name}Typed';
        } else {
          argName = param.name;
        }
      } else {
        argName = param.name;
      }

      // Apply nativeType conversion wrapper
      if (param.nativeType != null) {
        if (param.isOptional || param.type.nullable) {
          argName = '$argName?.let { ${param.nativeType}(it) }';
        } else {
          argName = '${param.nativeType}($argName)';
        }
      }

      parts.add('${param.name} = $argName');
    }
    return parts.join(', ');
  }

  /// Builds the full native call expression.
  String _buildNativeCall(
      UtsMethod method, String? className, String nativeArgs,
      {bool isStatic = true}) {
    if (className != null && isStatic) {
      return '$className.${method.name}($nativeArgs)';
    } else if (className != null) {
      return 'instance.${method.name}($nativeArgs)';
    }
    return '${method.name}($nativeArgs)';
  }

  /// Maps UTS type to Kotlin type string for argument extraction.
  ///
  /// When [schema] is provided, reference-type objects (classes with instance
  /// methods) are extracted as `String` handles instead of `Map<String, Any?>`.
  String _toKotlinType(UtsType type, {UnifiedTypeSchema? schema}) {
    switch (type.kind) {
      case UtsTypeKind.primitive:
        switch (type.name) {
          case 'String':
            return 'String';
          case 'int':
            return 'Int';
          case 'double':
            return 'Double';
          case 'bool':
            return 'Boolean';
          case 'DateTime':
            return 'String'; // ISO 8601
          case 'Duration':
            return 'Long'; // microseconds
          case 'Uri':
            return 'String';
          case 'Uint8List':
            return 'ByteArray';
          default:
            return 'Any';
        }
      case UtsTypeKind.object:
        if (schema != null && _isReferenceTypeClass(schema, type.name)) {
          return 'String'; // handle
        }
        return 'Map<String, Any?>';
      case UtsTypeKind.list:
        return 'List<Any?>';
      case UtsTypeKind.map:
        return 'Map<String, Any?>';
      case UtsTypeKind.enumType:
        return 'String';
      case UtsTypeKind.callback:
        return 'String'; // callback ID
      case UtsTypeKind.nativeObject:
        return 'String'; // handle-based
      case UtsTypeKind.voidType:
        return 'Unit';
      case UtsTypeKind.dynamic:
        return 'Any?';
      default:
        return 'Any?';
    }
  }

  /// Maps UTS type to actual native Kotlin type.
  String _toNativeKotlinType(UtsType type) {
    // If a native name is preserved, map Swift sub-integer types to Kotlin equivalents
    if (type.nativeName != null && type.kind == UtsTypeKind.primitive) {
      switch (type.nativeName) {
        case 'UInt8':
          return 'UByte';
        case 'UInt16':
          return 'UShort';
        case 'UInt32':
          return 'UInt';
        case 'UInt64':
          return 'ULong';
        case 'Int8':
          return 'Byte';
        case 'Int16':
          return 'Short';
        case 'Int32':
          return 'Int';
        case 'Int64':
          return 'Long';
        case 'Float':
          return 'Float';
        case 'CGFloat':
          return 'Double';
      }
    }
    switch (type.kind) {
      case UtsTypeKind.primitive:
        switch (type.name) {
          case 'String':
            return 'String';
          case 'int':
            return 'Int';
          case 'double':
            return 'Double';
          case 'bool':
            return 'Boolean';
          case 'DateTime':
            return 'java.util.Date';
          case 'Duration':
            return 'kotlin.time.Duration';
          case 'Uri':
            return 'java.net.URI';
          case 'Uint8List':
            return 'ByteArray';
          default:
            return 'Any';
        }
      case UtsTypeKind.object:
        return type.nativeName ?? type.name;
      case UtsTypeKind.list:
        final elementType = type.typeArguments?.first;
        if (elementType != null) {
          return 'List<${_toNativeKotlinType(elementType)}>';
        }
        return 'List<Any>';
      case UtsTypeKind.map:
        final keyType = type.typeArguments?.first;
        final valueType =
            type.typeArguments != null && type.typeArguments!.length > 1
                ? type.typeArguments![1]
                : null;
        if (keyType != null && valueType != null) {
          return 'Map<${_toNativeKotlinType(keyType)}, ${_toNativeKotlinType(valueType)}>';
        }
        return 'Map<String, Any>';
      case UtsTypeKind.enumType:
        return type.nativeName ?? type.name;
      case UtsTypeKind.nativeObject:
        return type.nativeName ?? type.name;
      default:
        return 'Any';
    }
  }

  /// Returns additional conversion code for a parameter, or null if none needed.
  String? _argumentConversion(UtsParameter param) {
    if (param.type.kind == UtsTypeKind.primitive &&
        param.type.name == 'DateTime') {
      return 'val ${param.name}Date = java.text.SimpleDateFormat("yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'").parse(${param.name})';
    }
    if (param.type.kind == UtsTypeKind.primitive &&
        param.type.name == 'Duration') {
      // Convert microseconds Long to kotlin.time.Duration
      return 'val ${param.name}Duration = kotlin.time.Duration.Companion.microseconds(${param.name})';
    }
    if (param.type.kind == UtsTypeKind.primitive && param.type.name == 'Uri') {
      return 'val ${param.name}URI = java.net.URI.create(${param.name})';
    }
    if (param.type.kind == UtsTypeKind.list) {
      final elementType = param.type.typeArguments?.first;
      if (elementType != null && elementType.kind == UtsTypeKind.primitive) {
        final kotlinPrimitive = _toNativeKotlinType(elementType);
        if (kotlinPrimitive != 'Any') {
          final opt = param.isOptional || param.type.nullable ? '?' : '';
          return 'val ${param.name}Typed = (${param.name} as$opt List<*>)$opt.map { it as $kotlinPrimitive }';
        }
      }
    }
    return null;
  }

  /// Returns the Kotlin expression for converting a return value.
  String _resultConversion(UnifiedTypeSchema schema, UtsType type) {
    switch (type.kind) {
      case UtsTypeKind.primitive:
        if (type.name == 'DateTime') {
          return 'java.text.SimpleDateFormat("yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'").format(nativeResult)';
        }
        if (type.name == 'Duration') {
          return 'nativeResult.inWholeMicroseconds';
        }
        if (type.name == 'Uri') {
          return 'nativeResult.toString()';
        }
        return 'nativeResult';
      case UtsTypeKind.object:
        // Check if it's a reference type (class with instance methods)
        final cls = schema.classes.where((c) => c.name == type.name).toList();
        if (cls.isNotEmpty && cls.first.methods.any((m) => !m.isStatic)) {
          return 'createHandle(nativeResult)';
        }
        if (schema.types.any((t) => t.name == type.name)) {
          return 'encode(nativeResult)';
        }
        return 'nativeResult';
      case UtsTypeKind.nativeObject:
        return 'createHandle(nativeResult)';
      case UtsTypeKind.enumType:
        return 'nativeResult.name';
      case UtsTypeKind.list:
        return 'nativeResult';
      case UtsTypeKind.map:
        return 'nativeResult';
      case UtsTypeKind.voidType:
        return 'null';
      default:
        return 'nativeResult';
    }
  }

  /// Converts the package name to a Kotlin import path.
  String _toKotlinPackageImport(String packageName) {
    // For gradle packages like "com.squareup.okhttp3:okhttp",
    // use the group ID as the package import
    if (packageName.contains(':')) {
      return packageName.split(':').first;
    }
    // For simple package names like "com.google.gson"
    if (packageName.contains('.')) {
      return packageName;
    }
    return '';
  }

  /// Checks if a named type is a reference type class (has instance methods).
  bool _isReferenceTypeClass(UnifiedTypeSchema schema, String typeName) {
    final cls = schema.classes.where((c) => c.name == typeName).toList();
    return cls.isNotEmpty && cls.first.methods.any((m) => !m.isStatic);
  }

  /// Collects all stream methods with their channel method names.
  List<_KotlinStreamMethodInfo> _collectStreamMethods(
      UnifiedTypeSchema schema) {
    final methods = <_KotlinStreamMethodInfo>[];
    for (final fn in schema.functions) {
      if (fn.returnType.kind == UtsTypeKind.stream) {
        methods.add(_KotlinStreamMethodInfo(
          channelMethod: fn.name,
          onListenBody: fn.nativeBody?['kotlin_onListen'],
          onCancelBody: fn.nativeBody?['kotlin_onCancel'],
          method: fn,
          className: null,
          isStatic: true,
        ));
      }
    }
    for (final cls in schema.classes) {
      for (final m in cls.methods) {
        if (m.returnType.kind == UtsTypeKind.stream) {
          methods.add(_KotlinStreamMethodInfo(
            channelMethod: '${cls.name}.${m.name}',
            onListenBody: m.nativeBody?['kotlin_onListen'],
            onCancelBody: m.nativeBody?['kotlin_onCancel'],
            method: m,
            className: cls.name,
            isStatic: m.isStatic,
          ));
        }
      }
    }
    return methods;
  }

  void _writeOnListen(StringBuffer buffer, UnifiedTypeSchema schema,
      List<_KotlinStreamMethodInfo> streamMethods) {
    buffer.writeln();
    buffer.writeln(
        '    override fun onListen(arguments: Any?, events: EventChannel.EventSink?) {');
    buffer.writeln('        eventSink = events');
    // Parse arguments for nativeBody access
    buffer.writeln(
        '        val args = (arguments as? Map<String, Any>) ?: emptyMap()');
    if (streamMethods.length == 1) {
      final m = streamMethods.first;
      if (m.onListenBody != null) {
        for (final line in m.onListenBody!.split('\n')) {
          buffer.writeln('        $line');
        }
      } else {
        _writeAutoStreamBody(buffer, schema, m, '        ');
      }
    } else if (streamMethods.length > 1) {
      buffer.writeln('        val method = args["method"] as? String ?: ""');
      buffer.writeln('        when (method) {');
      for (final m in streamMethods) {
        buffer.writeln('            "${m.channelMethod}" -> {');
        if (m.onListenBody != null) {
          for (final line in m.onListenBody!.split('\n')) {
            buffer.writeln('                $line');
          }
        } else {
          _writeAutoStreamBody(buffer, schema, m, '                ');
        }
        buffer.writeln('            }');
      }
      buffer.writeln('        }');
    }
    buffer.writeln('    }');
  }

  void _writeOnCancel(
      StringBuffer buffer, List<_KotlinStreamMethodInfo> streamMethods) {
    buffer.writeln();
    buffer.writeln('    override fun onCancel(arguments: Any?) {');
    final hasCustomCancel = streamMethods.any((m) => m.onCancelBody != null);
    if (hasCustomCancel && streamMethods.length == 1) {
      final m = streamMethods.first;
      if (m.onCancelBody != null) {
        for (final line in m.onCancelBody!.split('\n')) {
          buffer.writeln('        $line');
        }
      }
    } else if (hasCustomCancel && streamMethods.length > 1) {
      buffer.writeln(
          '        val args = (arguments as? Map<String, Any>) ?: emptyMap()');
      buffer.writeln('        val method = args["method"] as? String ?: ""');
      buffer.writeln('        when (method) {');
      for (final m in streamMethods) {
        if (m.onCancelBody != null) {
          buffer.writeln('            "${m.channelMethod}" -> {');
          for (final line in m.onCancelBody!.split('\n')) {
            buffer.writeln('                $line');
          }
          buffer.writeln('            }');
        }
      }
      buffer.writeln('        }');
    }
    // Auto-cancel for streams without nativeBody
    final hasAutoStreams = streamMethods.any((m) => m.onListenBody == null);
    if (hasAutoStreams) {
      buffer.writeln('        streamJob?.cancel()');
      buffer.writeln('        streamJob = null');
    }
    buffer.writeln('        eventSink = null');
    buffer.writeln('    }');
  }

  /// Auto-generates an onListen body for a stream method without nativeBody.
  void _writeAutoStreamBody(StringBuffer buffer, UnifiedTypeSchema schema,
      _KotlinStreamMethodInfo info, String indent) {
    final method = info.method;

    // Extract arguments from args map
    for (final param in method.parameters) {
      final kotlinType = _toKotlinType(param.type, schema: schema);
      if (param.isOptional || param.type.nullable) {
        buffer.writeln(
            '${indent}val ${param.name} = args["${param.name}"] as? $kotlinType');
      } else {
        buffer.writeln(
            '${indent}val ${param.name} = args["${param.name}"] as $kotlinType');
      }
    }

    // Type conversions
    for (final param in method.parameters) {
      final conversion = _argumentConversion(param);
      if (conversion != null) {
        buffer.writeln('$indent$conversion');
      }
    }

    // Instance lookup if needed
    if (!info.isStatic && info.className != null) {
      buffer.writeln('${indent}val handle = args["_handle"] as String');
      buffer.writeln(
          '${indent}val instance = instances[handle] as ${info.className}');
    }

    // Build native call
    final nativeArgs = _buildNativeArgList(schema, method.parameters);
    final nativeCall = _buildNativeCall(method, info.className, nativeArgs,
        isStatic: info.isStatic);

    // Get result conversion for the stream element type
    final innerType = method.returnType.typeArguments?.first;
    final resultExpr =
        innerType != null && innerType.kind != UtsTypeKind.voidType
            ? _resultConversion(schema, innerType)
            : 'nativeResult';

    // Collect + forward events
    buffer.writeln('${indent}streamJob = scope.launch {');
    buffer.writeln('$indent    try {');
    buffer.writeln('$indent        $nativeCall.collect { nativeResult ->');
    buffer.writeln('$indent            withContext(Dispatchers.Main) {');
    buffer.writeln('$indent                eventSink?.success($resultExpr)');
    buffer.writeln('$indent            }');
    buffer.writeln('$indent        }');
    buffer.writeln('$indent    } catch (e: Exception) {');
    buffer.writeln('$indent        withContext(Dispatchers.Main) {');
    buffer.writeln(
        '$indent            eventSink?.error(normalizeErrorCode(e), e.message, e.stackTraceToString())');
    buffer.writeln('$indent        }');
    buffer.writeln('$indent    }');
    buffer.writeln('$indent}');
  }

  /// Collects type names that are referenced by auto-generated methods
  /// (methods without nativeBody). Types only used in nativeBody methods
  /// don't need encode/decode helpers.
  Set<String> _typesNeededByAutoGeneratedMethods(UnifiedTypeSchema schema) {
    final needed = <String>{};
    final typeNames = schema.types.map((t) => t.name).toSet();

    void collectFromType(UtsType type) {
      if (type.kind == UtsTypeKind.object && typeNames.contains(type.name)) {
        needed.add(type.name);
        final typeDef = schema.types.firstWhere((t) => t.name == type.name);
        for (final field in typeDef.fields) {
          collectFromType(field.type);
        }
      }
      type.typeArguments?.forEach(collectFromType);
    }

    void collectFromMethod(UtsMethod method) {
      if (method.nativeBody?['kotlin'] != null) return;
      if (method.returnType.kind == UtsTypeKind.stream &&
          method.nativeBody?['kotlin_onListen'] != null) {
        return;
      }
      collectFromType(method.returnType);
      for (final param in method.parameters) {
        collectFromType(param.type);
      }
    }

    for (final fn in schema.functions) {
      collectFromMethod(fn);
    }
    for (final cls in schema.classes) {
      for (final method in cls.methods) {
        collectFromMethod(method);
      }
      // Also collect from constructor parameters
      if (cls.constructorParameters != null) {
        for (final param in cls.constructorParameters!) {
          collectFromType(param.type);
        }
      }
    }
    return needed;
  }

  /// Collects enum names that are referenced by auto-generated methods
  /// (methods without nativeBody). Enums only used in nativeBody methods
  /// don't need decode helpers since the native code handles them directly.
  Set<String> _enumsNeededByAutoGeneratedMethods(UnifiedTypeSchema schema) {
    final needed = <String>{};
    final enumNames = schema.enums.map((e) => e.name).toSet();

    void collectFromType(UtsType type) {
      if (type.kind == UtsTypeKind.enumType && enumNames.contains(type.name)) {
        needed.add(type.name);
      }
      type.typeArguments?.forEach(collectFromType);
    }

    void collectFromMethod(UtsMethod method) {
      if (method.nativeBody?['kotlin'] != null) return;
      if (method.returnType.kind == UtsTypeKind.stream &&
          method.nativeBody?['kotlin_onListen'] != null) {
        return;
      }
      collectFromType(method.returnType);
      for (final param in method.parameters) {
        collectFromType(param.type);
      }
    }

    for (final fn in schema.functions) {
      collectFromMethod(fn);
    }
    for (final cls in schema.classes) {
      for (final method in cls.methods) {
        collectFromMethod(method);
      }
      // Also collect from constructor parameters
      if (cls.constructorParameters != null) {
        for (final param in cls.constructorParameters!) {
          collectFromType(param.type);
        }
      }
    }
    return needed;
  }

  // --- Naming helpers ---

  static String _toSnakeCase(String input) {
    return input
        .replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_')
        .replaceAll(RegExp(r'_+'), '_')
        .replaceAll(RegExp(r'^_|_$'), '')
        .toLowerCase();
  }

  static String _toPascalCase(String input) {
    return input
        .replaceAll(RegExp(r'[^a-zA-Z0-9]'), ' ')
        .split(RegExp(r'\s+'))
        .where((s) => s.isNotEmpty)
        .map((s) => s[0].toUpperCase() + s.substring(1).toLowerCase())
        .join();
  }

  /// Removes duplicate methods by name, preferring instance over static.
  static List<UtsMethod> _deduplicateMethods(List<UtsMethod> methods) {
    final byName = <String, UtsMethod>{};
    for (final m in methods) {
      final existing = byName[m.name];
      if (existing == null) {
        byName[m.name] = m;
      } else if (existing.isStatic && !m.isStatic) {
        byName[m.name] = m;
      }
    }
    final seen = <String>{};
    return methods
        .where((m) => seen.add(m.name))
        .map((m) => byName[m.name]!)
        .toList();
  }
}

/// Info about a stream method for onListen/onCancel dispatch.
class _KotlinStreamMethodInfo {
  final String channelMethod;
  final String? onListenBody;
  final String? onCancelBody;
  final UtsMethod method;
  final String? className;
  final bool isStatic;

  _KotlinStreamMethodInfo({
    required this.channelMethod,
    this.onListenBody,
    this.onCancelBody,
    required this.method,
    this.className,
    this.isStatic = true,
  });
}
