import '../schema/unified_type_schema.dart';
import 'generator_base.dart';

/// Generates Swift platform channel handler code for iOS/macOS.
///
/// Produces a Swift `FlutterPlugin` class that:
/// - Registers a `FlutterMethodChannel` via `register(with:)`
/// - Dispatches method calls via `switch call.method`
/// - Extracts arguments and converts types
/// - Calls actual native library methods
/// - Returns results or errors
class SwiftGlueGenerator extends GeneratorBase {
  @override
  Map<String, String> generate(UnifiedTypeSchema schema,
      {Map<String, String> customTypes = const {}}) {
    final className = _toPascalCase(schema.package);
    final fileName = '${className}Plugin.swift';
    return {fileName: generateSwiftCode(schema)};
  }

  /// Generates the full Swift plugin source code.
  String generateSwiftCode(UnifiedTypeSchema schema) {
    final buffer = StringBuffer();
    final className = _toPascalCase(schema.package);
    final channelName = _toSnakeCase(schema.package);
    final hasStreams = _hasStreamMethods(schema);

    _writeHeader(buffer, schema);
    _writeImports(buffer, schema);
    buffer.writeln();
    _writePluginClass(buffer, schema, className, channelName,
        hasStreams: hasStreams);

    return buffer.toString();
  }

  bool _hasStreamMethods(UnifiedTypeSchema schema) {
    for (final fn in schema.functions) {
      if (fn.returnType.kind == UtsTypeKind.stream) return true;
    }
    for (final cls in schema.classes) {
      for (final m in cls.methods) {
        if (m.returnType.kind == UtsTypeKind.stream) return true;
      }
    }
    return false;
  }

  /// Returns true if any stream method lacks swift_onListen nativeBody.
  bool _hasAutoGeneratedStreams(UnifiedTypeSchema schema) {
    for (final fn in schema.functions) {
      if (fn.returnType.kind == UtsTypeKind.stream &&
          fn.nativeBody?['swift_onListen'] == null) {
        return true;
      }
    }
    for (final cls in schema.classes) {
      for (final m in cls.methods) {
        if (m.returnType.kind == UtsTypeKind.stream &&
            m.nativeBody?['swift_onListen'] == null) {
          return true;
        }
      }
    }
    return false;
  }

  /// Checks if any method in the schema has callback parameters.
  bool _hasCallbackParameters(UnifiedTypeSchema schema) {
    for (final fn in schema.functions) {
      for (final p in fn.parameters) {
        if (p.type.kind == UtsTypeKind.callback) return true;
      }
    }
    for (final cls in schema.classes) {
      for (final m in cls.methods) {
        for (final p in m.parameters) {
          if (p.type.kind == UtsTypeKind.callback) return true;
        }
      }
    }
    return false;
  }

  /// Checks if any class has instance (non-static) methods.
  bool _hasInstanceMethods(UnifiedTypeSchema schema) {
    for (final cls in schema.classes) {
      for (final m in cls.methods) {
        if (!m.isStatic) return true;
      }
    }
    return false;
  }

  void _writeHeader(StringBuffer buffer, UnifiedTypeSchema schema) {
    buffer.writeln('// GENERATED CODE — DO NOT EDIT');
    buffer.writeln('// Generated by auto_interop_generator');
    buffer.writeln('// Swift platform channel handler for ${schema.package}');
    buffer.writeln();
  }

  void _writeImports(StringBuffer buffer, UnifiedTypeSchema schema) {
    buffer.writeln('#if os(macOS)');
    buffer.writeln('import FlutterMacOS');
    buffer.writeln('#else');
    buffer.writeln('import Flutter');
    buffer.writeln('import UIKit');
    buffer.writeln('#endif');
    // Only import the native framework if there are auto-generated method calls.
    // Pure nativeBody packages handle everything inline and don't need the import.
    if (_hasAutoGeneratedMethodCalls(schema)) {
      buffer.writeln('import ${schema.package}');
    }
    // Emit additional platform-specific imports from nativeImports
    final swiftImports = schema.nativeImports?['swift'];
    if (swiftImports != null) {
      for (final imp in swiftImports) {
        buffer.writeln('import $imp');
      }
    }
  }

  /// Returns true if any method lacks nativeBody and needs auto-generated native calls.
  bool _hasAutoGeneratedMethodCalls(UnifiedTypeSchema schema) {
    for (final fn in schema.functions) {
      if (fn.returnType.kind == UtsTypeKind.stream) {
        if (fn.nativeBody?['swift_onListen'] == null) return true;
      } else {
        if (fn.nativeBody?['swift'] == null) return true;
      }
    }
    for (final cls in schema.classes) {
      for (final m in cls.methods) {
        if (m.returnType.kind == UtsTypeKind.stream) {
          if (m.nativeBody?['swift_onListen'] == null) return true;
        } else {
          if (m.nativeBody?['swift'] == null) return true;
        }
      }
    }
    return false;
  }

  void _writePluginClass(StringBuffer buffer, UnifiedTypeSchema schema,
      String className, String channelName,
      {bool hasStreams = false}) {
    final hasCallbacks = _hasCallbackParameters(schema);
    final protocols = hasStreams
        ? 'NSObject, FlutterPlugin, FlutterStreamHandler'
        : 'NSObject, FlutterPlugin';
    buffer.writeln('public class ${className}Plugin: $protocols {');

    // Channel reference for callbacks
    buffer.writeln('    private var channel: FlutterMethodChannel!');

    // Callback channel for native→Dart callback invocations
    if (hasCallbacks) {
      buffer.writeln('    private var callbackChannel: FlutterMethodChannel!');
    }

    // Instance registry for NativeObject support
    if (_hasInstanceMethods(schema)) {
      buffer.writeln('    private var instances: [String: AnyObject] = [:]');
      buffer.writeln('    private var nextHandle: Int = 0');
    }

    if (hasStreams) {
      buffer.writeln('    private var eventSink: FlutterEventSink?');
    }

    if (_hasAutoGeneratedStreams(schema)) {
      buffer.writeln('    private var streamTask: Task<Void, Never>?');
    }

    // Emit additional platform-specific instance fields from nativeFields
    final swiftFields = schema.nativeFields?['swift'];
    if (swiftFields != null) {
      for (final field in swiftFields) {
        buffer.writeln('    $field');
      }
    }
    buffer.writeln();

    // register(with:)
    buffer.writeln(
        '    public static func register(with registrar: FlutterPluginRegistrar) {');
    // On macOS, messenger is a property; on iOS, it's a method.
    buffer.writeln('        #if os(macOS)');
    buffer.writeln('        let messenger = registrar.messenger');
    buffer.writeln('        #else');
    buffer.writeln('        let messenger = registrar.messenger()');
    buffer.writeln('        #endif');
    buffer.writeln(
        '        let channel = FlutterMethodChannel(name: "auto_interop/$channelName", binaryMessenger: messenger)');
    buffer.writeln('        let instance = ${className}Plugin()');
    buffer.writeln('        instance.channel = channel');
    buffer.writeln(
        '        registrar.addMethodCallDelegate(instance, channel: channel)');
    if (hasCallbacks) {
      buffer.writeln(
          '        instance.callbackChannel = FlutterMethodChannel(name: "auto_interop/callbacks", binaryMessenger: messenger)');
    }
    if (hasStreams) {
      buffer.writeln(
          '        let eventChannel = FlutterEventChannel(name: "auto_interop/$channelName/events", binaryMessenger: messenger)');
      buffer.writeln('        eventChannel.setStreamHandler(instance)');
    }
    buffer.writeln('    }');
    buffer.writeln();

    // Instance registry helpers
    if (_hasInstanceMethods(schema)) {
      _writeInstanceRegistryHelpers(buffer);
      buffer.writeln();
    }

    // Data class encode/decode helpers (skip types only used in nativeBody methods)
    final neededTypes = _typesNeededByAutoGeneratedMethods(schema);
    for (final typeDef in schema.types) {
      if (neededTypes.contains(typeDef.name)) {
        _writeDataClassHelpers(buffer, schema, typeDef);
      }
    }

    // Enum conversion helpers (skip enums only used in nativeBody methods)
    final neededEnums = _enumsNeededByAutoGeneratedMethods(schema);
    for (final enumDef in schema.enums) {
      if (neededEnums.contains(enumDef.name)) {
        _writeEnumHelper(buffer, enumDef);
      }
    }

    // handle(_:result:)
    buffer.writeln(
        '    public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {');

    // Collect all method cases
    final hasMethods = schema.functions.isNotEmpty ||
        schema.classes.any((c) => c.methods.isNotEmpty);

    if (hasMethods) {
      // Use default empty dict so _create (no arguments) still works
      buffer.writeln(
          '        let args = (call.arguments as? [String: Any]) ?? [:]');
      buffer.writeln();
      buffer.writeln('        switch call.method {');

      // Top-level functions
      for (final fn in schema.functions) {
        _writeMethodCase(buffer, schema, fn, indent: '        ');
      }

      // Class methods (prefixed with className)
      for (final cls in schema.classes) {
        // Constructor factory for concrete classes with instance methods
        final hasInstanceMethods = cls.methods.any((m) => !m.isStatic);
        if (hasInstanceMethods && cls.kind != UtsClassKind.abstractClass) {
          _writeCreateCase(buffer, cls, indent: '        ');
        }

        for (final method in cls.methods) {
          _writeMethodCase(buffer, schema, method,
              indent: '        ',
              prefix: '${cls.name}.',
              className: cls.name,
              isStatic: method.isStatic);
        }
      }

      // Dispose handler for instance registry
      if (_hasInstanceMethods(schema)) {
        buffer.writeln('        case "_dispose":');
        buffer.writeln('            let handle = args["_handle"] as! String');
        buffer.writeln('            releaseHandle(handle)');
        buffer.writeln('            result(nil)');
      }

      buffer.writeln('        default:');
      buffer.writeln('            result(FlutterMethodNotImplemented)');
      buffer.writeln('        }');
    } else {
      buffer.writeln('        result(FlutterMethodNotImplemented)');
    }

    buffer.writeln('    }');

    // FlutterStreamHandler methods
    if (hasStreams) {
      final streamMethods = _collectStreamMethods(schema);
      _writeOnListen(buffer, schema, streamMethods);
      _writeOnCancel(buffer, streamMethods);
    }

    // Emit normalizeErrorCode helper
    _writeNormalizeErrorCode(buffer);

    buffer.writeln('}');
  }

  void _writeNormalizeErrorCode(StringBuffer buffer) {
    buffer.writeln();
    buffer.writeln(
        '    private func normalizeErrorCode(_ error: Error) -> String {');
    buffer.writeln('        let nsError = error as NSError');
    buffer.writeln('        switch nsError.domain {');
    buffer.writeln('        case NSURLErrorDomain:');
    buffer.writeln('            switch nsError.code {');
    buffer.writeln('            case NSURLErrorTimedOut: return "TIMEOUT"');
    buffer.writeln('            case NSURLErrorCancelled: return "CANCELLED"');
    buffer.writeln(
        '            case NSURLErrorNotConnectedToInternet, NSURLErrorNetworkConnectionLost: return "NETWORK_ERROR"');
    buffer.writeln('            default: return "NETWORK_ERROR"');
    buffer.writeln('            }');
    buffer.writeln('        case NSCocoaErrorDomain:');
    buffer.writeln('            switch nsError.code {');
    buffer.writeln(
        '            case NSFileNoSuchFileError, NSFileReadNoSuchFileError: return "NOT_FOUND"');
    buffer.writeln(
        '            case NSFileWriteNoPermissionError, NSFileReadNoPermissionError: return "PERMISSION_DENIED"');
    buffer.writeln('            default: return "IO_ERROR"');
    buffer.writeln('            }');
    buffer.writeln('        default:');
    buffer.writeln(
        '            if error is DecodingError { return "TYPE_ERROR" }');
    buffer.writeln(
        '            if error is EncodingError { return "TYPE_ERROR" }');
    buffer.writeln('            return String(describing: type(of: error))');
    buffer.writeln('        }');
    buffer.writeln('    }');
  }

  /// Collects all stream methods with their channel method names.
  List<_StreamMethodInfo> _collectStreamMethods(UnifiedTypeSchema schema) {
    final methods = <_StreamMethodInfo>[];
    for (final fn in schema.functions) {
      if (fn.returnType.kind == UtsTypeKind.stream) {
        methods.add(_StreamMethodInfo(
          channelMethod: fn.name,
          onListenBody: fn.nativeBody?['swift_onListen'],
          onCancelBody: fn.nativeBody?['swift_onCancel'],
          method: fn,
          className: null,
          isStatic: true,
        ));
      }
    }
    for (final cls in schema.classes) {
      for (final m in cls.methods) {
        if (m.returnType.kind == UtsTypeKind.stream) {
          methods.add(_StreamMethodInfo(
            channelMethod: '${cls.name}.${m.name}',
            onListenBody: m.nativeBody?['swift_onListen'],
            onCancelBody: m.nativeBody?['swift_onCancel'],
            method: m,
            className: cls.name,
            isStatic: m.isStatic,
          ));
        }
      }
    }
    return methods;
  }

  void _writeOnListen(StringBuffer buffer, UnifiedTypeSchema schema,
      List<_StreamMethodInfo> streamMethods) {
    buffer.writeln();
    buffer.writeln(
        '    public func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink) -> FlutterError? {');
    buffer.writeln('        self.eventSink = events');
    // Parse arguments for nativeBody access
    buffer.writeln('        let args = (arguments as? [String: Any]) ?? [:]');
    if (streamMethods.length == 1) {
      // Single stream method — no dispatch needed
      final m = streamMethods.first;
      if (m.onListenBody != null) {
        for (final line in m.onListenBody!.split('\n')) {
          buffer.writeln('        $line');
        }
      } else {
        _writeAutoStreamBody(buffer, schema, m, '        ');
      }
    } else if (streamMethods.length > 1) {
      // Multiple stream methods — dispatch based on "method" key
      buffer.writeln('        let method = args["method"] as? String ?? ""');
      buffer.writeln('        switch method {');
      for (final m in streamMethods) {
        buffer.writeln('        case "${m.channelMethod}":');
        if (m.onListenBody != null) {
          for (final line in m.onListenBody!.split('\n')) {
            buffer.writeln('            $line');
          }
        } else {
          _writeAutoStreamBody(buffer, schema, m, '            ');
        }
      }
      buffer.writeln('        default:');
      buffer.writeln('            break');
      buffer.writeln('        }');
    }
    buffer.writeln('        return nil');
    buffer.writeln('    }');
  }

  void _writeOnCancel(
      StringBuffer buffer, List<_StreamMethodInfo> streamMethods) {
    buffer.writeln();
    buffer.writeln(
        '    public func onCancel(withArguments arguments: Any?) -> FlutterError? {');
    // Check if any stream methods have custom onCancel logic
    final hasCustomCancel = streamMethods.any((m) => m.onCancelBody != null);
    if (hasCustomCancel && streamMethods.length == 1) {
      final m = streamMethods.first;
      if (m.onCancelBody != null) {
        for (final line in m.onCancelBody!.split('\n')) {
          buffer.writeln('        $line');
        }
      }
    } else if (hasCustomCancel && streamMethods.length > 1) {
      buffer.writeln('        let args = (arguments as? [String: Any]) ?? [:]');
      buffer.writeln('        let method = args["method"] as? String ?? ""');
      buffer.writeln('        switch method {');
      for (final m in streamMethods) {
        if (m.onCancelBody != null) {
          buffer.writeln('        case "${m.channelMethod}":');
          for (final line in m.onCancelBody!.split('\n')) {
            buffer.writeln('            $line');
          }
        }
      }
      buffer.writeln('        default:');
      buffer.writeln('            break');
      buffer.writeln('        }');
    }
    // Auto-cancel for streams without nativeBody
    final hasAutoStreams = streamMethods.any((m) => m.onListenBody == null);
    if (hasAutoStreams) {
      buffer.writeln('        streamTask?.cancel()');
      buffer.writeln('        streamTask = nil');
    }
    buffer.writeln('        self.eventSink = nil');
    buffer.writeln('        return nil');
    buffer.writeln('    }');
  }

  /// Auto-generates an onListen body for a stream method without nativeBody.
  void _writeAutoStreamBody(StringBuffer buffer, UnifiedTypeSchema schema,
      _StreamMethodInfo info, String indent) {
    final method = info.method;

    // Extract arguments
    for (final param in method.parameters) {
      final swiftType = _toSwiftType(param.type, schema: schema);
      if (param.isOptional || param.type.nullable) {
        buffer.writeln(
            '${indent}let ${param.name} = args["${param.name}"] as? $swiftType');
      } else {
        buffer.writeln(
            '${indent}let ${param.name} = args["${param.name}"] as! $swiftType');
      }
    }

    // Type conversions
    for (final param in method.parameters) {
      final conversion = _argumentConversion(param);
      if (conversion != null) {
        buffer.writeln('$indent$conversion');
      }
    }

    // Instance lookup if needed
    if (!info.isStatic && info.className != null) {
      buffer.writeln('${indent}let handle = args["_handle"] as! String');
      buffer.writeln(
          '${indent}let instance = instances[handle] as! ${info.className}');
    }

    // Build native call
    final nativeArgs = _buildNativeArgList(schema, method.parameters);
    final nativeCall = _buildNativeCall(method, info.className, nativeArgs,
        isStatic: info.isStatic);

    // Get result conversion for the stream element type
    final innerType = method.returnType.typeArguments?.first;
    final resultExpr =
        innerType != null && innerType.kind != UtsTypeKind.voidType
            ? _resultConversion(schema, innerType)
            : 'nativeResult';

    // Iterate + forward events
    buffer.writeln('${indent}streamTask = Task {');
    buffer.writeln('$indent    do {');
    buffer
        .writeln('$indent        for try await nativeResult in $nativeCall {');
    buffer.writeln('$indent            guard !Task.isCancelled else { break }');
    buffer.writeln('$indent            DispatchQueue.main.async {');
    buffer.writeln('$indent                self.eventSink?($resultExpr)');
    buffer.writeln('$indent            }');
    buffer.writeln('$indent        }');
    buffer.writeln('$indent    } catch {');
    buffer.writeln('$indent        if !Task.isCancelled {');
    buffer.writeln('$indent            DispatchQueue.main.async {');
    buffer.writeln(
        '$indent                self.eventSink?(FlutterError(code: self.normalizeErrorCode(error), message: error.localizedDescription, details: nil))');
    buffer.writeln('$indent            }');
    buffer.writeln('$indent        }');
    buffer.writeln('$indent    }');
    buffer.writeln('$indent}');
  }

  void _writeInstanceRegistryHelpers(StringBuffer buffer) {
    buffer
        .writeln('    private func createHandle(_ obj: AnyObject) -> String {');
    buffer.writeln('        let handle = "h_\\(nextHandle)"');
    buffer.writeln('        nextHandle += 1');
    buffer.writeln('        instances[handle] = obj');
    buffer.writeln('        return handle');
    buffer.writeln('    }');
    buffer.writeln();
    buffer.writeln('    private func releaseHandle(_ handle: String) {');
    buffer.writeln('        instances.removeValue(forKey: handle)');
    buffer.writeln('    }');
  }

  void _writeDataClassHelpers(
      StringBuffer buffer, UnifiedTypeSchema schema, UtsClass typeDef) {
    final name = typeDef.name;

    // decode helper
    buffer.writeln(
        '    private func decode$name(from map: [String: Any]) -> $name {');
    if (typeDef.fields.isEmpty) {
      buffer.writeln('        return $name()');
    } else {
      buffer.writeln('        return $name(');
      for (var i = 0; i < typeDef.fields.length; i++) {
        final field = typeDef.fields[i];
        final comma = i < typeDef.fields.length - 1 ? ',' : '';
        final decodeExpr = _swiftDecodeFieldExpr(schema, field);
        buffer.writeln('            ${field.name}: $decodeExpr$comma');
      }
      buffer.writeln('        )');
    }
    buffer.writeln('    }');
    buffer.writeln();

    // encode helper
    final hasNullableFields = typeDef.fields.any((f) => f.nullable);
    buffer.writeln('    private func encode(_ obj: $name) -> [String: Any] {');
    if (hasNullableFields) {
      // Use mutable dict so nullable fields can be conditionally added
      buffer.writeln('        var dict: [String: Any] = [:]');
      for (final field in typeDef.fields) {
        final encodeExpr = _swiftEncodeFieldExpr(schema, field);
        if (field.nullable) {
          buffer.writeln(
              '        if let val = obj.${field.name} { dict["${field.name}"] = $encodeExpr }');
        } else {
          buffer.writeln('        dict["${field.name}"] = $encodeExpr');
        }
      }
      buffer.writeln('        return dict');
    } else {
      buffer.writeln('        return [');
      for (var i = 0; i < typeDef.fields.length; i++) {
        final field = typeDef.fields[i];
        final comma = i < typeDef.fields.length - 1 ? ',' : '';
        final encodeExpr = _swiftEncodeFieldExpr(schema, field);
        buffer.writeln('            "${field.name}": $encodeExpr$comma');
      }
      buffer.writeln('        ]');
    }
    buffer.writeln('    }');
    buffer.writeln();
  }

  /// Returns the Swift expression to decode a field from a channel map.
  String _swiftDecodeFieldExpr(UnifiedTypeSchema schema, UtsField field) {
    final key = '"${field.name}"';
    final type = field.type;

    // Nested data class: call decode helper
    if (type.kind == UtsTypeKind.object &&
        schema.types.any((t) => t.name == type.name)) {
      if (field.nullable) {
        return 'map[$key] != null ? decode${type.name}(from: map[$key] as! [String: Any]) : nil';
      }
      return 'decode${type.name}(from: map[$key] as! [String: Any])';
    }

    // Enum field: call decode helper
    if (type.kind == UtsTypeKind.enumType) {
      if (field.nullable) {
        return 'map[$key] != null ? decode${type.name}(map[$key] as! String) : nil';
      }
      return 'decode${type.name}(map[$key] as! String)';
    }

    // Default: simple cast
    final swiftType = _toNativeSwiftType(type);
    if (field.nullable) {
      return 'map[$key] as? $swiftType';
    }
    return 'map[$key] as! $swiftType';
  }

  /// Returns the Swift expression to encode a field for the channel.
  String _swiftEncodeFieldExpr(UnifiedTypeSchema schema, UtsField field) {
    final type = field.type;
    final accessor = field.nullable ? 'val' : 'obj.${field.name}';

    // Nested data class: call encode helper
    if (type.kind == UtsTypeKind.object &&
        schema.types.any((t) => t.name == type.name)) {
      return 'encode($accessor)';
    }

    // Enum field: convert to string
    if (type.kind == UtsTypeKind.enumType) {
      return 'String(describing: $accessor)';
    }

    return accessor;
  }

  void _writeEnumHelper(StringBuffer buffer, UtsEnum enumDef) {
    final name = enumDef.name;
    buffer.writeln('    private func decode$name(_ value: String) -> $name {');
    buffer.writeln('        switch value {');
    for (final v in enumDef.values) {
      buffer.writeln('        case "${v.name}": return .${v.name}');
    }
    buffer.writeln(
        '        default: fatalError("Unknown $name value: \\(value)")');
    buffer.writeln('        }');
    buffer.writeln('    }');
    buffer.writeln();
  }

  void _writeCreateCase(StringBuffer buffer, UtsClass cls,
      {String indent = ''}) {
    buffer.writeln('${indent}case "${cls.name}._create":');
    if (cls.constructorParameters.isNotEmpty) {
      // Named-parameter construction
      for (final param in cls.constructorParameters) {
        final swiftType = _toSwiftType(param.type);
        if (param.isOptional || param.type.nullable) {
          buffer.writeln(
              '$indent    let ${param.name} = args["${param.name}"] as? $swiftType');
        } else {
          buffer.writeln(
              '$indent    let ${param.name} = args["${param.name}"] as! $swiftType');
        }
      }
      final argParts = cls.constructorParameters
          .map((p) => '${p.name}: ${p.name}')
          .join(', ');
      buffer.writeln('$indent    let instance = ${cls.name}($argParts)');
    } else {
      buffer.writeln('$indent    let instance = ${cls.name}()');
    }
    buffer.writeln('$indent    let handle = createHandle(instance)');
    buffer.writeln('$indent    result(handle)');
  }

  void _writeMethodCase(
      StringBuffer buffer, UnifiedTypeSchema schema, UtsMethod method,
      {String indent = '',
      String prefix = '',
      String? className,
      bool isStatic = true}) {
    final methodName = '$prefix${method.name}';
    buffer.writeln('${indent}case "$methodName":');

    // If nativeBody is provided for Swift, use it verbatim
    final swiftBody = method.nativeBody?['swift'];
    if (swiftBody != null) {
      for (final line in swiftBody.split('\n')) {
        buffer.writeln('$indent    $line');
      }
      return;
    }

    // Extract arguments
    for (final param in method.parameters) {
      final swiftType = _toSwiftType(param.type, schema: schema);
      if (param.isOptional || param.type.nullable) {
        buffer.writeln(
            '$indent    let ${param.name} = args["${param.name}"] as? $swiftType');
      } else {
        buffer.writeln(
            '$indent    let ${param.name} = args["${param.name}"] as! $swiftType');
      }
    }

    // Type conversion for special types
    for (final param in method.parameters) {
      final conversion = _argumentConversion(param);
      if (conversion != null) {
        buffer.writeln('$indent    $conversion');
      }
    }

    // Build the native call expression
    final nativeArgs = _buildNativeArgList(schema, method.parameters);
    final nativeCall =
        _buildNativeCall(method, className, nativeArgs, isStatic: isStatic);

    // Call the method and return result
    final returnType = method.returnType;
    if (returnType.kind == UtsTypeKind.stream) {
      buffer.writeln('$indent    // Stream: events forwarded via eventSink');
      buffer.writeln('$indent    result(nil)');
    } else if (returnType.kind == UtsTypeKind.voidType) {
      if (!isStatic && className != null) {
        buffer.writeln('$indent    let handle = args["_handle"] as! String');
        buffer.writeln(
            '$indent    let instance = instances[handle] as! $className');
        buffer.writeln('$indent    instance.${method.name}($nativeArgs)');
      } else if (className != null) {
        buffer.writeln('$indent    $nativeCall');
      }
      buffer.writeln('$indent    result(nil)');
    } else if (returnType.kind == UtsTypeKind.future) {
      final innerType = returnType.typeArguments?.first;
      if (!isStatic && className != null) {
        buffer.writeln('$indent    let handle = args["_handle"] as! String');
        buffer.writeln(
            '$indent    let instance = instances[handle] as! $className');
      }
      buffer.writeln('$indent    Task {');
      buffer.writeln('$indent        do {');
      if (!isStatic && className != null) {
        if (innerType != null && innerType.kind != UtsTypeKind.voidType) {
          buffer.writeln(
              '$indent            let nativeResult = try await instance.${method.name}($nativeArgs)');
        } else {
          buffer.writeln(
              '$indent            try await instance.${method.name}($nativeArgs)');
        }
      } else {
        if (innerType != null && innerType.kind != UtsTypeKind.voidType) {
          buffer.writeln(
              '$indent            let nativeResult = try await $nativeCall');
        } else {
          buffer.writeln('$indent            try await $nativeCall');
        }
      }
      final resultExpr =
          innerType != null && innerType.kind != UtsTypeKind.voidType
              ? _resultConversion(schema, innerType)
              : 'nil';
      buffer.writeln('$indent            DispatchQueue.main.async {');
      buffer.writeln('$indent                result($resultExpr)');
      buffer.writeln('$indent            }');
      buffer.writeln('$indent        } catch {');
      buffer.writeln('$indent            DispatchQueue.main.async {');
      buffer.writeln(
          '$indent                result(FlutterError(code: normalizeErrorCode(error), message: error.localizedDescription, details: String(describing: error)))');
      buffer.writeln('$indent            }');
      buffer.writeln('$indent        }');
      buffer.writeln('$indent    }');
    } else {
      // Synchronous with return value
      if (!isStatic && className != null) {
        buffer.writeln('$indent    let handle = args["_handle"] as! String');
        buffer.writeln(
            '$indent    let instance = instances[handle] as! $className');
        buffer.writeln(
            '$indent    let nativeResult = instance.${method.name}($nativeArgs)');
      } else {
        buffer.writeln('$indent    let nativeResult = $nativeCall');
      }
      final resultConversion = _resultConversion(schema, returnType);
      buffer.writeln('$indent    result($resultConversion)');
    }
  }

  /// Builds the argument list for a native Swift call.
  ///
  /// Wraps object-type params with decode helpers and DateTime params with
  /// ISO 8601 conversion.
  String _buildNativeArgList(
      UnifiedTypeSchema schema, List<UtsParameter> params) {
    final parts = <String>[];
    for (final param in params) {
      String argName;
      if (param.type.kind == UtsTypeKind.primitive &&
          param.type.name == 'DateTime') {
        argName = '${param.name}Date';
      } else if (param.type.kind == UtsTypeKind.primitive &&
          param.type.name == 'Duration') {
        argName = '${param.name}Interval';
      } else if (param.type.kind == UtsTypeKind.primitive &&
          param.type.name == 'Uri') {
        argName = '${param.name}URL';
      } else if (param.type.kind == UtsTypeKind.primitive &&
          param.type.name == 'Uint8List') {
        argName = '${param.name}Data';
      } else if (param.type.kind == UtsTypeKind.object &&
          _isReferenceTypeClass(schema, param.type.name)) {
        // Reference type param: look up instance from handle
        argName = 'instances[${param.name}] as! ${param.type.name}';
      } else if (param.type.kind == UtsTypeKind.object &&
          schema.types.any((t) => t.name == param.type.name)) {
        // Data class param: call decode helper to convert Map → native type
        argName = 'decode${param.type.name}(from: ${param.name})';
      } else if (param.type.kind == UtsTypeKind.enumType) {
        argName = 'decode${param.type.name}(${param.name})';
      } else {
        argName = param.name;
      }

      // Apply nativeType conversion wrapper
      if (param.nativeType != null) {
        if (param.isOptional || param.type.nullable) {
          argName = '$argName != nil ? ${param.nativeType}($argName!) : nil';
        } else {
          argName = '${param.nativeType}($argName)';
        }
      }

      // Apply nativeLabel for Swift parameter labels
      if (param.nativeLabel == '_') {
        parts.add(argName);
      } else {
        final label = param.nativeLabel ?? param.name;
        parts.add('$label: $argName');
      }
    }
    return parts.join(', ');
  }

  /// Builds the full native call expression.
  String _buildNativeCall(
      UtsMethod method, String? className, String nativeArgs,
      {bool isStatic = true}) {
    if (className != null && isStatic) {
      return '$className.${method.name}($nativeArgs)';
    } else if (className != null) {
      return 'instance.${method.name}($nativeArgs)';
    }
    return '${method.name}($nativeArgs)';
  }

  /// Maps UTS type to Swift type string for argument extraction from channel.
  ///
  /// When [schema] is provided, reference-type objects (classes with instance
  /// methods) are extracted as `String` handles instead of `[String: Any]`.
  String _toSwiftType(UtsType type, {UnifiedTypeSchema? schema}) {
    switch (type.kind) {
      case UtsTypeKind.primitive:
        switch (type.name) {
          case 'String':
            return 'String';
          case 'int':
            return 'Int';
          case 'double':
            return 'Double';
          case 'bool':
            return 'Bool';
          case 'DateTime':
            return 'String'; // ISO 8601
          case 'Duration':
            return 'Int'; // microseconds
          case 'Uri':
            return 'String';
          case 'Uint8List':
            return 'FlutterStandardTypedData';
          default:
            return 'Any';
        }
      case UtsTypeKind.object:
        if (schema != null && _isReferenceTypeClass(schema, type.name)) {
          return 'String'; // handle
        }
        return '[String: Any]';
      case UtsTypeKind.list:
        return '[Any]';
      case UtsTypeKind.map:
        if (type.typeArguments != null && type.typeArguments!.length == 2) {
          final valueType =
              _toSwiftType(type.typeArguments![1], schema: schema);
          if (valueType != 'Any') {
            return '[String: $valueType]';
          }
        }
        return '[String: Any]';
      case UtsTypeKind.enumType:
        return 'String';
      case UtsTypeKind.callback:
        return 'String'; // callback ID
      case UtsTypeKind.voidType:
        return 'Void';
      case UtsTypeKind.dynamic:
        return 'Any';
      default:
        return 'Any';
    }
  }

  /// Maps UTS type to actual native Swift type.
  String _toNativeSwiftType(UtsType type) {
    switch (type.kind) {
      case UtsTypeKind.primitive:
        switch (type.name) {
          case 'String':
            return 'String';
          case 'int':
            return 'Int';
          case 'double':
            return 'Double';
          case 'bool':
            return 'Bool';
          case 'DateTime':
            return 'Date';
          case 'Duration':
            return 'TimeInterval';
          case 'Uri':
            return 'URL';
          case 'Uint8List':
            return 'Data';
          default:
            return 'Any';
        }
      case UtsTypeKind.object:
        return type.name;
      case UtsTypeKind.list:
        final elementType = type.typeArguments?.first;
        if (elementType != null) {
          return '[${_toNativeSwiftType(elementType)}]';
        }
        return '[Any]';
      case UtsTypeKind.map:
        final keyType = type.typeArguments?.first;
        final valueType =
            type.typeArguments != null && type.typeArguments!.length > 1
                ? type.typeArguments![1]
                : null;
        if (keyType != null && valueType != null) {
          return '[${_toNativeSwiftType(keyType)}: ${_toNativeSwiftType(valueType)}]';
        }
        return '[String: Any]';
      case UtsTypeKind.enumType:
        return type.name;
      case UtsTypeKind.nativeObject:
        return type.name;
      default:
        return 'Any';
    }
  }

  /// Returns additional conversion code for a parameter, or null if none needed.
  String? _argumentConversion(UtsParameter param) {
    if (param.type.kind == UtsTypeKind.primitive &&
        param.type.name == 'DateTime') {
      final opt = param.isOptional || param.type.nullable ? '?' : '!';
      return 'let ${param.name}Date = ISO8601DateFormatter().date(from: ${param.name}$opt)';
    }
    if (param.type.kind == UtsTypeKind.primitive &&
        param.type.name == 'Duration') {
      // Convert microseconds Int to TimeInterval (seconds as Double)
      return 'let ${param.name}Interval = TimeInterval(Double(${param.name}) / 1_000_000.0)';
    }
    if (param.type.kind == UtsTypeKind.primitive && param.type.name == 'Uri') {
      final opt = param.isOptional || param.type.nullable ? '?' : '!';
      return 'let ${param.name}URL = URL(string: ${param.name}$opt)';
    }
    if (param.type.kind == UtsTypeKind.primitive &&
        param.type.name == 'Uint8List') {
      return 'let ${param.name}Data = ${param.name}.data';
    }
    return null;
  }

  /// Returns the Swift expression for converting a return value.
  String _resultConversion(UnifiedTypeSchema schema, UtsType type) {
    switch (type.kind) {
      case UtsTypeKind.primitive:
        if (type.name == 'DateTime') {
          return 'ISO8601DateFormatter().string(from: nativeResult)';
        }
        if (type.name == 'Duration') {
          // TimeInterval (seconds) → microseconds Int
          return 'Int(nativeResult * 1_000_000)';
        }
        if (type.name == 'Uri') {
          return 'nativeResult.absoluteString';
        }
        if (type.name == 'Uint8List') {
          return 'FlutterStandardTypedData(bytes: nativeResult)';
        }
        return 'nativeResult';
      case UtsTypeKind.object:
        // Check if it's a reference type (class with instance methods)
        final cls = schema.classes.where((c) => c.name == type.name).toList();
        if (cls.isNotEmpty && cls.first.methods.any((m) => !m.isStatic)) {
          return 'createHandle(nativeResult)';
        }
        // Check if it's a known data class in the schema
        if (schema.types.any((t) => t.name == type.name)) {
          return 'encode(nativeResult)';
        }
        return 'nativeResult';
      case UtsTypeKind.nativeObject:
        return 'createHandle(nativeResult)';
      case UtsTypeKind.enumType:
        return 'String(describing: nativeResult)';
      case UtsTypeKind.list:
        return 'nativeResult';
      case UtsTypeKind.map:
        return 'nativeResult';
      case UtsTypeKind.voidType:
        return 'nil';
      default:
        return 'nativeResult';
    }
  }

  /// Checks if a named type is a reference type class (has instance methods).
  bool _isReferenceTypeClass(UnifiedTypeSchema schema, String typeName) {
    final cls = schema.classes.where((c) => c.name == typeName).toList();
    return cls.isNotEmpty && cls.first.methods.any((m) => !m.isStatic);
  }

  /// Collects type names that are referenced by auto-generated methods
  /// (methods without nativeBody). Types only used in nativeBody methods
  /// don't need encode/decode helpers.
  Set<String> _typesNeededByAutoGeneratedMethods(UnifiedTypeSchema schema) {
    final needed = <String>{};
    final typeNames = schema.types.map((t) => t.name).toSet();

    void collectFromType(UtsType type) {
      if (type.kind == UtsTypeKind.object && typeNames.contains(type.name)) {
        needed.add(type.name);
        // Also collect nested types from this type's fields
        final typeDef = schema.types.firstWhere((t) => t.name == type.name);
        for (final field in typeDef.fields) {
          collectFromType(field.type);
        }
      }
      type.typeArguments?.forEach(collectFromType);
    }

    void collectFromMethod(UtsMethod method) {
      // Skip methods with nativeBody — they handle their own serialization
      if (method.nativeBody?['swift'] != null) return;
      // Skip stream methods with onListen nativeBody — data is produced inline
      if (method.returnType.kind == UtsTypeKind.stream &&
          method.nativeBody?['swift_onListen'] != null) {
        return;
      }
      collectFromType(method.returnType);
      for (final param in method.parameters) {
        collectFromType(param.type);
      }
    }

    for (final fn in schema.functions) {
      collectFromMethod(fn);
    }
    for (final cls in schema.classes) {
      for (final method in cls.methods) {
        collectFromMethod(method);
      }
    }
    return needed;
  }

  /// Collects enum names that are referenced by auto-generated methods
  /// (methods without nativeBody). Enums only used in nativeBody methods
  /// don't need decode helpers since the native code handles them directly.
  Set<String> _enumsNeededByAutoGeneratedMethods(UnifiedTypeSchema schema) {
    final needed = <String>{};
    final enumNames = schema.enums.map((e) => e.name).toSet();

    void collectFromType(UtsType type) {
      if (type.kind == UtsTypeKind.enumType && enumNames.contains(type.name)) {
        needed.add(type.name);
      }
      type.typeArguments?.forEach(collectFromType);
    }

    void collectFromMethod(UtsMethod method) {
      if (method.nativeBody?['swift'] != null) return;
      if (method.returnType.kind == UtsTypeKind.stream &&
          method.nativeBody?['swift_onListen'] != null) {
        return;
      }
      collectFromType(method.returnType);
      for (final param in method.parameters) {
        collectFromType(param.type);
      }
    }

    for (final fn in schema.functions) {
      collectFromMethod(fn);
    }
    for (final cls in schema.classes) {
      for (final method in cls.methods) {
        collectFromMethod(method);
      }
    }
    return needed;
  }

  // --- Naming helpers ---

  static String _toSnakeCase(String input) {
    return input
        .replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_')
        .replaceAll(RegExp(r'_+'), '_')
        .replaceAll(RegExp(r'^_|_$'), '')
        .toLowerCase();
  }

  static String _toPascalCase(String input) {
    return input
        .replaceAll(RegExp(r'[^a-zA-Z0-9]'), ' ')
        .split(RegExp(r'\s+'))
        .where((s) => s.isNotEmpty)
        .map((s) => s[0].toUpperCase() + s.substring(1).toLowerCase())
        .join();
  }
}

/// Info about a stream method for onListen/onCancel dispatch.
class _StreamMethodInfo {
  final String channelMethod;
  final String? onListenBody;
  final String? onCancelBody;
  final UtsMethod method;
  final String? className;
  final bool isStatic;

  _StreamMethodInfo({
    required this.channelMethod,
    this.onListenBody,
    this.onCancelBody,
    required this.method,
    this.className,
    this.isStatic = true,
  });
}
