import '../schema/unified_type_schema.dart';
import 'generator_base.dart';

/// Generates Swift platform channel handler code for iOS.
///
/// Produces a Swift `FlutterPlugin` class that:
/// - Registers a `FlutterMethodChannel` via `register(with:)`
/// - Dispatches method calls via `switch call.method`
/// - Extracts arguments and converts types
/// - Returns results or errors
class SwiftGlueGenerator extends GeneratorBase {
  @override
  Map<String, String> generate(UnifiedTypeSchema schema) {
    final className = _toPascalCase(schema.package);
    final fileName = '${className}Plugin.swift';
    return {fileName: generateSwiftCode(schema)};
  }

  /// Generates the full Swift plugin source code.
  String generateSwiftCode(UnifiedTypeSchema schema) {
    final buffer = StringBuffer();
    final className = _toPascalCase(schema.package);
    final channelName = _toSnakeCase(schema.package);
    final hasStreams = _hasStreamMethods(schema);

    _writeHeader(buffer, schema);
    _writeImports(buffer);
    buffer.writeln();
    _writePluginClass(buffer, schema, className, channelName,
        hasStreams: hasStreams);

    return buffer.toString();
  }

  bool _hasStreamMethods(UnifiedTypeSchema schema) {
    for (final fn in schema.functions) {
      if (fn.returnType.kind == UtsTypeKind.stream) return true;
    }
    for (final cls in schema.classes) {
      for (final m in cls.methods) {
        if (m.returnType.kind == UtsTypeKind.stream) return true;
      }
    }
    return false;
  }

  void _writeHeader(StringBuffer buffer, UnifiedTypeSchema schema) {
    buffer.writeln('// GENERATED CODE — DO NOT EDIT');
    buffer.writeln('// Generated by auto_interop_generator');
    buffer.writeln(
        '// Swift platform channel handler for ${schema.package}');
    buffer.writeln();
  }

  void _writeImports(StringBuffer buffer) {
    buffer.writeln('import Flutter');
    buffer.writeln('import UIKit');
  }

  void _writePluginClass(StringBuffer buffer, UnifiedTypeSchema schema,
      String className, String channelName, {bool hasStreams = false}) {
    final protocols = hasStreams
        ? 'NSObject, FlutterPlugin, FlutterStreamHandler'
        : 'NSObject, FlutterPlugin';
    buffer.writeln(
        'public class ${className}Plugin: $protocols {');

    if (hasStreams) {
      buffer.writeln('    private var eventSink: FlutterEventSink?');
      buffer.writeln();
    }

    // register(with:)
    buffer.writeln(
        '    public static func register(with registrar: FlutterPluginRegistrar) {');
    buffer.writeln(
        '        let channel = FlutterMethodChannel(name: "$channelName", binaryMessenger: registrar.messenger())');
    buffer.writeln(
        '        let instance = ${className}Plugin()');
    buffer.writeln(
        '        registrar.addMethodCallDelegate(instance, channel: channel)');
    if (hasStreams) {
      buffer.writeln(
          '        let eventChannel = FlutterEventChannel(name: "$channelName/events", binaryMessenger: registrar.messenger())');
      buffer.writeln(
          '        eventChannel.setStreamHandler(instance)');
    }
    buffer.writeln('    }');
    buffer.writeln();

    // handle(_:result:)
    buffer.writeln(
        '    public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {');

    // Collect all method cases
    final hasMethods =
        schema.functions.isNotEmpty || schema.classes.any((c) => c.methods.isNotEmpty);

    if (hasMethods) {
      buffer.writeln(
          '        guard let args = call.arguments as? [String: Any] else {');
      buffer.writeln(
          '            result(FlutterError(code: "ARGS", message: "Invalid arguments", details: nil))');
      buffer.writeln('            return');
      buffer.writeln('        }');
      buffer.writeln();
      buffer.writeln('        switch call.method {');

      // Top-level functions
      for (final fn in schema.functions) {
        _writeMethodCase(buffer, fn, indent: '        ');
      }

      // Class methods (prefixed with className)
      for (final cls in schema.classes) {
        for (final method in cls.methods) {
          _writeMethodCase(buffer, method,
              indent: '        ', prefix: '${cls.name}.');
        }
      }

      buffer.writeln('        default:');
      buffer.writeln('            result(FlutterMethodNotImplemented)');
      buffer.writeln('        }');
    } else {
      buffer.writeln('        result(FlutterMethodNotImplemented)');
    }

    buffer.writeln('    }');

    // FlutterStreamHandler methods
    if (hasStreams) {
      buffer.writeln();
      buffer.writeln(
          '    public func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink) -> FlutterError? {');
      buffer.writeln('        self.eventSink = events');
      buffer.writeln('        return nil');
      buffer.writeln('    }');
      buffer.writeln();
      buffer.writeln(
          '    public func onCancel(withArguments arguments: Any?) -> FlutterError? {');
      buffer.writeln('        self.eventSink = nil');
      buffer.writeln('        return nil');
      buffer.writeln('    }');
    }

    buffer.writeln('}');
  }

  void _writeMethodCase(StringBuffer buffer, UtsMethod method,
      {String indent = '', String prefix = ''}) {
    final methodName = '$prefix${method.name}';
    buffer.writeln('${indent}case "$methodName":');

    // Extract arguments
    for (final param in method.parameters) {
      final swiftType = _toSwiftType(param.type);
      if (param.isOptional || param.type.nullable) {
        buffer.writeln(
            '$indent    let ${param.name} = args["${param.name}"] as? $swiftType');
      } else {
        buffer.writeln(
            '$indent    let ${param.name} = args["${param.name}"] as! $swiftType');
      }
    }

    // Type conversion for special types
    for (final param in method.parameters) {
      final conversion = _argumentConversion(param);
      if (conversion != null) {
        buffer.writeln('$indent    $conversion');
      }
    }

    // Call the method and return result
    final returnType = method.returnType;
    if (returnType.kind == UtsTypeKind.stream) {
      buffer.writeln('$indent    // TODO: Set up stream and send events via eventSink');
      buffer.writeln('$indent    result(nil)');
    } else if (returnType.kind == UtsTypeKind.voidType) {
      buffer.writeln('$indent    // TODO: Call native method');
      buffer.writeln('$indent    result(nil)');
    } else if (returnType.kind == UtsTypeKind.future) {
      buffer.writeln('$indent    do {');
      buffer.writeln('$indent        // TODO: Call native async method');
      buffer.writeln('$indent        result(nil)');
      buffer.writeln('$indent    } catch {');
      buffer.writeln(
          '$indent        result(FlutterError(code: "ERROR", message: error.localizedDescription, details: nil))');
      buffer.writeln('$indent    }');
    } else {
      buffer.writeln('$indent    do {');
      buffer.writeln('$indent        // TODO: Call native method');
      final resultConversion = _resultConversion(returnType);
      buffer.writeln('$indent        result($resultConversion)');
      buffer.writeln('$indent    } catch {');
      buffer.writeln(
          '$indent        result(FlutterError(code: "ERROR", message: error.localizedDescription, details: nil))');
      buffer.writeln('$indent    }');
    }
  }

  /// Maps UTS type to Swift type string for argument extraction.
  String _toSwiftType(UtsType type) {
    switch (type.kind) {
      case UtsTypeKind.primitive:
        switch (type.name) {
          case 'String':
            return 'String';
          case 'int':
            return 'Int';
          case 'double':
            return 'Double';
          case 'bool':
            return 'Bool';
          case 'DateTime':
            return 'String'; // ISO 8601
          case 'Uint8List':
            return 'FlutterStandardTypedData';
          default:
            return 'Any';
        }
      case UtsTypeKind.object:
        return '[String: Any]';
      case UtsTypeKind.list:
        return '[Any]';
      case UtsTypeKind.map:
        return '[String: Any]';
      case UtsTypeKind.enumType:
        return 'String';
      case UtsTypeKind.callback:
        return 'String'; // callback ID
      case UtsTypeKind.voidType:
        return 'Void';
      case UtsTypeKind.dynamic:
        return 'Any';
      default:
        return 'Any';
    }
  }

  /// Returns additional conversion code for a parameter, or null if none needed.
  String? _argumentConversion(UtsParameter param) {
    if (param.type.kind == UtsTypeKind.primitive &&
        param.type.name == 'DateTime') {
      final opt = param.isOptional || param.type.nullable ? '?' : '!';
      return 'let ${param.name}Date = ISO8601DateFormatter().date(from: ${param.name}$opt)';
    }
    return null;
  }

  /// Returns the Swift expression for converting a return value.
  String _resultConversion(UtsType type) {
    if (type.kind == UtsTypeKind.primitive && type.name == 'DateTime') {
      return 'ISO8601DateFormatter().string(from: nativeResult)';
    }
    return 'nil /* TODO: convert native result */';
  }

  // --- Naming helpers ---

  static String _toSnakeCase(String input) {
    return input
        .replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_')
        .replaceAll(RegExp(r'_+'), '_')
        .replaceAll(RegExp(r'^_|_$'), '')
        .toLowerCase();
  }

  static String _toPascalCase(String input) {
    return input
        .replaceAll(RegExp(r'[^a-zA-Z0-9]'), ' ')
        .split(RegExp(r'\s+'))
        .where((s) => s.isNotEmpty)
        .map((s) => s[0].toUpperCase() + s.substring(1).toLowerCase())
        .join();
  }
}
