// GENERATED CODE — DO NOT EDIT
// Generated by auto_interop_generator

import 'package:auto_interop/auto_interop.dart';

/// HTTP methods supported by Alamofire.
enum HTTPMethod {
  get,
  post,
  put,
  delete,
  patch,
  head,
  options;
}

/// Configuration for a URL request.
class URLRequestConfig {
  /// The request URL.
  final String url;
  /// The HTTP method.
  final String method;
  /// Optional request headers.
  final Map<String, String>? headers;
  /// Optional request body.
  final Uint8List? body;
  /// Timeout interval in seconds.
  final double timeoutInterval;

  URLRequestConfig({required this.url, required this.method, this.headers, this.body, required this.timeoutInterval});

  factory URLRequestConfig.fromMap(Map<String, dynamic> map) {
    return URLRequestConfig(
      url: map['url'] as String,
      method: map['method'] as String,
      headers: map['headers'] as Map<String, String>?,
      body: map['body'] as Uint8List?,
      timeoutInterval: map['timeoutInterval'] as double,
    );
  }

  Map<String, dynamic> toMap() => {
    'url': url,
    'method': method,
    if (headers != null) 'headers': headers,
    if (body != null) 'body': body,
    'timeoutInterval': timeoutInterval,
  };
}

/// Represents the response from an HTTP request.
class DataResponse {
  /// The response data.
  final Uint8List? data;
  /// The HTTP status code.
  final int statusCode;
  /// Response headers.
  final Map<String, String> headers;

  DataResponse({this.data, required this.statusCode, required this.headers});

  factory DataResponse.fromMap(Map<String, dynamic> map) {
    return DataResponse(
      data: map['data'] as Uint8List?,
      statusCode: map['statusCode'] as int,
      headers: map['headers'] as Map<String, String>,
    );
  }

  Map<String, dynamic> toMap() => {
    if (data != null) 'data': data,
    'statusCode': statusCode,
    'headers': headers,
  };
}

/// Manages HTTP requests with session management.
abstract interface class SessionInterface {
  /// Makes an HTTP request.
  Future<DataRequest> request(String url, String method, Map<String, String>? headers);

  /// Downloads a file from a URL.
  Future<Future<String>> download(String url, String? destination);

  /// Uploads data to a URL.
  Future<Future<String>> upload(Uint8List data, String url);
}

/// Manages HTTP requests with session management.
class Session implements SessionInterface {
  static const _channel = AutoInteropChannel('alamofire');


  /// Makes an HTTP request.
  @override
  Future<DataRequest> request(String url, String method, Map<String, String>? headers) async {
    final result = await _channel.invoke<DataRequest>('request', {
      'url': url,
      'method': method,
      'headers': headers,
    });
    return result;
  }

  /// Downloads a file from a URL.
  @override
  Future<Future<String>> download(String url, String? destination) async {
    final result = await _channel.invoke<Future<String>>('download', {
      'url': url,
      'destination': destination,
    });
    return result;
  }

  /// Uploads data to a URL.
  @override
  Future<Future<String>> upload(Uint8List data, String url) async {
    final result = await _channel.invoke<Future<String>>('upload', {
      'data': data,
      'url': url,
    });
    return result;
  }
}

/// Represents an HTTP data request.
abstract interface class DataRequestInterface {
  /// Adds a response handler.
  Future<Future<DataResponse>> response();

  /// Cancels the request.
  Future<void> cancel();

  /// Resumes the request.
  Future<void> resume();
}

/// Represents an HTTP data request.
class DataRequest implements DataRequestInterface {
  static const _channel = AutoInteropChannel('alamofire');


  /// Adds a response handler.
  @override
  Future<Future<DataResponse>> response() async {
    final result = await _channel.invoke<Future<DataResponse>>('response');
    return result;
  }

  /// Cancels the request.
  @override
  Future<void> cancel() async {
    await _channel.invoke<void>('cancel');
  }

  /// Resumes the request.
  @override
  Future<void> resume() async {
    await _channel.invoke<void>('resume');
  }
}

