// GENERATED CODE — DO NOT EDIT
// Generated by auto_interop_generator
// Swift platform channel handler for Alamofire

import Flutter
import UIKit

public class AlamofirePlugin: NSObject, FlutterPlugin {
    public static func register(with registrar: FlutterPluginRegistrar) {
        let channel = FlutterMethodChannel(name: "alamofire", binaryMessenger: registrar.messenger())
        let instance = AlamofirePlugin()
        registrar.addMethodCallDelegate(instance, channel: channel)
    }

    public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        guard let args = call.arguments as? [String: Any] else {
            result(FlutterError(code: "ARGS", message: "Invalid arguments", details: nil))
            return
        }

        switch call.method {
        case "Session.request":
            let url = args["url"] as! String
            let method = args["method"] as! String
            let headers = args["headers"] as? [String: Any]
            do {
                // TODO: Call native method
                result(nil /* TODO: convert native result */)
            } catch {
                result(FlutterError(code: "ERROR", message: error.localizedDescription, details: nil))
            }
        case "Session.download":
            let url = args["url"] as! String
            let destination = args["destination"] as? String
            do {
                // TODO: Call native async method
                result(nil)
            } catch {
                result(FlutterError(code: "ERROR", message: error.localizedDescription, details: nil))
            }
        case "Session.upload":
            let data = args["data"] as! FlutterStandardTypedData
            let url = args["url"] as! String
            do {
                // TODO: Call native async method
                result(nil)
            } catch {
                result(FlutterError(code: "ERROR", message: error.localizedDescription, details: nil))
            }
        case "DataRequest.response":
            do {
                // TODO: Call native async method
                result(nil)
            } catch {
                result(FlutterError(code: "ERROR", message: error.localizedDescription, details: nil))
            }
        case "DataRequest.cancel":
            // TODO: Call native method
            result(nil)
        case "DataRequest.resume":
            // TODO: Call native method
            result(nil)
        default:
            result(FlutterMethodNotImplemented)
        }
    }
}
