/// Entry point for `build_runner`.
///
/// This library provides the builder factory used by `build_runner` to
/// generate Dart bindings from native package definitions.
///
/// Add to your `build.yaml`:
/// ```yaml
/// targets:
///   $default:
///     builders:
///       auto_interop_generator|auto_interop:
///         enabled: true
/// ```
library;

import 'dart:isolate';

import 'package:build/build.dart';
import 'package:path/path.dart' as p;

import 'src/analyzer/api_surface_analyzer.dart';
import 'src/config/config_parser.dart';
import 'src/generators/dart_generator.dart';
import 'src/resolver/override_loader.dart';
import 'src/type_definitions/type_definition_loader.dart';

/// Builder factory for build_runner.
Builder autoInteropBuilder(BuilderOptions options) {
  return AutoInteropBuilder(options);
}

/// A [Builder] that generates Dart bindings from `auto_interop.yaml`.
///
/// This builder reads the config file, resolves schemas (from pre-built
/// type definitions or by parsing), and outputs generated Dart files.
class AutoInteropBuilder implements Builder {
  final BuilderOptions options;
  final ConfigParser _configParser = ConfigParser();
  final DartGenerator _dartGen = DartGenerator();

  AutoInteropBuilder(this.options);

  /// Resolves the type definitions directory from the generator package.
  Future<TypeDefinitionLoader> _createLoader() async {
    final packageUri =
        Uri.parse('package:auto_interop_generator/src/type_definitions/');
    final resolved = await Isolate.resolvePackageUri(packageUri);
    if (resolved != null) {
      return TypeDefinitionLoader(definitionsDir: p.fromUri(resolved));
    }
    // Fallback to relative path
    return TypeDefinitionLoader(definitionsDir: 'lib/src/type_definitions');
  }

  @override
  Map<String, List<String>> get buildExtensions => {
        'auto_interop.yaml': ['lib/generated/auto_interop_bindings.dart'],
      };

  @override
  Future<void> build(BuildStep buildStep) async {
    final inputId = buildStep.inputId;
    final content = await buildStep.readAsString(inputId);

    AutoInteropConfig config;
    try {
      config = _configParser.parseYaml(content);
    } on ConfigParseException catch (e) {
      log.warning('Error parsing auto_interop.yaml: $e');
      return;
    }

    if (config.packages.isEmpty) {
      log.info('No packages in auto_interop.yaml');
      return;
    }

    final buffer = StringBuffer();
    buffer.writeln('// GENERATED CODE — DO NOT EDIT');
    buffer.writeln('// Generated by auto_interop_generator via build_runner');
    buffer.writeln();
    buffer.writeln("import 'package:auto_interop/auto_interop.dart';");
    buffer.writeln();

    final loader = await _createLoader();
    final overrideLoader = OverrideLoader(
      projectDir: config.overridesDir ?? 'auto_interop_overrides',
    );

    for (final spec in config.packages) {
      // Check overrides first (project then global), then fall back to loader
      final overrideResult = overrideLoader.load(
        spec.package,
        source: spec.source.name,
        version: spec.version,
      );
      final schema =
          overrideResult?.schema ?? loader.loadForPackage(spec.package);
      if (schema == null) {
        log.warning('No pre-built type definition for ${spec.package}. '
            'Run the CLI to parse and generate definitions first.');
        continue;
      }

      // Run analyzer before generating
      final analysisResult = const ApiSurfaceAnalyzer().analyze(schema);
      for (final d in analysisResult.diagnostics) {
        if (d.isError) {
          log.severe('[${spec.package}] $d');
        } else {
          log.warning('[${spec.package}] $d');
        }
      }
      if (analysisResult.hasErrors) {
        log.severe('Skipping ${spec.package} due to analysis errors');
        continue;
      }

      final files = _dartGen.generate(schema);
      for (final entry in files.entries) {
        // Strip the header from individual files since we have a combined header
        final code = entry.value
            .replaceFirst(RegExp(r'// GENERATED CODE.*\n'), '')
            .replaceFirst(RegExp(r'// Generated by.*\n'), '')
            .replaceFirst(
                RegExp(r"import 'package:auto_interop/auto_interop.dart';\n"),
                '')
            .trim();
        buffer.writeln('// --- ${spec.package} ---');
        buffer.writeln(code);
        buffer.writeln();
      }
    }

    await buildStep.writeAsString(
      AssetId(inputId.package, 'lib/generated/auto_interop_bindings.dart'),
      buffer.toString(),
    );
  }
}
