// GENERATED CODE — DO NOT EDIT
// Generated by auto_interop_generator
//
// Call registerAutoInteropPlugins(with:) from MainFlutterWindow
// to register all generated native plugins.
//
// In your MainFlutterWindow.swift (macOS), add after RegisterGeneratedPlugins:
//   registerAutoInteropPlugins(with: flutterViewController.registrar(forPlugin: "AutoInteropPlugins"))
//
// In your AppDelegate.swift (iOS), add in application(_:didFinishLaunchingWithOptions:):
//   registerAutoInteropPlugins(with: self.registrar(forPlugin: "AutoInteropPlugins")!)

#if os(macOS)
import FlutterMacOS
#else
import Flutter
#endif

public func registerAutoInteropPlugins(with registrar: FlutterPluginRegistrar) {
    AlamofirePlugin.register(with: registrar)
    SensorStreamPlugin.register(with: registrar)
    FileDownloaderPlugin.register(with: registrar)
}
