// GENERATED CODE — DO NOT EDIT
// Generated by auto_interop_generator
// Swift platform channel handler for Alamofire

#if os(macOS)
import FlutterMacOS
#else
import Flutter
import UIKit
#endif
import Alamofire

public class AlamofirePlugin: NSObject, FlutterPlugin {
    private var channel: FlutterMethodChannel!
    private var instances: [String: AnyObject] = [:]
    private var nextHandle: Int = 0

    public static func register(with registrar: FlutterPluginRegistrar) {
        #if os(macOS)
        let messenger = registrar.messenger
        #else
        let messenger = registrar.messenger()
        #endif
        let channel = FlutterMethodChannel(name: "auto_interop/alamofire", binaryMessenger: messenger)
        let instance = AlamofirePlugin()
        instance.channel = channel
        registrar.addMethodCallDelegate(instance, channel: channel)
    }

    private func createHandle(_ obj: AnyObject) -> String {
        let handle = "h_\(nextHandle)"
        nextHandle += 1
        instances[handle] = obj
        return handle
    }

    private func releaseHandle(_ handle: String) {
        instances.removeValue(forKey: handle)
    }

    private func decodeHTTPMethod(_ value: String) -> HTTPMethod {
        switch value {
        case "get": return .get
        case "post": return .post
        case "put": return .put
        case "delete": return .delete
        case "patch": return .patch
        case "head": return .head
        case "options": return .options
        default: fatalError("Unknown HTTPMethod value: \(value)")
        }
    }

    public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        let args = (call.arguments as? [String: Any]) ?? [:]

        switch call.method {
        case "Session._create":
            let instance = Session()
            let handle = createHandle(instance)
            result(handle)
        case "Session.request":
            let url = args["url"] as! String
            let method = args["method"] as! String
            let headers = args["headers"] as? [String: String]
            let handle = args["_handle"] as! String
            let instance = instances[handle] as! Session
            let nativeResult = instance.request(url, method: decodeHTTPMethod(method), headers: headers != nil ? HTTPHeaders(headers!) : nil)
            result(createHandle(nativeResult))
        case "Session.download":
            let url = args["url"] as! String
            let destination = args["destination"] as? String
            let handle = args["_handle"] as! String
            let instance = instances[handle] as! Session
            let downloadRequest = instance.download(url)
            downloadRequest.responseData { response in
                switch response.result {
                case .success(let data):
                    if let dest = destination {
                        try? data.write(to: URL(fileURLWithPath: dest))
                        DispatchQueue.main.async { result(dest) }
                    } else {
                        DispatchQueue.main.async { result("downloaded \(data.count) bytes") }
                    }
                case .failure(let error):
                    DispatchQueue.main.async {
                        result(FlutterError(code: "ALAMOFIRE_ERROR", message: error.localizedDescription, details: nil))
                    }
                }
            }
        case "Session.upload":
            let data = args["data"] as! FlutterStandardTypedData
            let url = args["url"] as! String
            let handle = args["_handle"] as! String
            let instance = instances[handle] as! Session
            instance.upload(data.data, to: url).responseData { response in
                switch response.result {
                case .success:
                    DispatchQueue.main.async { result("uploaded \(data.data.count) bytes") }
                case .failure(let error):
                    DispatchQueue.main.async {
                        result(FlutterError(code: "ALAMOFIRE_ERROR", message: error.localizedDescription, details: nil))
                    }
                }
            }
        case "DataRequest.response":
            let handle = args["_handle"] as! String
            let instance = instances[handle] as! Alamofire.DataRequest
            instance.responseData { response in
                var dict: [String: Any] = [:]
                if let data = response.data {
                    dict["data"] = FlutterStandardTypedData(bytes: data)
                }
                dict["statusCode"] = response.response?.statusCode ?? 0
                var headerDict: [String: String] = [:]
                if let allHeaders = response.response?.allHeaderFields {
                    for (key, value) in allHeaders {
                        headerDict[String(describing: key)] = String(describing: value)
                    }
                }
                dict["headers"] = headerDict
                DispatchQueue.main.async {
                    result(dict)
                }
            }
        case "DataRequest.cancel":
            let handle = args["_handle"] as! String
            let instance = instances[handle] as! DataRequest
            instance.cancel()
            result(nil)
        case "DataRequest.resume":
            let handle = args["_handle"] as! String
            let instance = instances[handle] as! DataRequest
            instance.resume()
            result(nil)
        case "_dispose":
            let handle = args["_handle"] as! String
            releaseHandle(handle)
            result(nil)
        default:
            result(FlutterMethodNotImplemented)
        }
    }
}
