// GENERATED CODE — DO NOT EDIT
// Generated by auto_interop_generator
// Swift platform channel handler for file_downloader

#if os(macOS)
import FlutterMacOS
#else
import Flutter
import UIKit
#endif

public class FileDownloaderPlugin: NSObject, FlutterPlugin {
    private var channel: FlutterMethodChannel!
    private var callbackChannel: FlutterMethodChannel!

    public static func register(with registrar: FlutterPluginRegistrar) {
        #if os(macOS)
        let messenger = registrar.messenger
        #else
        let messenger = registrar.messenger()
        #endif
        let channel = FlutterMethodChannel(name: "auto_interop/file_downloader", binaryMessenger: messenger)
        let instance = FileDownloaderPlugin()
        instance.channel = channel
        registrar.addMethodCallDelegate(instance, channel: channel)
        instance.callbackChannel = FlutterMethodChannel(name: "auto_interop/callbacks", binaryMessenger: messenger)
    }

    public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        let args = (call.arguments as? [String: Any]) ?? [:]

        switch call.method {
        case "download":
            let args = (call.arguments as? [String: Any]) ?? [:]
            let url = args["url"] as! String
            let destination = args["destination"] as! String
            let onProgressId = args["onProgress"] as? String
            let onCompleteId = args["onComplete"] as? String
            result(nil)
            guard let downloadUrl = URL(string: url) else {
                DispatchQueue.main.async {
                    if let cId = onCompleteId {
                        self.callbackChannel.invokeMethod(cId, arguments: ["failed", "Invalid URL"])
                    }
                }
                return
            }
            var simulatedProgress = 0.0
            var progressTimer: Timer?
            if let pId = onProgressId {
                progressTimer = Timer.scheduledTimer(withTimeInterval: 0.2, repeats: true) { [weak self] _ in
                    simulatedProgress = min(simulatedProgress + Double.random(in: 0.05...0.15), 0.95)
                    let pm: [String: Any] = ["bytesReceived": Int(simulatedProgress * 1048576), "totalBytes": 1048576, "progress": simulatedProgress]
                    self?.callbackChannel.invokeMethod(pId, arguments: [pm])
                }
            }
            let task = URLSession.shared.downloadTask(with: downloadUrl) { [weak self] tempUrl, _, error in
                DispatchQueue.main.async { progressTimer?.invalidate() }
                if let error = error {
                    DispatchQueue.main.async {
                        if let cId = onCompleteId { self?.callbackChannel.invokeMethod(cId, arguments: ["failed", error.localizedDescription]) }
                    }
                    return
                }
                if let tempUrl = tempUrl {
                    let destURL = URL(fileURLWithPath: destination)
                    try? FileManager.default.removeItem(at: destURL)
                    try? FileManager.default.moveItem(at: tempUrl, to: destURL)
                }
                DispatchQueue.main.async {
                    if let pId = onProgressId {
                        let fp: [String: Any] = ["bytesReceived": 1048576, "totalBytes": 1048576, "progress": 1.0]
                        self?.callbackChannel.invokeMethod(pId, arguments: [fp])
                    }
                    if let cId = onCompleteId { self?.callbackChannel.invokeMethod(cId, arguments: ["completed", nil]) }
                }
            }
            task.resume()
        case "cancelAll":
            result(nil)
        default:
            result(FlutterMethodNotImplemented)
        }
    }
}
