// GENERATED CODE — DO NOT EDIT
// Generated by auto_interop_generator
// Swift platform channel handler for sensor_stream

#if os(macOS)
import FlutterMacOS
#else
import Flutter
import UIKit
#endif
import CoreMotion

public class SensorStreamPlugin: NSObject, FlutterPlugin, FlutterStreamHandler {
    private var channel: FlutterMethodChannel!
    private var eventSink: FlutterEventSink?
    private let motionManager = CMMotionManager()

    public static func register(with registrar: FlutterPluginRegistrar) {
        #if os(macOS)
        let messenger = registrar.messenger
        #else
        let messenger = registrar.messenger()
        #endif
        let channel = FlutterMethodChannel(name: "auto_interop/sensor_stream", binaryMessenger: messenger)
        let instance = SensorStreamPlugin()
        instance.channel = channel
        registrar.addMethodCallDelegate(instance, channel: channel)
        let eventChannel = FlutterEventChannel(name: "auto_interop/sensor_stream/events", binaryMessenger: messenger)
        eventChannel.setStreamHandler(instance)
    }

    public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        let args = (call.arguments as? [String: Any]) ?? [:]

        switch call.method {
        case "accelerometerEvents":
            let samplingRate = args["samplingRate"] as? Int
            // Stream: events forwarded via eventSink
            result(nil)
        case "stopAll":
            result(nil)
        default:
            result(FlutterMethodNotImplemented)
        }
    }

    public func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink) -> FlutterError? {
        self.eventSink = events
        let args = (arguments as? [String: Any]) ?? [:]
        #if os(iOS)
        guard motionManager.isAccelerometerAvailable else {
            events(FlutterError(code: "UNAVAILABLE", message: "Accelerometer not available on this device", details: nil))
            return nil
        }
        let rate = (args["samplingRate"] as? Int) ?? 60
        motionManager.accelerometerUpdateInterval = 1.0 / Double(rate)
        motionManager.startAccelerometerUpdates(to: .main) { [weak self] data, error in
            if let error = error {
                self?.eventSink?(FlutterError(code: "SENSOR_ERROR", message: error.localizedDescription, details: nil))
                return
            }
            guard let data = data else { return }
            let event: [String: Any] = [
                "x": data.acceleration.x,
                "y": data.acceleration.y,
                "z": data.acceleration.z,
                "timestamp": ISO8601DateFormatter().string(from: Date())
            ]
            self?.eventSink?(event)
        }
        #else
        events(FlutterError(code: "PLATFORM_UNSUPPORTED", message: "Accelerometer is not available on macOS", details: nil))
        #endif
        return nil
    }

    public func onCancel(withArguments arguments: Any?) -> FlutterError? {
        motionManager.stopAccelerometerUpdates()
        self.eventSink = nil
        return nil
    }
}
