name: Publish to pub.dev

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-generator:
    name: Publish generator
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: packages/auto_interop_generator
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test

      - name: Publish
        run: dart pub publish --force

  publish-runtime:
    name: Publish runtime
    needs: publish-generator
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: packages/auto_interop
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Publish
        run: flutter pub publish --force
